### ISSUE TITLE
Flickering on mobile browsers after latest Construct 3 upgrade

### ISSUE THREAD

**Issue by DuckSeason51** [Scirra/Construct-bugs#7831] opened 2024-02-14 14:57 UTC
## Problem description

After upgrading to the new version of Construct 3, I'm observing flickering in my game on mobile versions of Safari and Chrome on iOS.

## Attach a .c3p

[version-with-flicker.zip](https://github.com/Scirra/Construct-bugs/files/14280986/version-with-flicker.zip)

## Steps to reproduce

1. Export project to HTML5
2. Deploy to hosting service
3. Open website on iPhone in Safari or Chrome
4. Click Let's Go!
5. Click Let's Go! again on Help Page
6. Click Skip Combo to observe again
7. This is also observable in Remote Preview mode (without having to deploy)
8. You can also observe it here: https://license-to-spell--lts-test-avc1ngbk.web.app/

## Observed result

Flickering in images at top of screen as well as license plate image

## Expected result

Images should not flicker

## More details

To try to isolate the issue, I tested two versions of an HTML5 export that were based on the same underlying project files. The first was generated by my previous version of Construct3 and the second was generated using r379. I did not observe any flickering on the old pre-r379 export, but did observe flickering on the r379 export, even though the underlying project files were the same. My steps were:

1. Pulled the project folder contents of my app from my GitHub repository from a point that I had saved before the r379 upgrade. This was the last version without the flickering.
2. Deployed the contents of the old HTML5 exported zip file to my hosting provider (this HTML5 export had been generated by Construct 3 before I upgraded to r379).
3. Tested on iPhone on Safari and Chrome
4. No flickering observed
5. Opened the old project files that I had just pulled from GitHub in Construct 3 r379.
6. Re-exported them as HTML5
7. Deployed the contents of the new HTML5 exported zip file to my hosting provider (this was a new HTML5 export created by r379, but with the same underlying project files that did not have flicker before)
8. Flicker is now present
9. I've also attached a zip of the old HTML5 export that does not have the flicker. It was generated on an older version of Construct 3 with the same underlying project files. 

[HTML5-export-without-flicker.zip](https://github.com/Scirra/Construct-bugs/files/14281265/HTML5-export-without-flicker.zip)

**Affected browsers/platforms:** 
iOS Safari and Chrome are affected
I don't see any flickering on Chrome on PC

**First affected release:** 
This started as soon as I upgraded to R379

## System details

<details><summary>View details</summary>

PASTE HERE
I don't have a crash report

</details>

**Comment by 19-KelvinLim** [comment] 2024-02-15 07:35
Experiencing this as well, only flickering on my mobile previews. PC previews remains stable with no flickers.

**Comment by AshleyScirra** [comment] 2024-02-15 13:21
I can reproduce some flickering on iOS. It goes away if I set 'Use worker' to 'No' in project properties. In this release Safari now supports worker mode, so I guess the flickering comes from a bug in Safari's handling of OffscreenCanvas.

Can you reproduce the problem in a minimal project as per the bug report guidelines? It is extremely difficult to diagnose problems in complex projects like the one you provided.

**Comment by 19-KelvinLim** [comment] 2024-02-15 16:09
Thanks for the help Ashley! it fixed my flickering issues on some layouts. I was using Google and Brave browser for my previews.
Sorry i'm new to this i did not know i have to make a bug report and follow the guidelines.

**Comment by DuckSeason51** [comment] 2024-02-15 23:12
Thank you, Ashley! I'm attaching a simplified version of my project where the flickering is still reproducible (sorry for not doing that sooner). 

[flicker_bug.zip](https://github.com/Scirra/Construct-bugs/files/14303316/flicker_bug.zip)

To reproduce the flickering with this project:

1. Open project in Remote Preview on Safari or Chrome on iOS
2. Click the "Spin!" button
3. Note the flickering of the sprites at the top of the screen labeled "Flicker layer". 

A few observations I made while building this that might help with troubleshooting:
1. My original app has six spinning columns and the flickering there is more pronounced than in this version of the app, which only has three columns. When I reduced the number of spinning columns to one in this version, I didn't notice any flickering. 
2. If I reorder the layers in this app to put the "flicker" layer on the bottom (make it index 0) then the flickering stops.
3. If I change the "User Worker" setting to "No" (as you suggested) then the flickering also stops! 

Note that the User Worker work around works on my "real" app as well, so the urgency to get this fixed just went way down, at least for me :-). 

Thanks for your quick response and the work around!

**Comment by AshleyScirra** [comment] 2024-02-19 13:20
Thanks, that looks like a decent repro. I think this is a bug in Safari, so I've filed it with Apple here: https://bugs.webkit.org/show_bug.cgi?id=269704
Closing this issue as we will follow up there.

I'm not sure how widespread this issue will prove to be in practice - we can change worker mode to default to off in Safari if it comes up a lot more, but let's wait and see first.

**Closed by AshleyScirra** 2024-02-19 13:20 UTC
