### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-bugs#8015] opened 2024-05-15 01:44 UTC
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'blob') @ TypeError: Cannot read properties of undefined (reading 'blob') at d.l (https://editor.construct.net/r391/projectResources.js:158:107) at async Xc.sE.yFa (https://editor.construct.net/r391/main.js:1288:286)
Stack: TypeError: Cannot read properties of undefined (reading 'blob') at d.l (https://editor.construct.net/r391/projectResources.js:158:107) at async Xc.sE.yFa (https://editor.construct.net/r391/main.js:1288:286)
Construct version: r391
URL: https://editor.construct.net/r391/
Date: Wed May 15 2024 03:37:46 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 23157.2 s

Platform information
Product: Construct 3 r391 (beta)
Browser: Chrome 124.0.6367.158
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: fr-FR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_stencil_texturing

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment] 2024-05-15 07:20
Could you please attach the project file and write the steps to reproduce?

**Comment by DiegoScirra** [comment] 2024-05-15 15:37
According to the stack trace this possibly has something to do with closing the Animations editor after making changes. Without more details it's not really feasible to look further into this though. Unless anymore information can be added, I will have to close this.

**Comment by DieppedalleDavid** [comment] 2024-05-15 18:18
Hello,

I did the same thing again and nothing happened.
Yes, I had opened an example of a game, copied a small part of an image from a sprite in this example and then pasted it into my project in one of my sprites, then it did that, but it didn't happen again.

**Comment by XHXIAIEIN** [comment] 2024-05-16 13:57
> I had opened an example of a game, copied a small part of an image from a sprite in this example and then pasted it into my project in one of my sprites, then it did that.

You need to describe more details steps to help you.

1. **What project did you open?**
You can find it from the start page via right click to open the content menu copying the link.

![image](https://github.com/Scirra/Construct-bugs/assets/45864744/384eba13-de04-4d2c-90d9-31fcc76e84f1)

2. **What object did you copy?**

Any more specific information would be helpful

**Comment by DieppedalleDavid** [comment] 2024-05-16 14:12
![image](https://github.com/Scirra/Construct-bugs/assets/26490771/a8ef2bda-891f-482f-9bd6-bf4aca972d95)
![image](https://github.com/Scirra/Construct-bugs/assets/26490771/47eaeba5-7385-404d-a007-32d9ae61796e)
![image](https://github.com/Scirra/Construct-bugs/assets/26490771/053fc137-e3e4-442a-b410-c8bc600f7406)
![image](https://github.com/Scirra/Construct-bugs/assets/26490771/6a1e4daf-7331-4e91-a8ff-25f92e20bf6f)

Yes, but it's no use, the bug won't reproduce.

**Comment by DiegoScirra** [comment] 2024-05-20 11:41
This seems similar to #8021, which I suspect has something to do with working with huge image files. I can't reproduce it on my side though, C3 struggles to load massive image files, but in the end it works.

I would suggest using smaller images.

Since there isn't more substantial information will close this.

**Closed by DiegoScirra** 2024-05-20 11:41 UTC
Labels: no repro
