### ISSUE TITLE
r350 - Adaptive Foreground and Adaptive Background icons doesn't work. The Icon is still displayed as a square in the circle

### ISSUE THREAD

**Issue by ArtemLanin** [Scirra/Construct-bugs#7260] opened 2023-07-28 10:28 UTC
## Problem description

It worked in previous versions of Construct 3 (a months ago) but now it doesn't work. The icon

## Attach a .c3p
[test_icon_bg_fg.zip](https://github.com/Scirra/Construct-bugs/files/12193362/test_icon_bg_fg.zip)

## Steps to reproduce

1. Create Adaptive Foreground and Adaptive Background icons
2. Build the Android project
3. Check the icon on your Android device

## Observed result

The Icon is displayed as a square in the circle
![2023-07-28_13-24-52](https://github.com/Scirra/Construct-bugs/assets/79050161/cbe5dbf2-337b-4756-b628-da3a6d16f5e6)

## Expected result

The icon should fill out all the space as it was before

## More details
Tested on Android 11 and 12 (Pixel XL and Pixel 3a)

**Affected browsers/platforms:** Android

**First affected release:** worked in r344.2 but broke in r350 -->

## System details

Android 11 and 12 (Pixel XL and Pixel 3a)

**Comment by fredriksthlm** [comment] 2023-07-28 19:44
This is a bug in Cordova 12. Will be fixed in 12.0.1

Workaround explained here: https://github.com/apache/cordova-android/issues/1616

**Comment by AshleyScirra** [comment] 2023-07-31 14:59
Duplicate of #7143. We will update when Cordova releases the fix for this.

**Closed by AshleyScirra** 2023-07-31 14:59 UTC
Labels: duplicate
