### ISSUE TITLE
Error when pressing edit button in timeline

### ISSUE THREAD

**Issue by gutsalovpavel** [Scirra/Construct-bugs#7542] opened 2023-11-13 03:34 UTC
Error report information
Type: unhandled exception
File: https://editor.construct.net/r366/main.js, line 1049, col 141
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Q.i (https://editor.construct.net/r366/main.js:1049:147) at d.qL (https://editor.construct.net/r366/projectResources.js:1051:94) at Es.KZb.KPa (https://editor.construct.net/r366/main.js:2603:200) at Array.oHb (https://editor.construct.net/r366/main.js:2602:118) at window.Akb.dispatchEvent (https://editor.construct.net/r366/main.js:1257:42) at window.Akb.Nk (https://editor.construct.net/r366/main.js:2956:422) at d.KU (https://editor.construct.net/r366/projectResources.js:1043:300) at u1.sLc (https://editor.construct.net/r366/components/bars/timelineBar/timelineBar.js:69:66) at Xq.g.J.kk.Ska.azb (https://editor.construct.net/r366/components/bars/timelineBar/timelineBar.js:53:443) at Zh (https://editor.construct.net/r366/main.js:396:253)
Construct version: r366
URL: https://editor.construct.net/r366/
Date: Mon Nov 13 2023 08:33:02 GMT+0500 (Узбекистан, стандартное время)
Uptime: 85.6 s

Platform information
Product: Construct 3 r366 (beta)
Browser: Chrome 119.0.6045.107
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Laptop GPU (0x000028E0) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

**Comment by WilsonPercival** [comment] 2023-11-13 04:16
@gutsalovpavel Could you please write the steps to reproduce the problem?

**Comment by gutsalovpavel** [comment] 2023-11-13 06:15
> @gutsalovpavel Could you please write the steps to reproduce the problem?

sadly, I don't know why it is happening, on the fresh project everything is working. But in my current one, even when I create a new timeline I got the error when pressing on the edit or on the play buttons

**Comment by WilsonPercival** [comment] 2023-11-13 06:30
> > @gutsalovpavel Could you please write the steps to reproduce the problem?
> 
> sadly, I don't know why it is happening, on the fresh project everything is working. But in my current one, even when I create a new timeline I got the error when pressing on the edit or on the play buttons

@gutsalovpavel I understand. Not all crashes can be reproduced in a new project. Can you share your project that is crashing? Otherwise, it will be impossible to fix the problem.

**Comment by gutsalovpavel** [comment] 2023-11-13 06:54
I can't share with the project. NDA. 
Ok, lets wait other people with this error

**Comment by WilsonPercival** [comment] 2023-11-13 07:11
> I can't share with the project. NDA. Ok, lets wait other people with this error

@gutsalovpavel You can remove all content from a project, including events.

**Comment by gutsalovpavel** [comment] 2023-11-13 07:49
after removing content the error gone

**Comment by WilsonPercival** [comment] 2023-11-13 08:12
> after removing content the error gone

@gutsalovpavel There was no need to remove object types. Only animations and animation frames needed to be removed.

**Comment by gutsalovpavel** [comment] 2023-11-13 08:30
> > after removing content the error gone
> 
> @gutsalovpavel There was no need to remove object types. Only animations and animation frames needed to be removed.
It is a big game with a lot of resources and a lot of animations in objects, particles, tilemaps, etc. I tried to remove objects by parts, and at some point, I was able to remove the bag, but I deleted 75% of the objects. Looks like an error from some type of resource, may be tilemaps, don't know, very hard to check, because each time I got to save and reload the game, the error disappear after you delete the bad resource type than restart the game

**Comment by WilsonPercival** [comment] 2023-11-13 08:38
> > > after removing content the error gone
> > 
> > 
> > @gutsalovpavel There was no need to remove object types. Only animations and animation frames needed to be removed.
> 
> It is a big game with a lot of resources and a lot of animations in objects, particles, tilemaps, etc. I tried to remove objects by parts, and at some point, I was able to remove the bug, but I deleted 75% of the objects. Looks like an error from some type of resource, maybe tilemaps, don't know, very hard to check, because each time I got to save and reload the game, the error disappear after I delete the bad resource type then restart the game

@gutsalovpavel You can post your project to my discord if you don't want to mess with it. Your report will most likely be closed because you did not provide a project file. You could try emailing the project file to Ashley, but with his workload I don't think he would want to spend time decomposing the project. I'm also not sure if anyone else can provide steps to reproduce this crash.

**Comment by AshleyScirra** [comment] 2023-11-13 10:37
I've assigned @DiegoScirra to look at the crash message, but as per the bug report guidelines, often such reports are impossible to fix as we need more information to be able to help, so this may be closed without a fix. I would advise finding a way to reproduce the problem in a project you're willing to share, which will make it 10x more likely it can be fixed, and the bug report guidelines also have advice on how to do that.

**Comment by AshleyScirra** [comment] 2023-11-13 15:17
As there is no repro and the evidence is that it is caused by a third-party addon, closing. If you identify which third-party addon is causing the problem, please report it to the addon developer.

**Closed by AshleyScirra** 2023-11-13 15:17 UTC
Labels: no repro, external
