### ISSUE TITLE
Savegame freeze the game!  (still in both 368-2 and even new r372-2)

### ISSUE THREAD

**Issue by NukeThemAllGame** [Scirra/Construct-bugs#7697] opened 2023-12-27 15:02 UTC
## i use 368-2 or even new r372-2 - when calling to save game, the game freezes! 

-> System: Save game to slot "quicksave"

It used to work in the past with same code on older versions. Please kindly fix

## Attach a .c3p    The project is here

https://drive.google.com/file/d/1wMne7blJtnGml0nFi0MqeoWy9LXfCZu4/view?usp=sharing
Easy isometric addon is here for you https://drive.google.com/file/d/1Js0QOVepIG4MJXNXQGYJ-HVsnFk_jXxw/view?usp=sharing

## Steps to reproduce

1.  Toggle enabled group called "Save/Load" in Sh_level1 event sheet. It was disabled because it causes freeze.
2.  Start preview with layouts for example "Sandbox".
3. The game will freeze instantly on start.

Alternatively you can create a simple 1 line code to test and even simple call of save action on keyboard 8  will cause the freeze 
even this single line if you try will cause freeze:
+ Keyboard: On 8 pressed -> System: Save game to slot "quicksave"

it used to work in the past correctly without freeze

## Observed result

Game freezes completely

it should save correctly. it used to work in the past correctly without freeze

## More details

I tried in both chrome and edge in r368-2/ and same problem in new r372-2

**Affected browsers/platforms:** 

I tried in both chrome and edge in r368-2/ and same problem in new r372-2. It impossible to say when it appeared first because I did not have Save feature in my game before. However if I load very old build from autumn the save works fine with same code.

## System details

<details><summary>View details</summary>

As the game freezes, no error appears in the game itself, it just freezes. However if I go to Dev tools, I see following:

solState.js:3  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'GetUID')
    at solState.js:3:40
    at Array.map (<anonymous>)
    at SolState._SaveToJson (solState.js:3:25)
    at ScheduledWait._SaveToJson (scheduledWait.js:10:442)
    at eventSheetManager.js:29:301
    at Array.map (<anonymous>)
    at EventSheetManager._SaveScheduledWaitsToJson (eventSheetManager.js:29:292)
    at EventSheetManager._SaveToJson (eventSheetManager.js:26:238)
    at C3Runtime._SaveToJsonString (runtime.js:115:476)
    at C3Runtime._DoSaveToSlot (runtime.js:113:149)

</details>

**Comment by WilsonPercival** [comment] 2023-12-27 16:56
@NukeThemAllGame I can't open your project. Please remove any third party addons in accordance with reporting guidelines.

<img width="412" alt="obser" src="https://github.com/Scirra/Construct-bugs/assets/91274932/f5fc16a5-0ea9-4b78-a521-a0278b4b72f9">

**Comment by NukeThemAllGame** [comment] 2023-12-27 17:04
Hello, it's not possible to remove it as it's used in the game but I attach here for you this addon:
https://drive.google.com/file/d/1Js0QOVepIG4MJXNXQGYJ-HVsnFk_jXxw/view?usp=sharing

**Comment by DinoSystem** [comment] 2023-12-27 17:50
Savegame freeze also happens to me very rarely, Ican't post a report as i cant reproduce it, and my game is huge.

**Comment by WilsonPercival** [comment] 2023-12-27 19:51
Minimum project: 
[issue7697.zip](https://github.com/Scirra/Construct-bugs/files/13780888/issue7697.zip)

Steps to reproduce:
1. Open and run the project.

Observed result: the game freezes and an error appears in the console.

<img width="940" alt="observed" src="https://github.com/Scirra/Construct-bugs/assets/91274932/1a11af53-89b2-4e30-9428-b8234128b307">

@NukeThemAllGame Can you tell me the version that didn't have this bug?

**Comment by WilsonPercival** [comment] 2023-12-27 19:53
> Savegame freeze also happens to me very rarely, Ican't post a report as i cant reproduce it, and my game is huge.
> 
> BUT i have a saved game where it always happens on a specific time, @AshleyScirra let me know if you want to investigate, as isaid my project is huge and it would be an unconventional bug hunt for you (but I think you would appreciate to check on my game :3)

@DinoSystem I think you can entrust this to me. I love exploring mistakes.

**Comment by NukeThemAllGame** [comment] 2023-12-27 20:06
> [WilsonPercival](/WilsonPercival)

Hi again WilsonPercival. Sorry I am new to bug reporting here. Are you part of construct 3 tech team or you are user like me submitting bugs?  Like i wrote in bug report, I tried in both chrome and edge in r368-2/ and same problem in new r372-2. It impossible to say when it appeared first because I did not have Save feature in my game before. However if I load very old build from autumn the save works fine with same code. It's would be good if tech team can look what's happening behind the "scenes" when the freeze happens to resolve it as it's a major show-stopper.

**Comment by WilsonPercival** [comment] 2023-12-27 20:09
> > [WilsonPercival](/WilsonPercival)
> 
> Hi again WilsonPercival. Sorry I am new to bug reporting here. Are you part of construct 3 tech team or you are user like me submitting bugs? Like i wrote in bug report, I tried in both chrome and edge in r368-2/ and same problem in new r372-2. It impossible to say when it appeared first because I did not have Save feature in my game before. However if I load very old build from autumn the save works fine with same code. It's would be good if tech team can look what's happening behind the "scenes" when the freeze happens to resolve it as it's a major show-stopper.

@NukeThemAllGame I am the same user as you.

**Comment by NukeThemAllGame** [comment] 2023-12-27 20:12
> @NukeThemAllGame I am the same user as you.

Thank you. I hope you can suggest solution or we can wait @AshleyScirra after the holidays!

Cheers!

**Comment by DinoSystem** [comment] 2023-12-27 20:37
Poor Wilson always mistaken for a Scirra team dev xD 

Ashley should actually hire him tbh.

**Comment by TmesisStudio** [comment] 2023-12-29 19:44
I have the same problem too. Don't know which version broken the savegame because I was working with a really old C3 version since a month ago.

**Comment by AshleyScirra** [comment] 2024-01-03 16:54
As per the bug report guidelines, large projects are infeasible to debug, and we require projects that do not use third-party addons to eliminate them as a possible cause (it is entirely possible a broken third-party addon could corrupt Construct's internal state and cause a problem like this, and so we need to rule that out). However I was able to fix the bug in the minimal project provided by @WilsonPercival. The problem in that project only occurs if you combine using 'For each' with zero instances, 'Wait' actions, and savegames. It seems plausible this is the cause of the issue in the larger project (and potentially other projects). That specific problem should be fixed for the next beta. It will probably only fix projects that have the exact error message shown in @WilsonPercival's screenshot - if your project has a different error message, it is probably a different issue, and will need to be filed as a separate issue with a minimal project as well. Unfortunately it's infeasible for us to debug large projects and projects using third-party addons, so the only way to make progress is to provide a minimal project demonstrating the issue as per our bug report guidelines, which do also include advice on how to reduce a large project to a minimal repro. If you can provide a minimal repro we can often fix the problem promptly; if you provide a full project it's probably going to be impossible to make progress.

**Closed by AshleyScirra** 2024-01-03 16:54 UTC

**Comment by DinoSystem** [comment] 2024-01-04 01:22
@AshleyScirra Thank you for fixing this! I got the exact same error in the log, so i assume it'll get fixed. Not a major issue since happens occasionally, but i was getting quite paranoid because of it.

**Comment by AshleyScirra** [comment] 2024-01-04 17:16
FWIW this fix is in r373.2 so you should be able to verify if it is working there.

**Comment by DinoSystem** [comment] 2024-01-04 17:35
> FWIW this fix is in r373.2 so you should be able to verify if it is working there.

I confirm it is fixed 😍
