### ISSUE TITLE
Crash on Undo in Image Editor on everything but Sprite.

### ISSUE THREAD

**Issue by FunkyK-oval** [Scirra/Construct-bugs#6742] opened 2023-03-10 14:49 UTC
## Problem description

Construct 3 crashes on Undo action (unhandled rejection) in Image Editor for every object **except** Sprite.

## Attach a .c3p

[C3_Beta333_UndoBug_FunkyKoval.zip](https://github.com/Scirra/Construct-bugs/files/10943080/C3_Beta333_UndoBug_FunkyKoval.zip)

## Steps to reproduce

1. Open example
2. Select Particles object and go into Image Editor
3. Doodle with the brush
4. Undo

## Observed result

Construct 3 crash.

## Expected result

An Undo operation

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Beta 333

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'kk') @ TypeError: Cannot read properties of null (reading 'kk') at Zx.g.K.MSc.Jg (https://editor.construct.net/r333/projectResources.js:2514:418) at Array.XY (https://editor.construct.net/r333/projectResources.js:2511:116) at Dx.g.K.Qb.dispatchEvent (https://editor.construct.net/r333/main.js:1234:42) at https://editor.construct.net/r333/projectResources.js:2552:416
Stack: TypeError: Cannot read properties of null (reading 'kk') at Zx.g.K.MSc.Jg (https://editor.construct.net/r333/projectResources.js:2514:418) at Array.XY (https://editor.construct.net/r333/projectResources.js:2511:116) at Dx.g.K.Qb.dispatchEvent (https://editor.construct.net/r333/main.js:1234:42) at https://editor.construct.net/r333/projectResources.js:2552:416
Construct version: r333
URL: https://editor.construct.net/r333/
Date: Fri Mar 10 2023 22:47:38 GMT+0800 (Singapore Standard Time)
Uptime: 210.6 s

Platform information
Product: Construct 3 r333 (beta)
Browser: Chrome 110.0.5481.178
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by AshleyScirra** [comment] 2023-03-10 14:55
Looks like a duplicate of #6730, should already be fixed for the next beta.

**Closed by AshleyScirra** 2023-03-10 14:55 UTC
Labels: duplicate
