### ISSUE TITLE
dark theme checkbox regressed in r287

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7113] opened 2023-06-13 15:08 UTC
## Problem description

In r287 the dark theme (probably the light theme as well) stopped using their nicely styled check boxes in favor of the browser default ones, I cannot find it in the patch notes, so I assume this happened by accident, but there is https://github.com/Scirra/Construct-bugs/issues/5509 which might have caused this.
## Attach a .c3p
not relevant

## Steps to reproduce

1. look at the properties bar check boxes in release r287

## Observed result
 ![image](https://github.com/Scirra/Construct-bugs/assets/89512047/d0440279-5c08-4afe-a12c-264397fc4b8f)

## Expected result
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/30768172-3e36-4921-86be-51f7e280df48)

## More details
#3360 I found this bug report, which is not directly connected but might be relevant in case you are considering fixing this.
As a side note, the layers bar still used the styled checkbox until r337, there it only regressed after fixing this #5303. So these seem to not use the same css?

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2023-06-15 13:45
This was indeed a regression caused by #5509. It should be fixed in the next beta.

**Closed by AshleyScirra** 2023-06-15 13:45 UTC
Labels: theme

**Comment by CrackHub** [comment] 2023-11-11 20:53
This is broken again. I don't wanna create new issue. I tried latest beta with chrome and firefox.
