### ISSUE TITLE
Audio fade with tag bug

### ISSUE THREAD

**Issue by XtremeToaster** [Scirra/Construct-bugs#7592] opened 2023-11-30 02:05 UTC
## Problem description

In my project, the music will continue on the start of layout if no music is playing.

When an action causes music with this tag to fade out, It has no volume when it restarts.

## Attach a .c3p
[Audio Bug.zip](https://github.com/Scirra/Construct-bugs/files/13509359/Audio.Bug.zip)

## Steps to reproduce

1. Press F to fade audio tagged "Music" and wait 2 seconds for the music to stop
2. Press an arrow key to fall off the ground platform and restart the layout

## Observed result

The gorgeous music I made just to show off the bug is playing with no volume when restarted

## Expected result

The music should restart and begin playing at its default "0" volume when the layout restarts

## More details

I'm using Firefox on a Windows 10 PC.

I have tried several things on the start of layout like asking the volume fade back in, setting the volume of the music to 0, unmuting it  with no luck.

**Affected browsers/platforms:** 

Firefox

**First affected release:** 

I found this in r368

## System details

Platform information

Product: Construct 3 r368.2 (stable)
Browser: Firefox 119.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
Language setting: en-US
Local storage

Storage quota (approx): 10 gb
Storage usage (approx): 77 mb (0.8%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    WEBGL_provoking_vertex

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

**Comment by WilsonPercival** [comment] 2023-11-30 06:35
@XtremeToaster You need to attach the original project file, not the exported project.

**Comment by WilsonPercival** [comment] 2023-11-30 06:55
Duplicate https://github.com/Scirra/Construct-bugs/issues/7480

**Comment by AshleyScirra** [comment] 2023-11-30 11:21
I believe this is a duplicate of #7480 and that it is a Firefox bug, which I filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1860581

**Closed by AshleyScirra** 2023-11-30 11:21 UTC
Labels: duplicate
