### ISSUE TITLE
"Menu" context menu icons size not matching text size

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6731] opened 2023-03-08 18:41 UTC
## Problem description
The "Menu" context menu icons seem overly large in comparison to the size of the text, making it look out of place.

## Steps to reproduce

1. click the menu button

## Observed result
icon scale doesn't match text scale
![scale1](https://user-images.githubusercontent.com/89512047/223804467-59a7dcd0-b2af-4342-87ef-58dc9cb332f2.png)

## Expected result
Icon scale in line with text scale

![expectedScale](https://user-images.githubusercontent.com/89512047/223804485-03019604-1078-44d2-a199-345feb5b3f63.png)

## More details
Imo the scales should be brought closer together, Idealy by decreasing the icon size. 
Otherwise the icons size could be scaled down and the text scaled up slightly if the buttons should stay a similar size.
(doesn't seem theme specific)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment] 2023-03-08 18:45
![theme](https://user-images.githubusercontent.com/89512047/223805888-2945a958-6fa2-4fa0-b2d2-d4abf977c6b7.png)

![example3](https://user-images.githubusercontent.com/89512047/223806156-80cd8485-e60d-4034-95db-07cdad3e7931.png)

3rd party theme developers override this as they also agree that it looks off.

**Comment by AshleyScirra** [comment] 2023-03-09 12:46
This looks like a regression in r318. The dark theme used to use small menu icons, but now uses large menu icons matching the default theme. I think it comes down to the fix for #6203: themes can't actually reliably override the icon size, and so by fixing that, it meant the theme can no longer override the main menu icon sizes.

I think we will need a separate theming system for the main menu to allow overriding the icon menu sizes in that menu only.

**Comment by AshleyScirra** [comment] 2023-03-10 17:34
This should be fixed, but in order to reduce risky changes in the run-up to the next stable release, the fix will be in the next release cycle (first beta after next stable release).

**Closed by AshleyScirra** 2023-03-10 17:34 UTC
Labels: theme
