### ISSUE TITLE
The  Editor icon will be misaligned different font.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8001] opened 2024-05-09 06:19 UTC
## Problem description

It often occurs intermittently, but can be resolved by restarting C3. This will be happen in non-English pages, I guess is that the icons are cropped incorrectly due to different language font. 

display resolution is 1920*1080 monitor. Use C3 PWA in full-screen window. The system display scale and browser scale are both 100%, so it is not caused by forced scaling.

There are two places where misalignment occurs:
1. call function action icon (but no screenshot)
2. the Layer bar

![644974c083c4b0b96d62e1ec9b98c3bf](https://github.com/Scirra/Construct-bugs/assets/45864744/f613d6fc-8739-49a6-b48f-0a76df56d077)

## Steps to reproduce

Can't reproduce, but it happens often

## Observed result

![0e6e77f2fd6388eae8016b63ac03348b](https://github.com/Scirra/Construct-bugs/assets/45864744/343e4c50-4859-4882-819a-d6b9d806d17d)

## Expected result

![image](https://github.com/Scirra/Construct-bugs/assets/45864744/0e0c45d7-8f4b-49e3-aa16-c696bdb52a18)

## More details

**Affected browsers/platforms:** Chrome, PWA 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r388.2 (stable)
Browser: Chrome 124.0.6367.119
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: zh-CN

Local storage
Storage quota (approx): 93 gb
Storage usage (approx): 38 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 730 (0x00004692) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment] 2024-05-10 14:02
I've never seen this despite using Construct constantly, the icon system has nothing to do with the language system, without steps to reproduce it's infeasible to fix, and it looks like it might be something like a graphics driver bug anyway which is beyond our control, so closing.

**Closed by AshleyScirra** 2024-05-10 14:02 UTC
Labels: can't reproduce
