### ISSUE TITLE
Html Element Z Order Issue

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-bugs#7674] opened 2023-12-18 14:24 UTC
## Problem description

Before r369, when an html element (a menu for example) was created at runtime, it was drawn above all other html elements. After r369, it is created behind the other html elements.

I edited "Html Menu" example, in order to demonstrate the problem.

## Attach a .c3p

[HtmlLayerOrder.zip](https://github.com/Scirra/Construct-bugs/files/13703751/HtmlLayerOrder.zip)

## Steps to reproduce

1. Run project
2. Right Click on the piggy to show the menu

## Observed result

![r369](https://github.com/Scirra/Construct-bugs/assets/53188782/f3835a41-072e-4aac-ad59-528fc1d7e605)

## Expected result

![r368](https://github.com/Scirra/Construct-bugs/assets/53188782/4593216d-ffaa-479e-a085-5d1898628af2)

## More details

Problem is solved if you mark as an html layer, every layer that contains an html element or if you create the new html element on the same layer as other html elements. If this is the right way to go from now on, then I should edit the layers in my projects in order to show the menus correctly.

**Affected browsers/platforms:** Chrome, Windows

**First affected release:** r369

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r371 (beta)
Browser: Chrome 120.0.6099.109
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 476 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M (0x00000A68) Direct3D11 vs_4_1 ps_4_1, D3D11)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2024-01-05 15:41
This minimal repro does not reproduce the problem - the new element is created on top of the existing one: 
[issue7674.zip](https://github.com/Scirra/Construct-bugs/files/13843891/issue7674.zip)
So there must be something more to this.

**Comment by AshleyScirra** [comment] 2024-01-05 15:44
This seems to reproduce it - the key is that the new element is created on a layer above the existing element: 
[issue7674-b.zip](https://github.com/Scirra/Construct-bugs/files/13843921/issue7674-b.zip)

**Comment by AshleyScirra** [comment] 2024-01-05 16:07
This should be fixed in the next beta. Looks like a regression that came from introducing HTML layers in r369.

**Closed by AshleyScirra** 2024-01-05 16:07 UTC
