### ISSUE TITLE
inserting new sprites doesn't work properly while a search is active

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#8327] opened 2024-11-20 07:51 UTC
## Problem description

I often try to insert a new sprite but then it feels like nothing happened, and I become confused.

No click to place object. No Animation Editor pops up.

I now realize it happens when the project search bar had text in it. 

![image](https://github.com/user-attachments/assets/ec62b627-0364-483f-ad89-c9e75ce32e62)

Once you do clear the search, it does actually still make a blank sprite, but there are 0 instances of it placed in the layout:

![image](https://github.com/user-attachments/assets/59a16e8b-f793-47ff-b94a-b6ff72a6f476)

I think maybe it could happen to other objects too, not just sprites.

## Attach a .c3p

[insertBug.zip](https://github.com/user-attachments/files/17826928/insertBug.zip)

## Steps to reproduce

1. Type "sprite" in the project search bar
2. Insert new sprite in the layout

## Observed result

Nothing.

![image](https://github.com/user-attachments/assets/65214f42-0294-4fd5-86c9-9b19f16a160f)

## Expected result

Should allow you to click to place it in the layout, and then it should show the image editor.

![image](https://github.com/user-attachments/assets/f6bfd6f6-76e8-4ba8-80e6-dfa7782b4e89)

## More details

Chrome

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2024-11-21 11:49
At first I couldn't reproduce this but it turns out it works if you're too quick. The steps to reproduce reliably are:

1. Type "sprite" in search bar
2. Double-click to add new object
3. Double-click Sprite
4. Dialog closes and mouse changes to a cross-hair
5. Wait a moment without clicking

Observed result: after a moment the mouse reverts to the normal cursor. It looks like this happens when the Project Bar updates to include a new search result for the newly-added Sprite. As the cross-hair place cursor has been cancelled then no initial instance is placed.

Expected result: next click to reliably insert a new instance (which opens Animations Editor)

**Comment by AshleyScirra** [comment] 2024-11-21 12:53
Should be fixed in the next beta.

**Closed by AshleyScirra** 2024-11-21 12:53 UTC
