### ISSUE TITLE
Invisible Action Icon for Custom Actions of non-Family ObjectTypes

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#6770] opened 2023-03-14 15:39 UTC
## Problem description

There is an issue with the way icon for actions related to a non-Family Custom Action are displayed  : **the objectType icon is invisible**, only the little lego at the bottom right is visible. (It works for Family but not for regular ObjectType)

## Attach a .c3p

[Bug_CustomAction_DisplayIcon.zip](https://github.com/Scirra/Construct-bugs/files/10970569/Bug_CustomAction_DisplayIcon.zip)

## Observed result

![image](https://user-images.githubusercontent.com/99751718/225054301-0c8d792f-357b-4188-a45b-bee01fe5aaad.png)

(i know those are not valid events, it's just to illustrate the issue)

## Expected result

The icon in the action related to the "Sprite : Action2" should display both a small lego and the actual Sprite icon behind.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2023-03-14 17:33
It looks OK to me when I open the provided project. Can you provide the steps to reproduce the problem?

**Comment by OverboyDev** [comment] 2023-03-14 18:18
You always say the instructions should start once the project is open : so here are the steps that i should have written according to what you're usually asking for bug reports  :
1. Open the project. (endà

However you're right it seems like the issue doesn't happen anymore once you close and reopen the project.
So if you want to reproduce it you need to do create a Custom Action yourself as any example c3p i could provide to you won't have the issue (as reopening the project fixes the issue) :

1. Create a Custom Action for a non-family ObjectType
2. Add a action that is calling this Custom Action.

Just wanna say my experience with reporting issues is very not pleasant lately due to contradicting explanations on why a bug report is wrong and what is considered as an actual issue and what is not. It's purely arbitrary and inconsistent. Same for the other issue I reported and you immediatly closed today. You even proved yourself the way Custom Actions is displayed is inconsistent with Regular Actions, while the fact Custom Actions and Regular Actions should be displayed the same way was supposedly the reason why they were inconsistent with Functions. (which doesn't makes sense as Custom Actions ARE Functions)

I spend a lot of work time to provide you detailed feedbacks following your guidelines and sometimes even more (mockups/screenshots) etc... It would be nice if spending doing this wouldn't end up ruining my day every time because of such frustrating reactions. C3 is the only tool i'm following where it happens so often. Usually software devs like free feedbacks and seem thankful.

**Comment by AshleyScirra** [comment] 2023-03-15 11:09
The point is to provide steps that reproduce the problem. Usually this can be done most easily by providing a sample project. If that approach does not reproduce the problem though then the steps need to be written differently.

We have been extremely busy lately. I am afraid that both due to an exceptional number of issue reports lately, in addition to a great deal of other work that we have to do, that we are so pushed for time that we simply cannot always afford to do detailed investigations of reports. This is the only way it is feasible for us to be able to stay on top of the extraordinary amount of work that is coming in. I apologise if this means some things are skipped or missed but there are just not enough hours in the day at the moment.

**Comment by AshleyScirra** [comment] 2023-03-15 12:15
This turned out to be pretty complicated but I think I have it fixed. In order to avoid potentially risky changes in the run-up to a stable release, and since the issue is only cosmetic, the fix will be in the next release cycle (first beta release after the next stable release).

**Closed by AshleyScirra** 2023-03-15 12:15 UTC

**Comment by AshleyScirra** [comment] 2023-03-16 11:51
Decided to bring this one forward to the next beta after all.
