### ISSUE TITLE
Sprite Font line height shifts text upwards

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-bugs#7729] opened 2024-01-10 00:43 UTC
## Problem description

Previously, the line height value increased the leading for a Sprite Font object. Now it's affecting the baseline (it shouldn't).

## Attach a .c3p

New project is easiest.

## Steps to reproduce

1. Add a sprite font object to the layout.
2. Exit the animation editor. 
3. Enter 20 in to the Line Height field.

## Observed result

The word "Text" is raised well above the bounding box.

![image](https://github.com/Scirra/Construct-bugs/assets/63005234/6b1ea48e-0d09-4d7a-8b8e-8c5bbd838ec9)

## Expected result

The word "Text" should stay on its baseline.

![image](https://github.com/Scirra/Construct-bugs/assets/63005234/99811d23-9b8e-4011-80e3-2c06b13dd571)

## More details

**Affected browsers/platforms:** Version 120.0.6099.216 (Official Build) (x86_64)

**First affected release:** This works correctly in r360, fails in r374

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2024-01-17 16:56
Looks like a regression in r369. Should be fixed in the next beta.

**Closed by AshleyScirra** 2024-01-17 16:56 UTC

**Comment by brushfe** [comment] 2024-01-17 17:02
Amazing, thanks again!
