### ISSUE TITLE
Problem when creating a new sprite

### ISSUE THREAD

**Issue by memetugabum** [Scirra/Construct-bugs#7826] opened 2024-02-14 05:45 UTC
After the update, I started having problems. I can’t create a new sprite, and also a Tile backdrop
Error:

Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. @ Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. at Function.C.IO (https://editor.construct.net/r379/main.js:1099:124) at d.fS (https://editor.construct.net/r379/projectResources.js:811:200) at d.fS (https://editor.construct.net/r379/projectResources.js:725:185) at async https://editor.construct.net/r379/projectResources.js:2944:169 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Stack: Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. at Function.C.IO (https://editor.construct.net/r379/main.js:1099:124) at d.fS (https://editor.construct.net/r379/projectResources.js:811:200) at d.fS (https://editor.construct.net/r379/projectResources.js:725:185) at async https://editor.construct.net/r379/projectResources.js:2944:169 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Construct version: r379
URL: https://editor.construct.net/
Date: Wed Feb 14 2024 12:44:02 GMT+0700 (Nobosibirsk, standart time)
Uptime: 9.3 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 100.0.4896.75
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) c3/1.4.0 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36
Language setting: ru-RU

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_video_texture, WEBGL_webcodecs_video_frame, OVR_multiview2

**Comment by AshleyScirra** [comment] 2024-02-14 10:33
Looks like a duplicate of #7824. Please note:

> Browser: Chrome 100.0.4896.75

The latest Chrome version is v121. Please update as presumably using out-of-date software is the problem, as it doesn't reproduce for me in Chrome v121.

**Closed by AshleyScirra** 2024-02-14 10:33 UTC

**Comment by AshleyScirra** [comment] 2024-02-14 10:40
...and also that using Electron with Construct is not supported. There is no official distribution of Construct that uses Electron, and we will not provide support to anybody doing so.
