### ISSUE TITLE
C3 Crushes Randomly

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-bugs#7445] opened 2023-10-06 01:24 UTC
It's been many weeks now since C3 started to crush and it's getting every time worse, today it happened around 8+ times, some while hit "save" and some while I hit "Export For web HTML5". I have been working on this project for 3 years and I'm worried that is going to corrupt my files as a few times while saving C3 Crushed and the file was corrupt with size = 0.
I have been using C3 since it came out and I never had any problems with Crushing, this just started happening recently.

Not sure if this is related but casualty started the crushing after I had been adding the final assets which went from 50 MB to 250 MB so maybe it's the size of the project? As I have seen in the past other users with similar issues, which had big-size projects.

![Image 004](https://github.com/Scirra/Construct-bugs/assets/41597700/d98e9cef-a59f-4ce2-adbe-5f5eb181aff9)

![Image 006](https://github.com/Scirra/Construct-bugs/assets/41597700/de63e942-db1a-4e7d-be76-287f1a2a1044)
![Image 005](https://github.com/Scirra/Construct-bugs/assets/41597700/b74f8ae2-778d-41d5-90e5-7ce13c7d3b3e)

## Attach a .c3p

I cannot share it, as is happening with my main project.

## Steps to reproduce

It happens random

## Observed result

Crush and the editor became red which shows the error log and if you want to save. 

## Expected result

That it doesn't crush

## More details

F12 Console log is pointing here:

}
;
CCG.eo = function(d) {
    d.tab = !1;
    CCG.co(d, "livepreviewstop")
}
;
CCG.Hpa = async function(d, e) {
    CCG.M.T(e, self.vb);
    if (!(!e || 0 < d.GF || 0 < d.Dw || CCG.Pe()))
        try {
            await CCG.M.Ri.NAc(e)
        } catch (f) {
            console.error("Error exporting: ", f),
            f && "minify-failed-load" === f.type ? CCG.M.g.O.P("OK").R((0,
            CCG.pn)("ui.errors.failed-to-load-minifier")) : f && "minify-error" === f.type ? CCG.M.g.O.P("MinifyError").R(f.log) : CCG.M.g.O.P("OK").R((0,
            CCG.pn)("ui.errors.failed-to-export"))
        }
}
;
CCG.co = function(d, e) {
    CCG.M.l(e);
    e = new CCG.M.Event(e);
    e.app = d;
    d.dispatchEvent(e)
}

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

r350 

Latest stable Crushes too

## System details

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct version: r350
URL: https://editor.construct.net/r350/
Date: Fri Oct 06 2023 00:29:47 GMT+0100 (British Summer Time)
Uptime: 170.6 s

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 117.0.5938.150
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment] 2023-10-06 10:53
@Tarek200 I think without a project file and steps to reproduce it will be difficult to do anything.

**Comment by Tarek200** [comment] 2023-10-06 15:20
> [WilsonPercival](/WilsonPercival)

Yes @WilsonPercival I understand it is a difficult bug because there are no steps to reproduce it as it happens randomly and I cannot share my project. However, the console log is pointing to a "minify-error" so I was hoping that they may be able to spot if there are any errors with the new minify that they added not long ago.

console.error("Error exporting: ", f),
f && "minify-failed-load" === f.type ? CCG.M.g.O.P("OK").R((0,
CCG.pn)("ui.errors.failed-to-load-minifier")) : f && "minify-error" 


I'm trying to see if I can replicate it with other projects that I could share.

**Comment by nerdError** [comment] 2023-10-11 05:54
Have you tried to reproduce it with all chrome extensions disabled?

**Comment by AshleyScirra** [comment] 2023-10-11 11:33
I'm afraid it's impossible to do anything without more details. Unfortunately the provided information does not point to any obvious cause. The only way to diagnose this would be if we can reproduce it ourselves.

Disabling any browser extensions would be a good idea in case something is interfering.

The error "failed to fetch" suggests a network request. It may be possible to identify which request this is in the Network tab of dev tools. However IIRC that only logs requests made if you open dev tools before the problem happens.

It also looks like you're still using r350 and normally issue reports require that you use the latest version. If the issue relates to the old minifier, note that has now been completely replaced, so if that was the cause then it should be fixed as of the latest releases.

**Closed by AshleyScirra** 2023-10-11 11:33 UTC
Labels: no repro

**Comment by Tarek200** [comment] 2023-10-12 19:44
Thanks for the Tips

-I disabled all the plugins
-I updated C3 to the latest beta https://editor.construct.net/r362/
-I been watching the Network but I couldnt see anything wrong, not sure what to look for though, all seems ok.

The Crash is constantly, even with a new empty project it crashes when I try to export it with NW.js.

**Here is a video:** 

https://github.com/Scirra/Construct-bugs/assets/41597700/4400c8e7-ba82-4875-91b5-32c8f0fa9929


**Error Log:**
[Notes.txt](https://github.com/Scirra/Construct-bugs/files/12886515/Notes.txt)

Not sure what else to I could do, any more ideas?

One thing I dont understand is why would it crash just on normal tabs and not on incognito mode?

**Comment by WilsonPercival** [comment] 2023-10-12 19:56
> Thanks for the Tips
> 
> -I disabled all the plugins -I updated C3 to the latest beta https://editor.construct.net/r362/ -I been watching the Network but I couldnt see anything wrong, not sure what to look for though, all seems ok.
> 
> The Crash is constantly, even with a new empty project it crashes when I try to export it with NW.js.
> 
> **Here is a video:**
> 
>  Video.mp4 
> **Error Log:** [Notes.txt](https://github.com/Scirra/Construct-bugs/files/12886515/Notes.txt)
> 
> Not sure what else to I could do, any more ideas?
> 
> One thing I dont understand is why would it crash just on normal tabs and not on incognito mode?

@Tarek200 I can guess:

1. You haven't disabled all Chrome extensions.
2. The C3 editor did not load completely. Try clearing the cache and waiting for the C3 editor to load again (when the download is complete you will see a notification in the lower left corner). Immediately after this, create a new project and run preview. The C3 editor is now available for offline use.

**Comment by Tarek200** [comment] 2023-10-12 22:03
> @Tarek200 I can guess:
> 
> 1. You haven't disabled all Chrome extensions.
> 2. The C3 editor did not load completely. Try clearing the cache and waiting for the C3 editor to load again (when the download is complete you will see a notification in the lower left corner). Immediately after this, create a new project and run preview. The C3 editor is now available for offline use.

@WilsonPercival 
As I explained above all the Plugins were disabled they are easy to check.
Also, to make sure that there is no problem with any extension or any other thing I Uninstalled Chrome and reinstalled it again fresh, there are no extensions at all as everything has been deleted but the editor still keeps crashing.


![Image 002](https://github.com/Scirra/Construct-bugs/assets/41597700/c0ac2dbf-8890-4376-a17a-ca12ecc575a2)
![Image 001](https://github.com/Scirra/Construct-bugs/assets/41597700/49cead19-b933-4822-afaf-7f5098036ebc)

 @AshleyScirra  This is a new Chrome freshly installed without any extensions, what do you recommend at this point? Could it be C3 Bug?

**Comment by AshleyScirra** [comment] 2023-10-16 12:52
I'm afraid I have no idea: we usually can't tell what's going wrong from just videos or error logs, which is why the steps to reproduce an issue are required, so we can debug the problem ourselves.

> One thing I dont understand is why would it crash just on normal tabs and not on incognito mode?

Usually this means the standard Chrome has browser extensions, or possibly a bad cache, that are not used in incognito mode. All I can suggest is try fully removing all browser extensions, and then clear the browser cache, and then try again. Failing that, try a different browser.
