### ISSUE TITLE
R397 issue - animation editor wrong frame edit

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-bugs#8096] opened 2024-07-02 03:30 UTC
## Problem description

R397 introduces a small but annoying issue with the animations editor. When double clicking a sprite, it no longer jumps to that frame in the editor, instead opening frame 0.

While this seems like a small detail, it's actually pretty annoying when using sprites for static environment objects, as it's not unusual to have a lot of objects saved into single animations.

See this gif for a comparison of the difference between r397 and r388-2:

![editor frames](https://github.com/Scirra/Construct-bugs/assets/46861823/d0ac6982-902c-468c-ae40-81b32bcac318)

Probably not necessary, but here's a project:
[editor frames.zip](https://github.com/user-attachments/files/16061279/editor.frames.zip)

## Steps to reproduce

1. Open up two copies of C3. One in R397 and any previous version. 
2. Double click the sprite and take note of the frame it jumps to.

## Observed result

Newest build doesn't jump to the current frame.

## Expected result

Jump to current frame

**First affected release:** R397

**Comment by AshleyScirra** [comment] 2024-07-02 13:35
Looks like a regression in r389 (that's the first affected release, not r397)

**Comment by DiegoScirra** [comment] 2024-07-02 18:54
Will be fixed in the next beta.

**Closed by DiegoScirra** 2024-07-02 18:54 UTC
