### ISSUE TITLE
Problem with viewport fit

### ISSUE THREAD

**Issue by DeividHiGamboa** [Scirra/Construct-bugs#6367] opened 2022-12-31 01:17 UTC
## Problem description

Hi, I'm new to "Construct 3" and just ran into a bug with versions after r308,They do not affect versions prior to r308, in the photos I use version r302. The problem is that the viewport fit does not work, if it is set to automatic or to cover it gives the same result as when it is set to cover, and I tried version r302 and it works as expected. I was investigating and I saw that the error is caused by the new export to android 12. This happened in an engine similar to this one (Gdevelop), I hope they fix it soon, thanks for making such a great engine!!!!

Version: r302
![Screenshot_20221230-191424](https://user-images.githubusercontent.com/109392555/210120711-994b01f7-026c-4bc7-b48c-db2211493d50.png)

Version: r317.2
![IMG-20221230-WA0002](https://user-images.githubusercontent.com/109392555/210120673-2a5fdce8-44f1-4900-a965-1b90d2768327.jpg)

Ps: English is not my native language, I hope you understand what I mean

## Attach a .c3p

[Fghge.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10326649/Fghge.c3p.zip)

## Steps to reproduce

1. Enter a version later than 308
2. create project
3. Change viewport fit to automatic
4.Export to android

## Observed result

The application covers the entire screen ignoring the settings 

## Expected result

It adjusts according to the configuration 

## More details

**Affected browsers/platforms:** 
Android and maybe ios?

**First affected release:** 
Version: r308
## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Product: Construct 3 r317.2 (stable)
Browser: Edge 108.0.1462.54
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
Language setting: es-ES

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 1,7 gb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 600 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by C3GameDev** [comment] 2023-01-01 14:45
Hi,
it's a cordova issue, everyone has this problem atm.

**Comment by DeividHiGamboa** [comment] 2023-01-03 00:49
> Hi, it's a cordova issue, everyone has this problem atm.

Is there a way to fix it or do you have to wait for scirra to come up with a solution or wait for cordova to fix it? There is no longer any way to support the notch, what could I do, the viewport fit does not work and neither does the platforminfo safeareainsettop. Will they give a quick solution or do you have to wait a long time?

**Comment by AshleyScirra** [comment] 2023-01-03 12:53
I'll look in to this but if the problem is with Cordova itself it may be beyond our control. Such issues can be reported to Cordova directly [here](https://github.com/apache/cordova-android/issues). The update for Android 12 was mandatory as without it nobody can even publish their apps as the Google Play store requires it, so unfortunately if that broke something else then there's no way to go back.

**Comment by fredriksthlm** [comment] 2023-01-09 15:55
I **_believe_** the reason for this is due to the below..

Construct 3 "codefix" for notch is to run LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES programmatically after the app is opened and the default theme is applied. This worked previously since the app only had one theme, for the main activity only.

Now the apps from Cordova use one theme for splash, and one for the "app". I believe the second theme is set _after_ the notch-fix code is run(?). And then the default cutout mode from the default theme is used.

Many of us never use the notch fix code snippet at all, since we define cutout mode directly in the theme instead. So for all of us that builds our apps in Android Studio, this is not a problem.

(There is an **unsupported** way of setting the second theme in the config xml (it's called AndroidPostSplashScreenTheme), which you might be able to look into, if you do not use Android Studio. )

**Comment by AshleyScirra** [comment] 2023-06-16 15:17
I spent a while working on Android exports today and looking in to this issue. It's pretty confusing especially as some comments seem to have interpreted the issue wrong: the problem reported is that viewport fit mode "Auto" should *not* extend the display in to the notch area (i.e. it should remain in a rectangular safe area). However the situation appears to be that it's not just the "Viewport fit" setting that controls whether you get a fullscreen experience: it's also the "Hide status bar" setting. So if "Viewport fit" is set to "Auto" and you choose "Hide status bar" on export, then it does the same thing on Android as if you chose viewport fit "Cover". The only way to avoid getting the screen to go in to the notch area is to choose both viewport fit "Auto" *and* make sure "Hide status bar" is unchecked on export.

This appears to be pretty old code so I think this is by design, and it's not clear that it was a regression or ever meant to be controlled solely by the "Viewport fit" setting, as it also involves the "Hide status bar" setting for Android, and the original report does not mention whether this was set or not. So it could be confusion caused by whether or not that setting was enabled. I did experiment with not using fullscreen mode and only hiding the status bar on Android, but this appears to also expose the notch area, rather than leaving only the safe area active. So that doesn't seem to help with keeping a safe rectangular area only. Perhaps it did change with a previous Cordova or Android update, but this just seems to be how it works now, and I don't think there's any obvious way to configure a safe-area-only rectangular view with an invisible status bar and system navigation. If someone finds a way to configure Cordova to do that I guess we could add it, but it's not clear it's supported at the moment. So I don't think there's any action we can take on this right now, so closing. In summary if you want to keep a rectangular view on a notch device, export with viewport fit "Auto" and "Hide status bar" unchecked, and that does currently work.

**Closed by AshleyScirra** 2023-06-16 15:17 UTC
Labels: external, Android
