### ISSUE TITLE
Copy picked picking incorrect after 'Wait'

### ISSUE THREAD

**Issue by GeometriXza** [Scirra/Construct-bugs#6752] opened 2023-03-12 08:21 UTC
## Problem description

When a copy-picked function calls another, non-copy-picked function, the picked family instances are retained.

## Attach a .c3p
[copyPickedBug.zip](https://github.com/Scirra/Construct-bugs/files/10950301/copyPickedBug.zip)

## Steps to reproduce

1. Open attached project.
2. Right-click on any sprite.

## Observed result

The clicked sprite flashes, and then tweens.

## Expected result

The clicked sprite should flash, and then all of the sprites should tween.

## More details
Copy picked works exactly as it should. However, it can be useful to call a function that applies actions to all instances of family objects or pick its own instances. When the non-copy-picked function is called directly, it applies the tween action to all family objects, as it should. However when the non-copy-picked function is called from a copy-picked function, this is not the case.

**Affected browsers/platforms:**

Chrome 111.0.5563.64

**First affected release:**

Tested in latest stable (r327.3) and beta (r333)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327.3 (stable)
Browser: Chrome 111.0.5563.64
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 516 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment] 2023-03-12 10:34
It seems that after waiting for an event, the state for the next called function is incorrectly restored.

**Comment by DinoSystem** [comment] 2023-03-12 17:51
Yeah, without the wait it works as intended, even a wait of 0 sec causes the issue.

**Comment by dop2000** [comment] 2023-03-14 05:05
Duplicate of my report #6477
I thought it should've been fixed by now?

**Comment by WilsonPercival** [comment] 2023-03-14 05:11
> Duplicate of my report #6477 I thought it should've been fixed by now?

That's because you're in a hurry, you're confused. Your mistake has been corrected, and this is not a duplicate, but a new one.

**Comment by AshleyScirra** [comment] 2023-03-16 17:08
This is similar to #6477 but in this case it still happened when adding a 'Wait'. It should be fixed for the next beta.

**Closed by AshleyScirra** 2023-03-16 17:08 UTC
