### ISSUE TITLE
Mouse - Can't do Left & Right click at the same time in Pointer lock

### ISSUE THREAD

**Issue by SalmanShhh** [Scirra/Construct-bugs#7993] opened 2024-05-07 18:39 UTC
if you have mouse locked to the game, it won't register left and right click at the same time

only works in 2 scenarios.
- when the mouse is moving in Pointer lock
- when running project in debug preview??

## Attach a .c3p
https://cdn.discordapp.com/attachments/517079142681018368/1237471016842694746/C3_Pointer_clicking_Bug.c3p?ex=663bc431&is=663a72b1&hm=4b6e0666f89461b480271d7853fd1f81c1e76f7dfd8fff004613756fd065e3e9&

## Steps to reproduce

1. Left click to lock the mouse.
2. hold right click and then left click.
3. the arrow should animate if the input is registered.

## Observed result

- Holding Right click makes the arrow point towards the mouse
- when the mouse is locked to the game it no longer animates on click left click while holding right click
- only works correctly when moving the mouse and then doing both click inputs.
![chrome_QM4dF0FQCA](https://github.com/Scirra/Construct-bugs/assets/21278459/4f06041b-c798-4891-9230-75772f0acb88)

## Expected result

![chrome_WEs9cYws1m](https://github.com/Scirra/Construct-bugs/assets/21278459/0ca34f36-b50e-431f-97f6-4371235cd24e)

## More details

**Affected browsers/platforms:** 
- on Chrome
- on Edge

**First affected release:** 
first discovered the issue in stable r388.2 , still persists to the latest beta r390
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r390 (beta)
Browser: Chrome 124.0.6367.119
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 560 gb
Storage usage (approx): 291 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment] 2024-05-08 10:48
It turns out this is a duplicate of #5381 - it's a bug in Chrome that has already been filed here: https://issues.chromium.org/issues/40817651

**Closed by AshleyScirra** 2024-05-08 10:48 UTC
Labels: duplicate
