### ISSUE TITLE
Crash dragging multiple functions/custom actions out of group

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#6949] opened 2023-04-19 16:27 UTC
## Problem description

I just moved a custom actions from a group to another group and it crashed.  

![Snipaste_2023-04-21_15-15-40](https://user-images.githubusercontent.com/45864744/233568302-0a351d18-8ae6-4243-92b8-567ce091a77a.png)

## Attach a .c3p

[issue#6949.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11293175/issue.6949.c3p.zip)

## Steps to reproduce

moved Group 2 to Group 1

## Observed result

crash.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r336/projectResources.js, line 1713, col 13
Message: Uncaught [object Object]
Stack: undefined
Construct version: r336
URL: https://editor.construct.net/
Date: Wed Apr 19 2023 23:52:00 GMT+0800 (中国标准时间)
Uptime: 7915 s

Platform information
Product: Construct 3 r336 (stable)
Browser: Chrome 112.0.5615.121
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Super with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by AshleyScirra** [comment] 2023-04-20 10:40
The bug report guidelines ask for a minimal project with clear steps to reproduce. Can you provide these?

The project is large and complicated compared to a minimal project which makes it difficult to investigate issues, and I'm not sure exactly what to do because the steps to reproduce don't explain precisely what to do. I tried moving a custom action to another event group and it worked fine for me.

**Comment by XHXIAIEIN** [comment] 2023-04-20 10:42
Please see my first picture, the marked 'AddChoice' and 'AddBubble'custom function. It only crashes when move them.

**Comment by AshleyScirra** [comment] 2023-04-20 11:01
Can you provide a minimal project as per the bug report guidelines? It is exceptionally difficult to deal with problems in projects this complicated.

**Comment by XHXIAIEIN** [comment] 2023-04-20 11:13
I tried copying them to a new project with these event blocks, but when I paste them over, it easily crashes the new project. I'm trying to figure out exactly where the problem is.

**Comment by XHXIAIEIN** [comment] 2023-04-21 07:11
@AshleyScirra  

[issue#6949.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11293145/issue.6949.c3p.zip)

![Snipaste_2023-04-21_15-10-46](https://user-images.githubusercontent.com/45864744/233566440-0e6d9bf6-9dcd-4c9f-b96a-097703589508.png)

**Comment by AshleyScirra** [comment] 2023-04-21 13:23
Thanks, finding a minimal repro really helps.

**Comment by AshleyScirra** [comment] 2023-04-21 14:12
The crash should be fixed in the next beta. Note however that issue #6949 remains so in these cases the drag-and-drop isn't allowed to be completed because of the other issue, but at least it does not crash.

**Closed by AshleyScirra** 2023-04-21 14:12 UTC
