### ISSUE TITLE
CONSTRUCT 3 R373 - Cannot open from dropbox

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-bugs#7707] opened 2024-01-03 16:31 UTC
## Problem description

CONSTRUCT 3 R373 Cannot refresh list from dropbox.

## Attach a .c3p

Not required (cant open them!)

## Steps to reproduce

1. Try to load from Dropbox
2.
3.

## Observed result

Cannot refresh List

## Expected result

To see my projects

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2024-01-04 10:25
Duplicate of #7708. This was a regression introduced in r373.

**Closed by DiegoScirra** 2024-01-04 10:25 UTC
Labels: duplicate
