### ISSUE TITLE
DrawingCanvas - Not smooth movement

### ISSUE THREAD

**Issue by starkiJi** [Scirra/Construct-bugs#7496] opened 2023-10-27 12:27 UTC
### **Problem description**
The **Sprite** object always moves smoothly, but the **DrawingCanvas** object jerks when it slows down, you will see when you run the project

### **Attach a .c3p**
[DrawingCanvas_Not smooth movement_r364b.zip](https://cloud.mail.ru/public/xKyt/KYAEH5D4H)

### **Steps to reproduce**
1. Open a project.
2. Start the project
3. Look at the **DrawingCanvas** objects when they start to slow down and compare them to the **Sprite** object, which always moves smoothly

### **Expected result**
**DrawingCanvas** moves as smoothly as a **Sprite**

### **More details**
Chrome, r364b

**Comment by AshleyScirra** [comment] 2023-10-27 13:30
This is currently by design - by default Drawing Canvas does pixel snapping to ensure the drawn content can display pixel-perfectly, as in other use cases, that's what people expect it to do (and not doing it results in bug reports like "drawn content looks blurry"). One workaround is to set the Drawing Canvas angle to something like 0.0001, so it visibly doesn't look rotated, but a non-zero angle disables the pixel snapping.

It might be straightforward to add a setting for this, but I have to ask, why do you need it? It seems quite a contrived example. If it's for a menu or something, wouldn't normal sprites suffice?

**Comment by starkiJi** [comment] 2023-10-27 14:12
> _This is currently by design - by default Drawing Canvas does pixel snapping to ensure the drawn content can display pixel-perfectly, as in other use cases, that's what people expect it to do (and not doing it results in bug reports like "drawn content looks blurry"). One workaround is to set the Drawing Canvas angle to something like 0.0001, so it visibly doesn't look rotated, but a non-zero angle disables the pixel snapping._
> 
> _It might be straightforward to add a setting for this, but I have to ask, why do you need it? It seems quite a contrived example. If it's for a menu or something, wouldn't normal sprites suffice?_

1. I started improving the game menu. 
2. The game is planned for mobile phones. 
3. To prevent the game from slowing down on weak phones, I came up with the idea of moving the **Text** object to the **Drawing Canvas** object, since **Drawing Canvas** is a more productive object compared to **Text**
4. I also use this approach with **Text** and **Drawing Canvas** in other places, this allows me to translate for a large number of languages, otherwise I will have to have a large number of **Sprites** with many names in many languages.
5. This is not a critical problem, I can tolerate it, but if you have time, I would be happy with the option.
6. Here is a short video from the game menu, The text below on the buttons caught my attention and I created an Issue. - https://youtube.com/shorts/-_K24YmX3U4
7. **Good luck!**

**Comment by AshleyScirra** [comment] 2023-10-27 14:31
> To prevent the game from slowing down on weak phones, I came up with the idea of moving the Text object to the Drawing Canvas object

This should not be any faster. A Text object that does not change should be rendering pretty much identically to a Drawing Canvas: it just draws a pre-generated texture. That should be about as fast as drawing a Sprite. So you should not need to do that at all.

If you can measure a performance degradation using non-changing Text objects, please file an issue so I can look in to that.

I don't think this use case makes sense, so the original issue should not need solving, so closing as not a bug.

**Closed by AshleyScirra** 2023-10-27 14:31 UTC
