### ISSUE TITLE
Chrome tab crash STATUS_BREAKPOINT when using some dialogs

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7321] opened 2023-08-22 15:39 UTC
## Problem description

![obser](https://github.com/WilsonPercival/WilsonPercival/assets/91274932/87ce8c04-8c8a-4406-b4d4-d8c153dae90b)

## Attach a .c3p

No.

## Steps to reproduce

1. Create a new project.
2. Add a sprite.
3. Go to the Event sheet editor.
4. Right-click and select `Add custom action`.
5. Click `<click to choose>`. A window will open, click `OK`.
6. In the `Name` field, select the text `Action1`.
7. Press `Enter`.

Please repeat the steps exactly, otherwise you won't be able to repeat the mistake.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/ed0c7b70-231d-4d62-89bf-0c713edce1f5

## Expected result

The editor works well.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r354b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r354 (beta)
Browser: Chrome 115.0.5790.171
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 92 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-08-23 14:29
Tab crashes indicate a problem in the browser, not Construct. I can reproduce in Chrome stable v116, but it does not reproduce in Chrome canary v118, so this looks like a Chrome bug that was already fixed.

**Comment by XHXIAIEIN** [comment] 2023-08-23 22:34
This problem also happens on r350, Edge 116.0.1938.54.
It can be reproduced when edit the Category of Function.

This problem has affected my work very much, it is very frequent, and I even turned on the automatic backup every 2 minutes.

**Comment by AshleyScirra** [comment] 2023-09-01 11:28
Just an update on this as it looks like lots of people are running in to it: I can reproduce this in Chrome v116 stable, but it does not appear to reproduce in Chrome v117 beta. So it appears to be a crash in Chrome v116 that has already been fixed for v117. The [release schedule](https://chromiumdash.appspot.com/schedule) shows that v117 will start rolling out as the new stable release in the next week or two, so everyone will be auto-updated to that version soon. Given how short that time scale is I don't think there's anything to be gained by filing an issue with Google - it already looks fixed and it's unlikely they'd act any sooner even if an issue was filed. So until then, if this is problematic for using Construct, you can [download and install Chrome beta](https://www.google.com/chrome/beta/) which won't be affected, and then switch back to the stable version when it's out. Note this all also applies to Microsoft Edge as that uses the same browser engine as Chrome, and you can [also download Edge beta](https://www.microsoftedgeinsider.com/) as a similar workaround.

To try to avoid further duplicates, leaving this issue open and marked 'Fixed'.

**Comment by WilsonPercival** [comment] 2023-09-13 00:33
@AshleyScirra You were right. Now I tried it on 117, and this bug is no longer there.

**Comment by AshleyScirra** [comment] 2023-09-13 11:18
Chrome v117 is now rolling out to stable, so closing this issue. In Chrome, go to Menu -> Help -> About Google Chrome to check the version and update if necessary. In Edge go to Menu -> Help and feedback -> About Microsoft Edge (it might take another couple of days for the corresponding Edge update to start rolling out). Both should automatically update over the next couple of weeks even if you do nothing.

**Closed by AshleyScirra** 2023-09-13 11:18 UTC
Labels: external, chrome
