### ISSUE TITLE
User media can't get camera feed on majority of Android devices

### ISSUE THREAD

**Issue by technofou** [Scirra/Construct-bugs#7764] opened 2024-01-22 04:31 UTC
## Problem description

User media is able to get the camera feed for iPhones and Pixel devices, but not for the majority of Android devices currently used which are modern Galaxy devices. This bug affects the majority of Android users today. The green indicator does light up after permission is given, but the feed is black.

## Attach a .c3p

Exporting the official Scirra User Media example project with Cordova.

## Steps to reproduce

1. Take the official User Media example project
2. Export with Cordova
3. Run on a Pixel device (cameras are detected and the feed is shown)
4. Run on a modern Galaxy device (the list is incomplete, green indicator appears, but feed is black)

## Observed result

Permission is asked, but even when granted 3 different Galaxy devices tested across OneUI 4 & 5 were unable to show the camera feed.

## Expected result

For the camera feed to appear, especially when using the official example project, regardless of the Android device, but especially on the devices sold and used by the majority of Android users today.

## More details

We initially thought it was a privacy issue with the brand-new version of Android, but unfortunately, our Z Flip 5, S23 Ultra, and S20 Ultra failed to show the camera feed properly. Exporting to an Xcode project worked for iOS devices.

At first, we thought it was the code for our game, but trying it with the official Scirra User Media example file didn't fix the issue and highlighted the problem with modern Galaxy devices.

I do understand that in Bug #7716 @AshleyScirra mentioned that he tested on a Zenphone 8 and Galaxy S8, but one is a very niche device and the other is an outdated 8-year-old Galaxy device; both do not represent the experience that the majority of Android users (using modern Galaxy devices) will experience, and is not an actual representation of the current state.

With the majority of applications today able to run and use the camera feed on modern Galaxy devices, the responsibility is on Construct/Cordova to support their implementations properly. The majority of Android customers today will face this issue, and that is with your current example and recommended implementation compiled using your provided tools.

The statement that this bug affects the majority of Android users today is valid and should require a second look and proper testing with a modern average Android device, somewhere around a fully updated Samsung Galaxy S21+.

**Comment by AshleyScirra** [comment] 2024-01-22 13:08
This is a duplicate of #7716 and my best guess would be it's a device-specific issue that is beyond our control to fix, so even if we purchased an affected device and observed the issue, there would still not be anything we can do. As I advised in the other issue the best approach here would be to report the issue to Samsung and/or Google who would be better placed to deal with it.

**Closed by AshleyScirra** 2024-01-22 13:08 UTC
Labels: duplicate

**Comment by technofou** [comment] 2024-01-23 04:07
This is not a "device-specific" issue but one that affects the majority of Android devices, as Samsung is the market leader. The probability of Samsung changing their platform instead of Construct adapting to it is extremely slim. Google can't do anything about it since it works on their Pixel (minority market share), and this is a modern Galaxy issue.

It means that Scirra accepts not to adapt their development tool to be compatible with the number one phone manufacturer on the planet in the hope that they will change for a minority third-party development tool. This is punishing for us developers using Construct.

**Comment by AshleyScirra** [comment] 2024-01-23 11:09
It's not our responsibility to fix everything that goes wrong in the entire software industry. It is Samsung and Google's responsibility to ensure their devices and software works with agreed industry standards such as browser specifications. Device-specific problems are often cause by system problems like graphics driver bugs; it's not our responsibility to ensure all Samsung devices have correctly functioning graphics drivers, that's on Samsung. Sometimes people don't understand this point or don't believe us and continue insisting we make device-specific system software work even though it's impossible and entirely outside our responsibility. For this reason our [Forum & Community Guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035) include a rule against insisting we do the impossible. Please don't be that person. I've advised the best direction to go in to get the problem fixed, and so I suggest you go and try that instead of doing the equivalent of insisting your car manufacturer repairs the roads.
