### ISSUE TITLE
microbit button bug

### ISSUE THREAD

**Issue by cncw252** [Scirra/Construct-bugs#7924] opened 2024-03-26 19:01 UTC
## Problem description

the microbit button services  don't work.
## Attach a .c3p

 the 3 example projects.
## Steps to reproduce

1.Set up my phone and microbit as the  Tutorial say (GETTING STARTED WITH THE BBC MICRO:BIT).

## Observed result

when i run the Accelerometer and led and button services, the botton don't work. then i run the button services only, A botton is work ,but b botton don't work.
thermometer and magnetometer say  "no reading" too.
 i use C3(384 & 385)  Edge 122.0.2365.86 on Android phone in China. microbit is v2.21.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2024-03-27 17:05
It worked fine for me. Are you sure it's not something like a Bluetooth connection issue, or that the buttons are getting stuck or something?

**Comment by F3der1co** [comment] 2024-03-27 18:39
I can confirm I have the same issue, I ordered a Microbit v2 after the update and played with it a bit, in the examples only the accelerometer and LEDs work for me

**Comment by AshleyScirra** [comment] 2024-03-28 10:52
I have a BBC micro:bit v2.21. For the firmware version, the DETAILS.TXT file that appears if you connect it with USB shows `Build ID: v0257-gc782a5ba`. In Construct 3 r385, everything is working fine for me: accelerometer, buttons, temparature, bearing (which requires calibration), and LED. I think this proves if there is a problem, it's not with Construct, as if it was then it wouldn't all work for me in r385. So I'm afraid it looks like the problem is somewhere else - perhaps the Bluetooth connection is poor, which would be a common cause of things working intermittently. Perhaps there's some other hardware or software specification that needs to be met, but I don't know what that could be, as all I see is everything working. Unfortunately that means I don't see any action that we can take, so closing this issue.

**Closed by AshleyScirra** 2024-03-28 10:52 UTC
Labels: can't reproduce
