### ISSUE TITLE
Unable to create a new object in Editor

### ISSUE THREAD

**Issue by Darkderd** [Scirra/Construct-bugs#7829] opened 2024-02-14 10:48 UTC
## Problem description

Unable to create a new object in Editor
## Attach a .c3p

[project.zip](https://github.com/Scirra/Construct-bugs/files/14278368/project.zip)

## Steps to reproduce

1.Create project
2.insert new object/sprite
3. press OK and get error
![Записати](https://github.com/Scirra/Construct-bugs/assets/160015721/2140b2ff-e761-435f-a064-3223b80c073a)

## Observed result

next error
`Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. @ Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. at Function.C.IO (https://editor.construct.net/r379/main.js:1099:124) at d.fS (https://editor.construct.net/r379/projectResources.js:811:200) at d.fS (https://editor.construct.net/r379/projectResources.js:725:185) at async https://editor.construct.net/r379/projectResources.js:2944:169 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Stack: Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. at Function.C.IO (https://editor.construct.net/r379/main.js:1099:124) at d.fS (https://editor.construct.net/r379/projectResources.js:811:200) at d.fS (https://editor.construct.net/r379/projectResources.js:725:185) at async https://editor.construct.net/r379/projectResources.js:2944:169 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Construct version: r379
URL: https://editor.construct.net/
Date: Wed Feb 14 2024 12:42:43 GMT+0200 (за східноєвропейським стандартним часом)
Uptime: 42.8 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 100.0.4896.75
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) c3_wladek_hack/1.4.0 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.2.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_video_texture, WEBGL_webcodecs_video_frame, OVR_multiview2`

## Expected result

Create new object

## More details

Chrome/Windows

**First affected release:** 

## System details

Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. @ Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. at Function.C.IO (https://editor.construct.net/r379/main.js:1099:124) at d.fS (https://editor.construct.net/r379/projectResources.js:811:200) at d.fS (https://editor.construct.net/r379/projectResources.js:725:185) at async https://editor.construct.net/r379/projectResources.js:2944:169 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Stack: Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. at Function.C.IO (https://editor.construct.net/r379/main.js:1099:124) at d.fS (https://editor.construct.net/r379/projectResources.js:811:200) at d.fS (https://editor.construct.net/r379/projectResources.js:725:185) at async https://editor.construct.net/r379/projectResources.js:2944:169 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Construct version: r379
URL: https://editor.construct.net/
Date: Wed Feb 14 2024 12:42:43 GMT+0200 (за східноєвропейським стандартним часом)
Uptime: 42.8 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 100.0.4896.75
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) construct 3/1.4.0 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.2.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_video_texture, WEBGL_webcodecs_video_frame, OVR_multiview2
<details><summary>View details</summary>

**Comment by AshleyScirra** [comment] 2024-02-14 10:56
Duplicate of #7824. Perhaps do not come to us with support requests when you use Electron with `c3_wladek_hack`.

**Closed by AshleyScirra** 2024-02-14 10:56 UTC

**Comment by Darkderd** [comment] 2024-02-14 11:22
okey
