### ISSUE TITLE
After copy of sprite editor crash

### ISSUE THREAD

**Issue by benjaboyy** [Scirra/Construct-bugs#7384] opened 2023-09-10 17:04 UTC
## Problem description

I copied the sprite animation and it looks like it changes some of the settings which coused it to crash. After reloading the crashed project that animation can not be clicked or the program crashes.

## Attach a .c3p

[AirForceInterstellar.zip](https://github.com/Scirra/Construct-bugs/files/12569425/AirForceInterstellar.zip)

## Steps to reproduce

1. Open project
2. Open animation editor of "HUD-WeaponIcon"
3. Select "Grenade 2" 
- CRASH -

## Observed result

Crash report, but i also see a -1 in the frame field of the animation

## Expected result

No crashies

## More details

Tested stable and bleeding edge

**Affected browsers/platforms:** 

Windows chrome

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Q.Ia (https://editor.construct.net/r357-2/main.js:1050:312) at Cz (https://editor.construct.net/r357-2/projectResources.js:340:29) at fHa (https://editor.construct.net/r357-2/projectResources.js:182:187) at https://editor.construct.net/r357-2/projectResources.js:181:489
Stack: TypeError: unexpected type at Q.Ia (https://editor.construct.net/r357-2/main.js:1050:312) at Cz (https://editor.construct.net/r357-2/projectResources.js:340:29) at fHa (https://editor.construct.net/r357-2/projectResources.js:182:187) at https://editor.construct.net/r357-2/projectResources.js:181:489
Construct version: r357.2
URL: https://editor.construct.net/r357-2/
Date: Sun Sep 10 2023 18:56:44 GMT+0200 (Central European Summer Time)
Uptime: 56 s

Platform information
Product: Construct 3 r357.2 (beta)
Browser: Chrome 116.0.5845.180
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by WilsonPercival** [comment] 2023-09-10 17:18
@benjaboyy Could you provide the steps to reproduce the crash after copying? I mean the crash that happened before this crash.

**Comment by WilsonPercival** [comment] 2023-09-10 17:35
@DiegoScirra I'm sure this is a duplicate of https://github.com/Scirra/Construct-bugs/issues/7245

The sprite had a `Grenade` animation. @benjaboyy copied and pasted it. After this Construct crashed (#7245). Further, perhaps @benjaboyy saved the project and now the `Grenade2` animation does not open, instead Construct crashes.

**Comment by DiegoScirra** [comment] 2023-09-15 17:42
I can reproduce the crash, but I rather not fix it because the project is in an inconsistent state where the animation has no frames, which isn't possible normally.

Check the next release to see if the problem that lead to producing the corrupted animation has been fixed.

**Comment by WilsonPercival** [comment] 2023-09-19 14:18
> r359 is now out, can check again.

@AshleyScirra Here the crash still remains.

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Q.Ja (https://editor.construct.net/r359/main.js:1050:312) at Cz (https://editor.construct.net/r359/projectResources.js:340:29) at gHa (https://editor.construct.net/r359/projectResources.js:182:187) at https://editor.construct.net/r359/projectResources.js:181:489
Stack: TypeError: unexpected type at Q.Ja (https://editor.construct.net/r359/main.js:1050:312) at Cz (https://editor.construct.net/r359/projectResources.js:340:29) at gHa (https://editor.construct.net/r359/projectResources.js:182:187) at https://editor.construct.net/r359/projectResources.js:181:489
Construct version: r359
URL: https://editor.construct.net/r359/
Date: Tue Sep 19 2023 17:18:19 GMT+0300 (Восточная Европа, летнее время)
Uptime: 685 s

Platform information
Product: Construct 3 r359 (beta)
Browser: Chrome 117.0.5938.89
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

**Comment by DiegoScirra** [comment] 2023-09-21 10:38
The original crash, that comes from copying and pasting an animation, has already been fixed in the r359. This issue is a side effect of that, so won't do anything to avoid this as it essentially has to do with loading a corrupted project which shouldn't happen in the first place.

**Closed** 2023-09-21 10:38 UTC

**Comment by benjaboyy** [comment] 2023-09-21 21:35
ive build for 2 weeks on this project, can i remove the corrupted part?

**Comment by DiegoScirra** [comment] 2023-09-21 23:02
I am thinking that maybe it is possible to use the bulk importing options to replace the animation without actually selecting it which is when the crash happens. I'll try doing that and see how it goes, if that works I'll let you know how to do it yourself.

If it doesn't work I can always just edit the relevant project files to get rid of the corrupted animation and send the project back to you.

Is the project you shared the latest version?

**Comment by DiegoScirra** [comment] 2023-09-22 10:22
@benjaboyy

You can get rid of the animation that is causing problems by opening the Object Type that has it in the Animations editor and then dropping this file [fix.zip](https://github.com/Scirra/Construct-bugs/files/12699676/fix.zip) into the animations panel.

After doing that the animation will have one frame and won't be corrupted anymore, after that you will be able to delete it.
