### ISSUE TITLE
Swirl effect WebGPU bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7450] opened 2023-10-08 16:51 UTC
## Problem description

When the game is launched on `WebGL`, the `Swirl` effect spins clockwise, and when on `WebGPU`, it spins counterclockwise.

## Attach a .c3p

<img width="315" alt="attach" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/f02d782d-5ae4-4fdf-8229-82b2004a3ff1">

## Steps to reproduce

1. Open `Effects - swirl transition`.
2. In the left ear, change the value of the `Enable WebGPU` parameter to `Yes`.
3. Run the project.

## Observed result

`WebGPU`:

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/807c8136-e4e3-4ff0-989a-f48ca0c8d130

`WebGL`:

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/6b562c4a-725a-4d58-b5c3-3ac8db0e3c6b

## Expected result

The effect should curl equally on `WebGL` and `WebGPU`.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r361b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r361 (beta)
Browser: Chrome 117.0.5938.132
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 226 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by F3der1co** [comment] 2023-10-10 09:38
Yes I noticed too that the UV coordinates are flipped when I created some of my 3rd party shaders.
To me it seems like the **webGL version is incorrect** when applied to a layer or layout, while webGPU is correct. What I mean with correct: the coordinates are consistent when applying the effect to a layer, layout and instance.

**Comment by AshleyScirra** [comment] 2023-10-20 14:54
I've fixed the WebGPU 'Swirl' effect to go in the same direction as WebGL for the next beta.

@F3der1co - I'm afraid I don't think it's feasible to change the co-ordinate system for WebGL. Firstly there are axis differences at the API level (e.g. Y-up vs. Y-down, different Z ranges, etc) which can't always easily be compensated for. Secondly we can't change how the co-ordinate system works in existing WebGL shaders without risking breaking third-party effects going back years (whose developers may not even be around any more). So I think it's just something we have to live with. If WebGPU is correct, then at least we have the right design for the future.

**Comment by F3der1co** [comment] 2023-10-20 15:05
> I've fixed the WebGPU 'Swirl' effect to go in the same direction as WebGL for the next beta.
> 
> @F3der1co - I'm afraid I don't think it's feasible to change the co-ordinate system for WebGL. Firstly there are axis differences at the API level (e.g. Y-up vs. Y-down, different Z ranges, etc) which can't always easily be compensated for. Secondly we can't change how the co-ordinate system works in existing WebGL shaders without risking breaking third-party effects going back years (whose developers may not even be around any more). So I think it's just something we have to live with. If WebGPU is correct, then at least we have the right design for the future.

I see. I'm interested to see your fix in the next beta so I can apply this to my shaders.

**Comment by F3der1co** [comment] 2023-11-16 14:59
@AshleyScirra 
so you just flipped it, so now the same issue exists but when the effect is applied to an object...

**Comment by AshleyScirra** [comment] 2023-12-20 17:15
The fix for this didn't seem right as it caused #7569, so reopening.

**Comment by AshleyScirra** [comment] 2024-02-07 11:34
There is a significant complication here, which is that the WebGL renderer actually has a bug. See this repro: [issue7450.zip](https://github.com/Scirra/Construct-bugs/files/14192768/issue7450.zip)

With the WebGL renderer, the swirl effect on a layout rotates clockwise, but on an object it rotates counter-clockwise. The reason for this is that WebGL sometimes inverts the Y direction (due to WebGL having ridiculous complications from inconsistent Y direction in different parts of the API); Construct also has to invert the Y direction in certain circumstances to match the situation in WebGL, but didn't always do it correctly, causing a difference in rotation direction between object effects and layout effects.

The WebGPU renderer was not affected by this - the WebGPU API is better designed and has a consistent Y direction through the API, and so Construct never needs to invert the Y direction in the WebGPU renderer. This is why I could not originally get the WebGPU effect to render consistently with WebGL - it's because rendering in WebGL is not consistent!

So for the next release cycle I've tried to align everything with rotating clockwise. This means changing swirl effects on objects in the WebGL renderer from rotating counter-clockwise to rotating clockwise, which is technically a breaking change, but hopefully not a serious one (if only used for cosmetic purposes then I guess the swirl direction doesn't really matter). Then I've adjusted the WebGPU swirl effect to rotate clockwise too so it is consistent with WebGL rendering.

@F3der1co - the complication here is that the inverted Y direction reached WebGL shaders. The rectangles passed in uniforms have the Y direction inverted, so instead of ranging from 0-1 for top-to-bottom, it uses the range 1-0. This can also mean the rectangles seem upside-down as the bottom position is above the top position, but this is just because the Y direction is inverted. Sometimes this doesn't affect anything, but sometimes it affects a shader's calculations and thus alters the effect. Therefore sometimes WGSL shaders must emulate the inverted Y direction used in GLSL for the src/srcOrigin/dest uniforms in order to produce the same effect. This was necessary both here for the swirl effect and for the Lens2 effect (#7541). For the swirl effect it's a simple inversion of the angle. However for Lens2 I used proper emulation of the inverted Y direction, like so:

```wgsl
// At start of shader: get normalized source co-ordinates
// and then invert Y direction to match WebGL
var tex : vec2<f32> = c3_srcToNorm(input.fragUV);
tex.y = 1.0 - tex.y;

// ... rest of effect ...

// At end of shader: calculate background sampling position
// and then invert Y direction again
p.y = 1.0 - p.y;
// ...
output.color = textureSample(textureBack, samplerBack, mix(c3Params.destStart, c3Params.destEnd, p));
```

So essentially you just need to get `y = 1.0 - y` in the right places in WGSL, and it should emulate the same thing done in GLSL. Sorry for the complication - it was a total nightmare to set up the effect compositor in WebGL, but at least we made it consistent in WebGPU!

**Closed by AshleyScirra** 2024-02-07 11:34 UTC
Labels: difficult, webgpu

**Comment by AshleyScirra** [comment] 2024-02-07 15:10
The fix for the swirl direction in WebGL immediately caused a bunch of regressions that I quickly found in my own testing. I think too many things depend on it working the way it does currently. I've had to revert the fix for that (although WebGPU still consistently rotates clockwise).

It may be simply too complicated to fix the WebGL effect processing at this point. I think it's likely most uses of 'Swirl' will be solely cosmetic and so not necessarily be seriously affected if the swirl rotates in a different direction. So I think we will just have to live with a difference there.
