### ISSUE TITLE
Failed To Open Project. Duplicate Animation Error.

### ISSUE THREAD

**Issue by davidFailedToOpen** [Scirra/Construct-bugs#8106] opened 2024-07-08 22:39 UTC
## Problem description

 The c3p file brings up an error upon opening:  Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

## Attach a .c3p

 
[tonkinNoAddons.zip](https://github.com/user-attachments/files/16134994/tonkinNoAddons.zip)

## Steps to reproduce

1. Change the extension from zip to c3p
2. Open the file in the construct 3 website

## Observed result

  Error: Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.
![image](https://github.com/Scirra/Construct-bugs/assets/174982841/939bbcc8-71aa-4ad3-a656-d5e23d7c75c8)
Console:
![image](https://github.com/Scirra/Construct-bugs/assets/174982841/11b163ca-e74a-48d4-96c0-41e91a2473a3)

## Expected result

 Open the project file.

## More details
 

 To solve the bug, I want to know how which bit I need to remove to remove the the duplicate animation successfully and turn it back into a valid c3p file. I already tried removing the duplicate animation. What I did after was I made a copy of the c3p file, renamed the format from c3p to zip, extracted it, located the JSON file in the objectTypes folder, opened it using notepad, found a duplicate animation on two different subfolders, deleted one of them (don't know if done correctly), saved the changes and exited, compressed as zip file, renamed the format from zip to c3p, then it gave me this error when I tried opening it on the construct 3 website: main.js:907 [Project] Exception opening: Error: missing file path 'project.c3proj'

**Affected browsers/platforms:**  Chrome, Opera GX, firefox

 r397

**First affected release:**  Worked in r397 and broke in r397

## System details

<details><summary>View details</summary>

PASTE HERE 
![image](https://github.com/Scirra/Construct-bugs/assets/174982841/ffa320fa-000f-4787-812f-c1fe6b692a25)

</details>

**Comment by davidFailedToOpen** [comment] 2024-07-09 02:02
Wait I don't even think you can open it even if you fix the duplicate animation error since I deleted a lot of files to minimize it because I couldn't send it here... It'll say something like 'missing file path'. Making a bug report on a bug that doesn't let you open the project itself is such a hassle since you cannot do much if you can't open the project.

**Comment by davidFailedToOpen** [comment] 2024-07-09 03:02
![image](https://github.com/Scirra/Construct-bugs/assets/174982841/e0636dc0-dcc3-46eb-8eac-279c2675534e)
I have made many attempts to remove the duplicate animation or to just remove the object type all together but it just spawned even more errors and gave up. My only hope to continue making my game project is that an experienced person can fix it for me. 
Here is the full file. https://www.dropbox.com/t/c4rlrG6qpa9hvWeR I don't know if it's less trusting if it's in dropbox than in here, but please someone find a solution to this bug. The same problem was fixed before in a previous bug report so it should be possible with my game. Thanks

**Comment by davidFailedToOpen** [comment] 2024-07-09 03:03
I didn't mean to close it

**Comment by CrackHub** [comment] 2024-07-09 10:31
```
{
"frames": [{
		"width": 160,
		"height": 160,
		"originX": 0.475,
		"originY": 0.91875,
		"originalSource": "",
		"exportFormat": "lossless",
		"exportQuality": 0.8,
		"imageSpriteId": 5062070,
		"collisionPoly": {
			"points": [0, 0.3041666666666667, 1, 0.3041666666666667, 1, 0.96875, 0, 0.96875]
		},
		"useCollisionPoly": true,
		"duration": 1,
		"tag": ""
	}],
"sid": 262976015114029,
"name": "scorch",
"isLooping": false,
"isPingPong": false,
"repeatCount": 1,
"repeatTo": 0,
"speed": 5
}
```
Duplicate code in nonSolidObject.json
Fixed version (+Bundled addons): https://mega.nz/file/l4RmTIqI#pb3PUxEIhxtHm3f4Obm54bXO9fobgOIA5ucSScLHy-0

**Comment by DiegoScirra** [comment] 2024-07-09 11:27
Thanks @CrackHub

I was just going to try and fix the project because there isn't much else to do about this otherwise. With out any steps to reproduce the original issue that causes the duplicate names, it's just guess work.

Closing.

**Closed by DiegoScirra** 2024-07-09 11:27 UTC
