### ISSUE TITLE
SDK v2 - Exception thrown on ACE SetPositionToObject from a custom plugin

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8324] opened 2024-11-13 05:46 UTC
## Problem description

When calling the action **Set Position To Object** from a custom plugin, construct throws an exception.

## Attach a .c3p
[set-position-to-object-error SDK v2.zip](https://github.com/user-attachments/files/17726944/set-position-to-object-error.SDK.v2.zip)
[drawingPlugin addon - Set Pos to Obj error.zip](https://github.com/user-attachments/files/17726946/drawingPlugin.addon.-.Set.Pos.to.Obj.error.zip)

## Steps to reproduce

1. Install the attached addon
2. Open and run the attached project

## Observed result

Construct throws an exception when setting the position of the red object to the green object. This happens when the ACEs are added using AddCommonPositionACEs() method from the IPluginInfo interface.

## Expected result

No exception should be thrown

## More details

r407.2 stable
r415 beta

## System details

<details><summary>View details</summary>

Uncaught (in promise) TypeError: t.GetPairedInstance is not a function
    at AnySDK.SetPosToObject (commonACEs.js:1:1895)
    at C3.Action._RunObject_ParamsConst (action.js:1:9875)
    at C3.EventBlock._RunActions_Fast (eventBlock.js:1:11517)
    at C3.EventBlock._RunAndBlock (eventBlock.js:1:10819)
    at C3.EventBlock.Run (eventBlock.js:1:9627)
    at C3.EventSheet._ExecuteTrigger (eventSheet.js:1:6080)
    at C3.EventSheet._TriggerForClass (eventSheet.js:1:4247)
    at C3.EventSheet._Trigger (eventSheet.js:1:3865)
    at C3.EventSheetManager._Trigger (eventSheetManager.js:1:6214)
    at C3.Runtime.Trigger (runtime.js:1:45612)

</details>

**Comment by AshleyScirra** [comment] 2024-11-13 12:57
Upon further investigation this also reproduces with a variety of other common ACEs - it turns out there's an oversight in the engine that meant some object and layer parameters and static conditions were not correctly handled with SDK v2. I've prepared a fix, but it is quite a complex and extensive change - given how close we are to a stable release I think it is too risky a change for this release cycle, so the fix will be in the next release cycle (first beta after the next stable release).

**Closed by AshleyScirra** 2024-11-13 12:57 UTC
Labels: sdk

**Comment by sotano42** [comment] 2024-11-13 16:53
> Upon further investigation this also reproduces with a variety of other common ACEs - it turns out there's an oversight in the engine that meant some object and layer parameters and static conditions were not correctly handled with SDK v2. I've prepared a fix, but it is quite a complex and extensive change - given how close we are to a stable release I think it is too risky a change for this release cycle, so the fix will be in the next release cycle (first beta after the next stable release).

Understood, looking forward to have it int the next beta.
