### ISSUE TITLE
Collision point erroneously adds/subtracts 0.1 from a corner

### ISSUE THREAD

**Issue by desertcucco** [Scirra/Construct-bugs#7728] opened 2024-01-09 19:19 UTC
## Problem description

When editing the collision points for a sprite, regardless of whether you manually enter the points, drag the points around, or use set to bounding box, one of the points will always add or subtract 0.1 from a corner after closing the sprite editor. This happens in every Construct project I test with, including ones in the Example Browser.

## Attach a .c3p

https://drive.google.com/file/d/184MKQfY_bLRvcdavEYSFhzMWg7qmxsrl/view

## Steps to reproduce

1. Open ObjectBank
2. Open Player_Base Sprite Editor
3. Navigate to collisions tab
4. Adjust any of the 4 collision points and make note of what you changed them to
5. Close and then reopen the sprite editor, navigate back to collisions tab
6. Check each of the points to find one of them with an x/y that either subtracted 0.1 or added 0.1 to what you set the collision points as.

## Observed result

A point that I set as x8 y8 will change to x8 y7.9. Another point that I didn't even touch may also change. In this video a point I directly edit subtracts 0.1 and then a random point I didn't touch adds 0.1. Video: https://www.youtube.com/watch?v=Qn6I9XOSzI4&ab_channel=Carl

Using Demonire as an example: if I go into the sprite editor for Player_Base and go to the collision tool, if I try setting each of the 4 points to the corner, the bottom-right point will set itself to x8 y7.9 even when I type x8 y8 or set to bounding box (which should set it to x8 y8 since the sprite is 8x8). Other points will randomlly add 0.1 or subtract 0.1 as well (see attached video).

This happens for **every sprite** so characters will sometimes stop moving if they're against a wall because they hit the 0.1 decrease.

I get this with every Construct project.

## Expected result

The collision points should remain as what they're entered and not randommly add/subtract 0.1 from the value.

## More details

**Affected browsers/platforms:** Google Chrome 120.0.6099.199, Mac OS Sonoma. I was getting this issue on older versions of Chrome as well.

**First affected release:** I first noticed this when starting Construct a few months ago and it's persisted after however many updates there's been.

**VIDEO:** https://www.youtube.com/watch?v=Qn6I9XOSzI4&ab_channel=Carl

**Comment by WilsonPercival** [comment] 2024-01-10 01:20
Can not reproduce.

**Comment by desertcucco** [comment] 2024-01-10 01:43
> This might explain what happened in my project :) #7687

Yep, looks like the exact same thing. Can go easily unnoticed so hopefully the team checks this out + watches the video and is able to find a fix!

**Comment by F3der1co** [comment] 2024-01-15 21:01
I just had broken collision with jump through platforms and just remembered reading about this here! I would have not figured this out without hours/days of search if it wasn't for this report, ty!

**Comment by DiegoScirra** [comment] 2024-01-16 13:43
Not able to reproduce this with the steps provided. We even have a Mac with Sonoma to try it out. Tried different ways to set the collision polygon vertexes (mouse movement, keyboard input, set collision box options and guess collision polygon option) and every time the values end up as expected.

@desertcucco

Can you include the platform information? Just to see if there is anything in there that might be helpful to try and reproduce this.

**Comment by desertcucco** [comment] 2024-01-16 15:36
@DiegoScirra I'm sorry, what do you mean by platform information? Want to make sure I'm getting you the right thing. Thanks!

**Comment by DiegoScirra** [comment] 2024-01-16 16:00
Go to **MENU -> About -> Platform information**

A dialog will show up with a bunch of information about your system, there is even a button to copy the whole thing to the clipboard so you can paste it here.

**Comment by desertcucco** [comment] 2024-01-16 16:02
@DiegoScirra

Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 120.0.6099.199
Browser engine: Chromium
Context: browser
Operating system: macOS 14.1.2
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 429 gb
Storage usage (approx): 629 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560X OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by desertcucco** [comment] 2024-01-20 02:54
@DiegoScirra For whatever reason, it seems to be functioning as intended in Safari... I can even switch back to Chrome and run a playtest, and as long as I don't open the collision editor while in Chrome, it won't bug out.

**Comment by desertcucco** [comment] 2024-01-25 15:56
@DiegoScirra @AshleyScirra Upon further testing, this issue also happens in Safari. A fix would be nice considering other people in this thread have had it happen to them and also I'm spending $100/yr or whatever.

**Comment by AshleyScirra** [comment] 2024-01-25 16:25
I can't reproduce this, and @DiegoScirra has said he can't reproduce it either. I tried this:

1. Open project
2. Edit PlayerBase object
3. Switch to collisions tool
4. Select bottom-left collision point, and using toolbar, change `8` to `7`
5. Close Animations Editor
6. Reopen Animations Editor
7. Select bottom-left collision point

It displays `7` as I last left it. There is no offset applied.

I'm afraid it is usually impossible to help unless we can reproduce the problem. It is important to identify the precise steps that reliably reproduce the problem. Often this includes specific details that are not actually mentioned in the original report.

It would also be worth checking if you have any browser extensions installed and try disabling them, as sometimes weird issues that the team can't reproduce are caused by browser extensions interfering with Construct.

**Comment by AshleyScirra** [comment] 2024-05-29 15:59
This issue has been marked 'can't reproduce' for a few months with no further response, so closing.

**Closed by AshleyScirra** 2024-05-29 15:59 UTC
Labels: can't reproduce
