### ISSUE TITLE
webgpu fails on all computers that have a dedicated graphics card from version r382 to r384.

### ISSUE THREAD

**Issue by skinkairewalker** [Scirra/Construct-bugs#7907] opened 2024-03-19 14:44 UTC
## Problem description

running examples in versions: r382 , r383 and r384 .
Most applications don't work or don't even run (black screen).

## Steps to reproduce

1. I accessed: [](https://editor.construct.net/r382/) to [](https://editor.construct.net/r384/)
2. I clicked explore examples
3. I selected the category: New
4. I RUN : fruit merger, simple synth, pixel data reader, layout transition, follow, cell linking and others. All the screen goes black or at most it only loads the background image.

## Observed result

screenshot : [r381](https://prnt.sc/vTipx19NJATV)
When running the functional version (r381) I get this console log: 

```
sw.js:506 [SW-Preview] Up to date
bootPreview.js:92 Registered service worker on https://preview.construct.net/
previewWindow.js:38 [C3 preview] Browser opened wrong size popup: wanted 320 x 180, got 298 x 82; resizing to compensate
sw.js:506 [SW-Preview] Up to date
runtime.js:25 [C3 runtime] Hosted in worker, rendering with WebGL 2 [ANGLE (Intel, Intel(R) UHD Graphics (0x00009A60) Direct3D11 vs_5_0 ps_5_0, D3D11)] (standard compositing)

```

screenshot : 
[r382](https://prnt.sc/_6W726EvbPqb)
[r383](https://prnt.sc/kqWDt2PWoe5j)
[r384](https://prnt.sc/P7kqaZwiOvCM)
When running the not-functional versions (r382 to r384) I get this console log: 

```
bootPreview.js:92 Registered service worker on https://preview.construct.net/
previewWindow.js:38 [C3 preview] Browser opened wrong size popup: wanted 320 x 180, got 298 x 82; resizing to compensate
sw.js:506 [SW-Preview] Up to date
runtime.js:26 [C3 runtime] Hosted in worker, rendering with WebGPU [intel/gen-12lp]
```

## Expected result
render the application.

## More details

**If I disable graphical acceleration (enabled by default) and restart the browser, it works again.**

**Affected browsers/platforms:** tested on Chrome(v122.0.6261.129 ) and Opera One(version: 108.0.5067.24) Chromium:122.0.6261.112 
**Both Windows 11 x64**

**First affected release:** worked in r381 but broke from r382 to r384

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r384 (beta)
Browser: Chrome 122.0.6261.129
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Language setting: pt-BR

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 165 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics (0x00009A60) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by WilsonPercival** [comment] 2024-03-19 14:53
Do I understand correctly, in `r381b` `WebGPU` worked, but in `r382b` `WebGPU` stopped working?

**Comment by AshleyScirra** [comment] 2024-03-19 16:15
I suspect this is a duplicate of #7906, where WebGPU is failing to render on some classes of hardware, so I'm closing this issue. It would be useful if you could answer the two questions I put in [this comment](https://github.com/Scirra/Construct-bugs/issues/7906#issuecomment-2007597752).

**Closed** 2024-03-19 16:15 UTC
Labels: duplicate

**Comment by skinkairewalker** [comment] 2024-03-21 20:10
It's this webgpu technology that is messed up, disabling it in the project itself, versions r382 to r384 work without the need to disable graphical acceleration in the browser

[webgpu disables in project ](https://prnt.sc/S4I5uEhuz0fU)
