### ISSUE TITLE
Runtime mousedown events not behaving as expected

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#7609] opened 2023-12-04 09:21 UTC
## Problem description

I'm setting a mousedown eventlistener like this
`runtime.addEventListener("mousedown", (ev) => console.log(ev.buttons));`

as per the Manual https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/iruntime#internalH1Link1

This works fine, except that if I hold rightclick and then use leftclick (or vice versa, and also with middle mouse button), the mousedown event does not trigger anymore.

## Attach a .c3p

[mousedown.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13544066/mousedown.c3p.zip)

## Steps to reproduce

1. Just leftclick -> ev.buttons = 1 (check console)
2. Just rightclick -> ev.buttons = 2
3. Hold rightclick, then leftclick -> event is not triggered

## Observed result

The mousedown event is not triggered at all.

## Expected result

The mousedown event is triggered, with ev.buttons = 3
You can try it here: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons#result

## More details
Pointerdown has the same issue

**Affected browsers/platforms:** Edge, Chrome, Firefox

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r369 (beta)
Browser: Edge 119.0.2151.93
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 139 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA Quadro K620 (0x000013BB) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment] 2023-12-04 11:31
Closing since it was already answered
https://www.construct.net/en/forum/construct-3/scripting-51/runtime-mousedown-mousebuttons-179786#forumPost1100430

**Comment by Wackytoaster** [comment] 2023-12-04 17:47
Reopening since Ashley suggested
https://www.construct.net/en/forum/construct-3/scripting-51/runtime-mousedown-mousebuttons-179786#forumPost1100452

`We're responsible for Construct's firing of mousedown events on runtime, so that part could be fixed.`

Would be awesome <3

**Comment by AshleyScirra** [comment] 2023-12-14 16:28
Updated the next beta to fire runtime `mousedown`, `mousemove` and `mouseup` events exactly as they do in the DOM.

Note this is not a duplicate of #6513, which refers to pointer events specifically (e.g. `pointerdown`), which work differently with simultaneous button presses, and Construct should already handle these events the same as they fire in the DOM.

**Closed by AshleyScirra** 2023-12-14 16:28 UTC
Labels: scripting
