### ISSUE TITLE
Update to the latest Beta message keeps popping up despite I tick notify me about just Stable

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-bugs#7006] opened 2023-05-06 09:02 UTC
Update to the latest Beta message keeps popping up despite I have set the settings to notify me about just stable releases.

![Image 001](https://user-images.githubusercontent.com/41597700/236613909-bc637f2b-c616-45c5-b7bc-c66f0b0443a1.png)
![Image 002](https://user-images.githubusercontent.com/41597700/236613912-3abb78b4-9522-420c-99e5-9198f3f2d18a.png)

## Steps to reproduce

1. Go to: (**Menu** ------ **Settings** ----- **Update**: ) then change "**Notify me updates about for**" To "**Stable releases**" 
2. Close the Editor
3. Open [the editor ](https://editor.construct.net/r339/)

## Observed result
Shows Notification message to update to the latest Beta:
![Image 002](https://user-images.githubusercontent.com/41597700/236614168-997c05b0-83d3-483e-8d64-8f18e6fa1e15.png)

## Expected result

Dont show any message related to Beta updates

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
R339

I cannot test if it's fixed on R340 because there are no higher beta updates so the message it will not pop up.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r339 (beta)
Browser: Chrome 112.0.5615.138
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 352 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by WilsonPercival** [comment] 2023-05-06 09:54
Duplicate https://github.com/Scirra/Construct-bugs/issues/6992

**Comment by Tarek200** [comment] 2023-05-06 10:36
Hoh Thanks Wilson I haven't even looked in closed bugs for this issue )) 


Whoa, I went through that bug report and what a combo, I didn't spect this will be by design lol.

This is insane!
Why do you guys keep forcing us to work on your terms??
I open hundreds of times a day the editor,  for a range of situations:
-Work on my Games.
-Empty project to (Debug/Test/Experiment) something.
-Help someone by creating examples.
-Etc...

Im constantly opening the editor and to have to click every time the notification "dont update" is really annoying, you shouldn't be forcing that message as doesn't make any sense. You already update the versions automatically when there is a new stable which forced us to work by targetting directly the version:
 "https://editor.construct.net/Version/"    To avoid force updates.

And now you trying to make us click that message every time we open the editor, this is really unnecessary and very annoying. I really dont understand you guys, doesn't make any sense the decisions you guys make sometimes.

I dont think we should have the need to ask for this to be fixed as it's a very obvious and annoying thing, you should have avoided it by default.

**Comment by AshleyScirra** [comment] 2023-05-09 13:58
Closing as duplicate of #6992

**Closed by AshleyScirra** 2023-05-09 13:58 UTC
Labels: duplicate
