### ISSUE TITLE
Minor incorrect code highlighting due to presence of ")" in a string

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#7484] opened 2023-10-23 21:11 UTC
## Problem description

Some minor incorrect code highlighting when there's a ")" present inside a string.
![image](https://github.com/Scirra/Construct-bugs/assets/31101309/d6ab6c70-1f84-4db6-9d3b-f44001445b3c)

## Attach a .c3p

[codehighlighting.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13079163/codehighlighting.c3p.zip)

## Steps to reproduce

Four cases with different results:
1. Highlight the first opening "{"
2. Highlight the first opening "(" after the if
3. Hightlight the closing ")" after the if
4. Highlight the closing "}"

## Observed result

1. The "{" is marked in red, and the corresponding closing "}" is not marked
2. The opening "(" is marked in green, but the corresponding closing ")" is not marked
3. The closing ")" is marked in red, but the corresponding opening "(" is not marked. Instead, the opening "{" is marked in red too.
4. Both the opening and closing "{}" are marked in green as they should be

## Expected result

The corresponding opening/closing brackets to be marked in green

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r363 (beta)
Browser: Chrome 118.0.5993.89
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 134 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4080 (0x00002704) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-10-24 16:06
This bug is in the CodeMirror text editor itself, not Construct - you can also reproduce it here: https://codemirror.net/5/mode/javascript/index.html

I think this is a fundamentally difficult thing to do because highlighting the right open bracket when you are at a close bracket means reverse-parsing JavaScript to get it right. A whole entire reverse parser for a full programming language for a highlighting feature probably isn't worth it. So it just does a dumb character search, including the contents of strings. (IIRC another similar issue was filed about this already, but I can't find it.) Having said that, VS Code seems to get it right - and you can use VS Code as an external editor with a folder project if you want more advanced features.

Either way it's not something we can easily fix so closing.

**Closed by AshleyScirra** 2023-10-24 16:06 UTC
Labels: wontfix, external, scripting

**Comment by WilsonPercival** [comment] 2023-10-24 16:20
@AshleyScirra Isn't this what you were trying to find? 🙃 https://github.com/Scirra/Construct-bugs/issues/5796

**Comment by AshleyScirra** [comment] 2023-10-25 10:40
Yep, I think that was the one.
