### ISSUE TITLE
Crash when searching for file references.

### ISSUE THREAD

**Issue by Everade** [Scirra/Construct-bugs#7711] opened 2024-01-03 20:47 UTC
## Problem description
C3 crashes when trying to search for references of a project file.
Was able to reproduce this with any C3 example project as well.

## Attach a .c3p
https://editor.construct.net/#open=cave-bridge

## Steps to reproduce
1. Right click any project file ( for example Fireflies sprite) and select "Find all references..."
2. Crash

## Observed result
"Oops! Something went wrong." - crash

## Expected result
No crash

## More details
**Affected browsers/platforms:** Chrome
**First affected release:** r373 (beta)

## System details
<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'add') @ TypeError: Cannot read properties of undefined (reading 'add') at Ria (https://editor.construct.net/r373/main.js:420:227) at new lr.g.J.Table.qAc (https://editor.construct.net/r373/main.js:1881:173) at pa.j (https://editor.construct.net/r373/main.js:1131:44) at CCG.Fi (https://editor.construct.net/r373/main.js:416:268) at window.FF.bm (https://editor.construct.net/r373/components/bars/findReferencesBar/findReferencesBar.js:15:379) at Avb (https://editor.construct.net/r373/components/bars/findReferencesBar/findReferencesBar.js:4:164) at Bvb (https://editor.construct.net/r373/components/bars/findReferencesBar/findReferencesBar.js:7:1)
Stack: TypeError: Cannot read properties of undefined (reading 'add') at Ria (https://editor.construct.net/r373/main.js:420:227) at new lr.g.J.Table.qAc (https://editor.construct.net/r373/main.js:1881:173) at pa.j (https://editor.construct.net/r373/main.js:1131:44) at CCG.Fi (https://editor.construct.net/r373/main.js:416:268) at window.FF.bm (https://editor.construct.net/r373/components/bars/findReferencesBar/findReferencesBar.js:15:379) at Avb (https://editor.construct.net/r373/components/bars/findReferencesBar/findReferencesBar.js:4:164) at Bvb (https://editor.construct.net/r373/components/bars/findReferencesBar/findReferencesBar.js:7:1)
Construct version: r373
URL: https://editor.construct.net/r373/
Date: Wed Jan 03 2024 21:41:39 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 69.8 s

Platform information
Product: Construct 3 r373 (beta)
Browser: Chrome 120.0.6099.130
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3090 (0x00002204) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex</details>

**Comment by WilsonPercival** [comment] 2024-01-03 22:21
Can not reproduce.

**Comment by DiegoScirra** [comment] 2024-01-03 22:26
Duplicate of #7708. A regression was introduced in the latest beta which affects every place where there is a table showing icons.

**Closed by DiegoScirra** 2024-01-03 22:26 UTC
Labels: duplicate

**Comment by I-N-C-O-G-N-I-T-O** [comment] 2024-01-03 22:41
> Can not reproduce.

Crashes for me. Either by using search or find all reference. Chrome/Safari on Mac.
