### ISSUE TITLE
Cloning sprite fails on latest beta. Cloning a tiled background causes critical error/crash.

### ISSUE THREAD

**Issue by Smaadz** [Scirra/Construct-bugs#8342] opened 2024-12-01 18:09 UTC
## Problem description

Cloning a sprite fails in the editor.
Cloning a tiled background crashes the editor.
Possibly more but haven't tested it...

## Attach a .c3p

[sprite and tilemap.zip](https://github.com/user-attachments/files/17969883/sprite.and.tilemap.zip)

## Steps to reproduce

1. Create a sprite, try to clone it, says it cant...
2. Create a Tiled Background, try to clone it, screen goes red and crashes

## Observed result

Fail/Crash

## Expected result

Not fail/Not crash

## More details

---

**Affected browsers/platforms:** 

Am using chrome. Windows 10

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'eka') @ TypeError: Cannot read properties of null (reading 'eka') at d.Ph (https://editor.construct.net/r417/projectResources.js:852:9) at d.Ri (https://editor.construct.net/r417/projectResources.js:652:6) at d.Ri (https://editor.construct.net/r417/projectResources.js:850:319) at d.Ri (https://editor.construct.net/r417/projectResources.js:768:203) at d.Ca (https://editor.construct.net/r417/projectResources.js:651:396) at d.Ca (https://editor.construct.net/r417/projectResources.js:748:219) at https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:44:65 at fkb (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:44:172) at window.qn.ywb (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:149:510) at Hmb.Uc (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:285:502)
Stack: TypeError: Cannot read properties of null (reading 'eka') at d.Ph (https://editor.construct.net/r417/projectResources.js:852:9) at d.Ri (https://editor.construct.net/r417/projectResources.js:652:6) at d.Ri (https://editor.construct.net/r417/projectResources.js:850:319) at d.Ri (https://editor.construct.net/r417/projectResources.js:768:203) at d.Ca (https://editor.construct.net/r417/projectResources.js:651:396) at d.Ca (https://editor.construct.net/r417/projectResources.js:748:219) at https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:44:65 at fkb (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:44:172) at window.qn.ywb (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:149:510) at Hmb.Uc (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:285:502)
Construct version: r417
URL: https://editor.construct.net/r417/
Date: Sun Dec 01 2024 18:07:26 GMT+0000 (Greenwich Mean Time)
Uptime: 296.8 s

Platform information
Product: Construct 3 r417 (beta)
Browser: Chrome 131.0.6778.86
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002484) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by DiegoScirra** [comment] 2024-12-02 11:05
Duplicate of #8338. Will be fixed in the next beta.

**Closed by DiegoScirra** 2024-12-02 11:05 UTC
Labels: duplicate
