### ISSUE TITLE
Steamworks addon & example project: showing overlay does nothing and freezes the app window

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#8328] opened 2024-11-20 13:33 UTC
## Problem description

Steamworks addon & example project: 
after exporting the project to Webview 2,
showing overlay does nothing and freezes the app window

(the other features such as displaying steam account infos are working)

## Attach a .c3p

[SteamPluginTest_c3p.zip](https://github.com/user-attachments/files/17831321/steam-test-project_.zip)

this is just the exact example project you provided here: https://www.construct.net/en/make-games/addons/1105/steamworks

**Here is the export to try quicker :** 
[SteamPluginTest r417.zip](https://github.com/user-attachments/files/17933328/SteamPluginTest_Export.zip)
[SteamPluginTest r418.zip](https://github.com/user-attachments/files/17994642/SteamPluginTest.r418.zip)

## Steps to reproduce

1. Open the Steamworks example project without changing anything
2. Export to Windows Webview 2
3. Open the export
4. Press Show Overlay button

![image](https://github.com/user-attachments/assets/7498bdb7-6a32-4d6e-ab17-f66eb8feb9b2)

## Observed result

Nothing happens (the overlay isn't shown)
The window is frozen (impossible to move or close, unless force closing using Task manager)
No error are showed in the console

## Expected result

The steam overlay is shown
The window isn't frozen

## More details

Tried on last stable r416, on Windows 10, with worker mode set to on and off

**MORE INFOS:** I asked about it on the Discord: it looks like it never works on some system (like mine), and on other computers, it seem to work but not every time, they still get the same freeze sometimes

**Comment by AshleyScirra** [comment] 2024-11-21 11:54
It works fine for me. Are you definitely using the latest addon version v1.2?

I have no idea what could be wrong on other systems. Unfortunately this makes it infeasible to investigate unless we can identify a way to reliably reproduce it. Can you identify any information about affected systems, or find anything to change on a system that does work that causes it to stop working?

**Comment by F3der1co** [comment] 2024-11-21 12:29
I can reproduce the freeze/broken state with the following steps:
- run app
- open steam overlay
- change focus away from window to different app or desktop
- now focus steamPluginTest again
- It now is in a weird broken state: steam overlay is visible on top but is not clickable, but html buttons from c3 are clickable. Window cannot be closed using the "X" in the window header, but can be closed from the task bar.

Note the window cannot be closed via the "X" button if the steam overlay is opened regardless of the steps

**Comment by OverboyDev** [comment] 2024-11-21 12:35
Yes i'm using last addon version 1.2:
I'm on Win10, with a Nvidia 1070 gtx, 60Hz display

With "Enable Overlay = true" : as i describe in the report, it freeze the app window. By that I mean it's impossible to move or close the window (except if i force quit it with task manager). However it doesn't freeze the running C3 game, i can still press the achievement buttons for example. But the window is frozen

With "Enable Overlay = false" : it pop ups seperate Steam windows, but it doesn't free the game window

**Comment by OverboyDev** [comment] 2024-11-21 12:45
The report from Federico is interesting, it looks like there is 2 issues:

1 issue affecting everyone : when the Steam Overlay is shown or supposed to be shown it's impossible to move and close the Game Window (with the "x" button")

1 issue affecting only some windows users: the overlay isn't shown at all, but it's still impossible to move and close the Game Window. The additional issue here is that as there aren't any way to "close" the invisible Steam Overlay, it's also impossible to close the game window, It makes issue 1 even worse

**Comment by OverboyDev** [comment] 2024-11-26 20:22
Tried on 3 different computers, the same issue happens in all of them.
All of them are Win10, Nvidia, 60hz

**Comment by AndreYin** [comment] 2024-11-26 20:46
Same thing happening here. Here's my step-by-step:

1. Exported using r416 stable and Steamworks plugin 1.3.0 (SDK v2)
2. Opened up Steam and clicked "Add new game" on the bottom left, then "Add a non-Steam game" (alternatively, if you have a game on Steam, you can just go to it's folder, delete everything and rename .exe to SteamPluginTest.exe)
3. Run the game and click the "Show overlay" button

Even though the game shows the overlay, the app unfocus instantly and opens the friends list in the actual Steam application. 
When you try to go back into the game, nothing is clickable. All clicks are passing through the overlay, into the actual game. 

Here's a video showcasing it:

https://streamable.com/5tfurp

**Comment by casgabe** [comment] 2024-11-26 23:18
I have the same problem. The window freezes and I can't interact or close it. Steam seems to work with the plugin, like unlocking achievements, it makes a sound but it doesn't show the overlay in the corner of the screen.

Showcasing it:
[https://streamable.com/1i4ovx](url)

(Win10, AMD RX6600)

**Comment by shotgunanaconda** [comment] 2024-11-27 15:41
I too have this issue. Window freezes and no steam overlay and cant do anything until app is forced closed.
Too me this makes WebView2 an absolute no-go for Steam games (the nr1 most important game store), even if it's 10% of your audience having this issue it's a big chunk of your sales and potential audience. 

Windows 10, latest c3 stable.

**Comment by Jase0000** [comment] 2024-11-29 10:05
I tested this and exactly the same as @shotgunanaconda , both with running directly, or adding into steam and running.

**Comment by AshleyScirra** [comment] 2024-12-02 15:08
I am planning to investigate this but I would warn you such issues can be extremely difficult to deal with - it could be some graphics driver problem, or an issue with Steam itself, or be something that is difficult to track down and so takes a long time to deal with.

In the mean time I would advise to uncheck "Enable overlay" - then Steam uses fallbacks like showing the actual Steam UI instead of their in-game overlay. Even with our workaround to show the in-game overlay, things like achievement notification popups can't be shown, because of the limitations of having to use [such a complicated workaround for problems with the Steam Overlay](https://www.construct.net/en/blogs/ashleys-blog-2/trying-show-steam-overlay-1861) - but Steam's fallback works for those and so the notification will appear. So I do wonder if it's worth dealing with such complicated workarounds if they don't even fully support all the overlay features - maybe it's just better to rely on Steam's fallback anyway.

**Comment by AshleyScirra** [comment] 2024-12-02 16:47
I can reproduce the issue with changing focus as described in [this comment](https://github.com/Scirra/Construct-bugs/issues/8328#issuecomment-2491009695). It is extremely difficult to figure out why it does not work - it seems to be that the Steam Overlay is interfering with the way the app works. I don't know what it is doing as it's all undocumented and internal to Steam, and so all I can do is guess what might help. I tried a few things which didn't work before finding that WebView2 has an alternate rendering mode which seems to work better and fixes that focus problem. Perhaps it helps with other cases too. I've updated the next beta to use that mode, and I think we'll have to do more testing to identify what difference that has made to other cases. Hopefully there is a positive result, because if that doesn't work, there may not be any other good options...

**Comment by AshleyScirra** [comment] 2024-12-03 14:39
The Windows WebView2 export has been updated in r418 - please try again there and let me know how it works out.

**Comment by OverboyDev** [comment] 2024-12-03 14:43
I'm still getting the exact same issue when exporting the default project using r418, here is the exact exported projet in case it helps: 
[SteamPluginTest r418.zip](https://github.com/user-attachments/files/17994642/SteamPluginTest.r418.zip)

**Comment by shotgunanaconda** [comment] 2024-12-05 20:26
I tried the new version. Sadly not fixed.

a) Run .exe with steam running the background but not added to the library. Log says overlay is open, and to be honest it's acting like it is. I cant close or interactive with the application window at all. Unlike before i can now press shift+tab to close the overlay as it was actually open. So it's calling it, but not drawing anything. 

b) Add game to steam library and run it. Now this is weird. I press the overlay button and it minimizes the game and opens my friendlist and the steam exe but NOT the overlay. It doesnt work pressing shift+tab to go back. I have to click on the game in the taskbar (the game is still inactive) and then press shift+tab. So it's calling steam but not the overlay.

:/

**Comment by AshleyScirra** [comment] 2024-12-06 13:14
With the [export from this comment](https://github.com/Scirra/Construct-bugs/issues/8328#issuecomment-2514766683), I can't reproduce any issue with running the app independently. If I add it as a non-Steam game, it does weirdly show both the Steam window *and* the Steam overlay when showing the overlay, but otherwise it seems to work OK. I can't reproduce any of the issues around the overlay not drawing, the window freezing, or the overlay getting stuck showing with the updated export.

I'm afraid I think this is the end of the road for the Steam overlay workarounds. If I can't reproduce the issue, that often is a dead-end by itself; further, even when I can reproduce an issue, the Steam Overlay is a black box - it appears to do complicated external alterations to the app which are all undocumented. I have no idea what it's doing nor what might fix it. The only relevant features in the Steamworks API are detecting when the overlay appears and disappears, and requesting to show it. There is no way to customize it. There isn't even any way to request to hide it, which limits some workaround options. The API documentation basically says if the app renders with D3D11 it should work, and browsers do render with D3D11, but it doesn't work - so even the limitations seem to be undocumented. All I can do is essentially try random things in the vague hope that it helps, and unsurprisingly, that has not led to a solution. In particular my latest effort ran in to [a WebView2 bug](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4968) that breaks gamepad and pointer lock, which is bad enough that we can't use that approach until that is fixed. *Even if* we got this particular workaround working successfully, it is still fundamentally limited by other limitations in the Steam Overlay, such as its incorrect use of alpha that mean it can't be shown transparently - that means notification popups like "Achievement unlocked" cannot be shown. So even the best case scenario if a lot of complicated stuff can be fixed will still leave it only partially supported.

The only good solution is that Valve fix the overlay so it works for these cases. It would be good if everyone affected asks Valve for this, as the more people who ask, the more they'll see it's important.

Meanwhile:
- When the Steam in-game overlay is not supported, Steam uses fallbacks, such as showing the Steam window itself instead of an in-game overlay. This all seems to work fine. It also means things like "Achievement unlocked" notifications work, as it appears to show that in a separate window on top (if only the entire overlay worked like that!)
- Supporting the Steam in-game overlay is not a publishing requirement for Steam.
- The Steam overlay works fine on the Steam Deck - again it uses a different approach drawing on top of the game, rather than intrusively modifying the game application itself. (If only the Windows overlay worked like that!)
- The rest of the Steam integration works fine and appears unaffected.

It's also possible future updates for WebView2 will enable a better workaround: support for [rendering WebView2 to a texture](https://github.com/MicrosoftEdge/WebView2Feedback/issues/20) should mean it renders the same way as other typical desktop games, and so support the Steam in-game overlay. So this might become possible in future. However this won't cover macOS WKWebView or Linux CEF as they use different technologies - again the best solution is for Valve to properly support it.

I'd also point out neither NW.js nor Electron actually support the Steam in-game overlay out-of-the-box: both also have to use workarounds, which work for the time being, but depend on things like Chromium command-line flags that are not officially supported by Google - so those workarounds could stop working too. The only way to guarantee it works in future is for Valve to update the in-game overlay to properly support them.

Given Steam has fallbacks, the rest of the integration is working fine, there are a lot of benefits to having our own desktop exporter technology, and there may be new workarounds in future, I don't think this alone merits altering our plans to move over to our own desktop exporters and ultimately phase out NW.js. So it's a shame we can't support this for now - I really have spent a great deal of time on this and [already gone to great lengths](https://www.construct.net/en/blogs/ashleys-blog-2/trying-show-steam-overlay-1861) to get it even to partially work at all - but I don't think there is any good way forward. I've released a v1.3.1 update for the [Steamworks addon](https://www.construct.net/en/make-games/addons/1105/steamworks) that removes the overlay workaround, so it will always use the fallbacks instead. I will keep an eye on any changes that make new workarounds possible and experiment with them in future. However for now I don't think we can take this any further, so closing this issue. If you really want support, again - please contact Valve! It's their software and they are the only ones who can actually make it work well.

**Closed by AshleyScirra** 2024-12-06 13:14 UTC
Labels: difficult, need info

**Comment by OverboyDev** [comment] 2024-12-06 14:36
I see, I hope Valve will fix this then.
Could you please write a feature request post about that the official Steam place for such reports?
https://steamcommunity.com/discussions/forum/10/

As a developer of a popular game engine, it would be easier for you to convince them + you already know everything you tried and what is currently lacking. I think a lot of C3 users would comment and +1 your thread.

**Comment by AshleyScirra** [comment] 2024-12-06 16:19
I've already tried privately, but I think it's a good idea to make a public post where others can show their support. I made a post here: https://steamcommunity.com/discussions/forum/10/591756872987476379/
