### ISSUE TITLE
iOS Export - error with pods-release.xcconfig & pods-debug.xcconfig

### ISSUE THREAD

**Issue by Telecs** [Scirra/Construct-bugs#7400] opened 2023-09-18 18:04 UTC
## Problem description

When I export any project to Xcode, I can neither preview nor build my project in Xcode, due to the following error:

> /Users/XXX/Downloads/Alchemist Template.ios.project/pods-debug.xcconfig:2:1 could not find included file 'Pods/Target Support Files/Pods-Alchemist Template/pods-debug.xcconfig' in search paths

## Attach a .c3p

[Link to .c3p (the problem arise with any)](https://pestorosso.com/share/ios_export_fail.c3p)

## Steps to reproduce

1. Export project to iOS / Xcode project
2. Try to run / archive project in Xcode

## Observed result

The preview & build are not working.

Since R258, the following line has been added to pods-release.xcconfig and its equivalent to pods-debug.xcconfig:

`#include "Pods/Target Support Files/Pods-Alchemist Template/Pods-Alchemist Template.release.xcconfig"
`

If these lines are deleted (which are automatically generated by Apache), the project works fine.

## Expected result

No error, obviously.

I don't know if you have any control over what Apache is doing, but simply deleting the lines of code in pods-release.xcconfig & pods-debug.xcconfig would at least avoid having to delete them manually with each new build.

**First affected release:** R258. It was working fine with previous stable release

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 116.0.5845.188
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 556 gb
Storage usage (approx): 1.2 gb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by therealPaulPlay** [comment] 2023-09-18 18:09
Can confirm, pods aren't generating for me either. I always have to manually install the pods by running cocoapods (pod install). Even if I'm not using any plugin, I have to run pod install because of this dependency

**Comment by AshleyScirra** [comment] 2023-09-20 15:41
This sounds related to #6934 - sometimes you have to run `pod install` for the exported Xcode project to work, and due to some weird Cordova/Xcode problems we can't make the build service run it for you. Does running `pod install` solve the problem?

**Comment by therealPaulPlay** [comment] 2023-09-20 20:44
It does as it generates these support files, but for me at least, I have to do it with empty projects as well, so not even the built-in browser object added to the project or the google ad plugin or anything like that. So I‘m not sure why the dependency is there in the first place

**Comment by AshleyScirra** [comment] 2023-09-26 16:14
I can't reproduce this. I opened the provided project in r360, exported it as an Xcode project, opened it, adjusted the signing setting (which is always necessary), and ran it on an attached iPhone device. It built and ran just fine. There was no need to adjust any further settings. Perhaps this is an issue with your particular Xcode setup or system configuration?

**Comment by therealPaulPlay** [comment] 2023-09-26 16:39
I‘m using an apple silicon mac. Could that be the issue? I‘ll quickly check whether I can replicate the issue with Telecs project.

**Comment by therealPaulPlay** [comment] 2023-09-26 16:45
So I've exported it using stable release 358, selected the xcode project export for ios 14+ with vibrate permission (as default, I think) and chose the simple minification setting. The xcode file I get includes a podfile (which should not be necessary in this case afaik cuz no pods should be installed) which leads to the error in xcode. I have attached my xcode file as well as the error screenshot here. Note that I am using Xcode 15.0 but can confirm that the issue has been a thing in xcode 14.X too. 
<img width="1022" alt="Bildschirmfoto 2023-09-26 um 18 45 13" src="https://github.com/Scirra/Construct-bugs/assets/80539587/f512000b-77de-49f4-a263-6ce2888a7bf7">
[Alchemist Template.ios.project.zip](https://github.com/Scirra/Construct-bugs/files/12730002/Alchemist.Template.ios.project.zip)

**Comment by therealPaulPlay** [comment] 2023-09-26 17:14
Interesting reply, this doesn‘t make much sense to me… The issue (at least from what I understood) is that there is a dependency in regular construct 3 Xcode exports that requires the pods folder which has not been generated. Unless using 3rd party plugins that break the pod install process on the build server for some reason, this issue should not exist, as the build server should handle the pods. 

Simply installing Cocoapods also does not fix the issue for me and the message that the pods have already been installed should not be related to you installing cocoapods. My only guess would be that you ran pod install or pod update before which has installed the pods or that the build service was successful this time.

**Comment by AshleyScirra** [comment] 2023-09-28 09:57
> I‘m using an apple silicon mac & chrome for apple silicon, newest version. Could that be the issue?

I also tested on an Apple silicon mac (M1).

> The issue (at least from what I understood) is that there is a dependency in regular construct 3 Xcode exports that requires the pods folder which has not been generated.

By default Construct projects don't require pods, and this appears to be what I see: a normal Construct project export works fine and doesn't need `pod install`.

Sometimes your project will need pods, but that depends on the features used in your project. Usually the cause is third-party addons, but IIRC, the Browser object requires pods as it uses `cordova-plugin-inappbrowser` which for some reason creates an empty pod file: https://github.com/apache/cordova-ios/issues/1365

I suspect the confusion here is it's not true that any project reproduces the problem, but since use of the Browser object is relatively common and is known to cause a problem with an empty pod file due to a Cordova bug, that is probably what is causing the problem. That also seems to be what happened with *Alchemist Template.ios.project.zip* as it includes the broken empty Podfile. However that comes down to a Cordova issue. In other cases usually you do have to run `pod install` if the project really does use pods, which depends on the specific plugins your project uses (usually involving third-party plugins); I've updated [this tutorial](https://www.construct.net/en/tutorials/ios-application-development-and-publishing-with-xcode-25) to mention that `pod install` may sometimes be required.

It's difficult to test this any further as I don't have a .c3p project that reproduces the problem, but I strongly suspect that explains the situation, so closing.

**Closed by AshleyScirra** 2023-09-28 09:57 UTC
Labels: can't reproduce, iOS

**Comment by therealPaulPlay** [comment] 2023-09-28 10:41
Hey Ashley,
Sorry for not making myself clear, but I actually mean an empty project. So, no Browser object or anything like that. Still, I get a podfile in my construct export and will need to run `pod install` to solve dependency issues (that fixes it for me, you mentioned it breaks the project but for me it actually fixes the issues). 
Here is the zip that I get directly from construct from a c3p (also attached) that is completely empty. 
[Empty project.ios.project.zip](https://github.com/Scirra/Construct-bugs/files/12748485/Empty.project.ios.project.zip)
[Empty project.zip](https://github.com/Scirra/Construct-bugs/files/12748486/Empty.project.zip)

**Comment by therealPaulPlay** [comment] 2023-09-28 10:46
Could that be because I have the behavior "radial progress" (addon) installed?
