### ISSUE TITLE
Closing CustomAction dialog box with "Enter" while the Name field is active crashes C3

### ISSUE THREAD

**Issue by Qba-Sproud** [Scirra/Construct-bugs#7344] opened 2023-08-30 04:51 UTC
## Problem description

Closing the CustomAction dialog window by using "Enter" on keyboard while focused on the Name field will crash the C3 Editor webpage with a STATUS_BREAKPOINT error message.

## Attach a .c3p

[CustomActionRenameCrash.zip](https://github.com/Scirra/Construct-bugs/files/12471555/CustomActionRenameCrash.zip)

(rename from .zip to .c3p)

## Steps to reproduce

1. Open provided .c3p
2. Open Event Sheet
3. Add Custom Action
4. Pick TiledBackground
5. Click on the Name field
6. Press "Enter" on keyboard to close dialog box

## Observed result

C3 webpage crashes with a STATUS_BREAKPOINT error message.

## Expected result

Dialog box is closed and C3 continues to operate.

## More details

Happens in Google Chrome Version 116.0.5845.141 (Official Build) (64-bit), but works correctly in Waterfox G5.1.10 (64-bit)

**Affected browsers/platforms:** Google Chrome Version 116.0.5845.141 (Official Build) (64-bit)

**First affected release:** Happening as far back as R350 stable

## System details

<details><summary>View details</summary>

Product: Construct 3 r350 (stable)
Browser: Chrome 116.0.5845.141
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 1.8 gb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment] 2023-08-30 08:05
Duplicate https://github.com/Scirra/Construct-bugs/issues/7321

**Comment by AshleyScirra** [comment] 2023-09-01 10:29
Duplicate of #7321.

**Closed by AshleyScirra** 2023-09-01 10:29 UTC
Labels: external
