### ISSUE TITLE
Editor freezes when trying to open a timeline while another (child) timeline is open and in edit mode

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#8279] opened 2024-10-10 03:51 UTC
## Problem description

Editor freezes when trying to open a timeline while another (child) timeline is open and in edit mode

## Attach a .c3p
[test tl.zip](https://github.com/user-attachments/files/17304467/test.tl.zip)

## Steps to reproduce

1. Open the timeline window
2. Open timeline "1X"
3. Click edit icon (move the red marker a few seconds)
4. In the project window, double click timeline "1"

## Observed result
Editor freeze, no response, not even a console error

## Expected result
Plays normally (playing the individual timelines works fine)

## More details

**Affected browsers/platforms:** Chrome app (latest 129.0.6668.101 (Official Build) (64-bit))

**Comment by DiegoScirra** [comment] 2024-10-10 16:55
Duplicate of #8276

Already fixed in **r410**

**Closed by DiegoScirra** 2024-10-10 16:55 UTC
Labels: duplicate
