### ISSUE TITLE
Constructor method not fired with subclassed non-world instances

### ISSUE THREAD

**Issue by EdwinMorizet** [Scirra/Construct-bugs#7179] opened 2023-07-07 14:48 UTC
## Problem description

Constructor method are not fired at instantiation of the IInstance.

It's working for the IWorldInstance.

## Attach a .c3p

[BugConstructor.zip](https://github.com/Scirra/Construct-bugs/files/11983170/BugConstructor.zip)

## Steps to reproduce

1. subclass a Dictionary or a JSON instance
2. log inside the constructor method

## Observed result

no log

## Expected result

log

## More details

Work on 327.2
Don't work on 344.2

**Comment by AshleyScirra** [comment] 2023-07-07 15:38
I think this is a regression in r341 caused by the fix for #6997. It should be fixed in the next beta. Note however that the only problem is the Dictionary script interface is lazy-created - as soon as you first use it (e.g. by calling `runtime.objects.Dictionnary.getFirstInstance()`), the class is created and the constructor is run.

**Closed by AshleyScirra** 2023-07-07 15:38 UTC
Labels: scripting
