### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by baezipsa** [Scirra/Construct-bugs#7546] opened 2023-11-14 05:49 UTC
## Problem description
this source not changed 1 year
before I can build IOS and can testflight. but someday can't build 

android also sometimes can sometimes can't build.

Error report information
Type: unhandled exception
File: https://editor.construct.net/r366/main.js, line 1917, col 242
Message: Uncaught TypeError: d.getModifierState is not a function
Stack: TypeError: d.getModifierState is not a function at rr.g.li.jMa (https://editor.construct.net/r366/main.js:1917:242) at aj.g.cwc.yd (https://editor.construct.net/r366/main.js:1919:416) at https://editor.construct.net/r366/main.js:1919:139
Construct version: r366
URL: https://editor.construct.net/r366/
Date: Tue Nov 14 2023 14:44:33 GMT+0900 (한국 표준시)
Uptime: 628 s

Platform information
Product: Construct 3 r366 (beta)
[touchtouchgame.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13344995/touchtouchgame.c3p.zip)

Browser: Chrome 119.0.6045.123
Browser engine: Chromium
Context: browser
Operating system: macOS 14.0.0
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment] 2023-11-14 05:59
Duplicate https://github.com/Scirra/Construct-bugs/issues/7529

**Comment by AshleyScirra** [comment] 2023-11-14 12:38
Closing as looks like a duplicate of #7529. As noted there we cannot reproduce this and currently have no idea how it could possibly happen, and the best thing to do is try disabling browser extensions, which are frequently the cause of such problems. If you find out which browser extension causes this, it would be useful to let us know, so we can either work around it if feasible or at least advise other users accordingly.

**Closed by AshleyScirra** 2023-11-14 12:38 UTC
