### ISSUE TITLE
There is no get attribute by name expression in HTML.Element

### ISSUE THREAD

**Issue by XIMIKATIK** [Scirra/Construct-bugs#7442] opened 2023-10-05 13:11 UTC
Why can I change the html attribute of an element by name in the plugin actions, but I can't get the attribute value when clicking on the html?

`<button id="button_ofcanvas" class="btn" content="filename" sub="no">Button</button>`
How do I get the content and sub attribute when I click on a button?
I am missing the expression HTML.TargetAttribute("name") in the likeness of HTML.TargetID and HTML.TargetClass

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2023-10-05 13:45
This is not a bug report, so closing. For general questions please post to the forum, or if you have a suggestion then [see this thread](https://www.construct.net/en/forum/construct-3/general-discussion-7/announcing-new-construct-161682).

**Closed by AshleyScirra** 2023-10-05 13:45 UTC
Labels: not a bug

**Comment by XIMIKATIK** [comment] 2023-10-05 20:47
> This is not a bug report, so closing. For general questions please post to the forum, or if you have a suggestion then [see this thread](https://www.construct.net/en/forum/construct-3/general-discussion-7/announcing-new-construct-161682).

How can I make a plugin, add an attribute change action by name, and not add a function to read this attribute? it feels like this is not a plugin, but a flaw just to write news on the site that HTML appeared in C3, but in real use the plugin does not have standard functions. Now I have to go to the site to leave a request, wait until they vote for it and you decide to add this feature, in a year or two... or maybe just don't pay attention to it.
