### ISSUE TITLE
Turrets of the same family target themselves

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7696] opened 2023-12-25 12:56 UTC
## Problem description

I have a family with Turret behavior. I set member 1 to target 2 and 2 to target 1 (using an overridden family action).
Now member 1 targets themselves, and 2 target themselves.
This doesn't happen if each type has its own Turret, and they do not belong to the same family.

## Attach a .c3p

[test target.zip](https://github.com/Scirra/Construct-bugs/files/13766085/test.target.zip)

## Steps to reproduce

1. Run preview

## Observed result
1. Blue target themselves instead of Red.
2. Red target themselves instead of Blue.
3. Yellow and Pink work correctly.

## Expected result

Blue shouldn't target itself. Same for Red.

**Comment by Alaadel** [comment] 2023-12-29 18:29
It seems this is the same as #5323.

> So "S1: add target S2" actually modifies the family turret behavior, and so all objects in the family - both S1 and S2 - will target S2. The other disabled action will work the same, so everything will end up targeting everything. This is currently by design.
So basically "add target" is kinda global action (like Physic set gravity?) which applies to the whole family. I wonder why? What if I want to have both objects in family but target each other without targeting themselves?

For example, my strategy game has a Unit family, which has 2 objects; Ally and Enemy. The targeting code is the same, so to keep things modular, I tried using families but it didn't work. Now I have to add more unit types and have to rewrite a good part of the targeting code for each unit because each unit is using its own Turret (no family turret).

Is there a cleaner way to do this?

**Comment by AshleyScirra** [comment] 2024-01-03 16:15
Closing as a duplicate of #5323 - targets are saved at the level of object type/family, so everything with the same behavior shares the same target list. It's just the way it's always worked. I guess we could change it, but it would be tricky to do in a backwards-compatible way. For proposals to change the way existing features work, file a feature suggestion instead.

**Closed by AshleyScirra** 2024-01-03 16:15 UTC
Labels: duplicate
