### ISSUE TITLE
C3 crashes with Aw Snap if you put category for function "Save and load"

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7360] opened 2023-09-01 20:44 UTC
## Problem description

https://github.com/Scirra/Construct-bugs/assets/7268697/ba22c0c0-98d3-4b83-b284-38254ac18789

## Steps to reproduce

1. start new project
2. make a function with category Save and load

## Observed result

Crashes but not with 100% repo. Crashed 3 out of 4 times for me.

## More details

**Affected browsers/platforms:** Chrome on W10

**First affected release:** r350

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 116.0.5845.140
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 1006 gb
Storage usage (approx): 1.9 gb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment] 2023-09-01 20:57
Duplicate https://github.com/Scirra/Construct-bugs/issues/7321

**Comment by JeFawk** [comment] 2023-09-01 22:06
> Duplicate #7321

I don't think this is a duplicate, I got different repo steps leading to a memory crash (?)

**Comment by WilsonPercival** [comment] 2023-09-01 23:05
@JeFawk 
<img width="899" alt="Untitled" src="https://github.com/Scirra/Construct-bugs/assets/91274932/8f6d3d04-a799-4e02-bc66-cd751f42a7ca">

**Comment by AshleyScirra** [comment] 2023-09-04 12:16
Very likely a duplicate of #7321. Test in Chrome v117+ to confirm.

**Closed by AshleyScirra** 2023-09-04 12:16 UTC
Labels: duplicate
