### ISSUE TITLE
Creating dynamic layer with recreate initial objects and assigning trackid results in timeline error

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#8243] opened 2024-09-22 13:54 UTC
## Problem description

I am trying to make a layout for each cutscene I have. Then I will add them in the game using the Create Layer - Recreate initial objects, coupled with the timeline controller. In this example I am creating 3 layers, destroying them, and then creating them again. The 2nd time they are created again, I get the following error in the console: 

trackState.js:7 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'GetIndex')
    at Track.SetInstance (trackState.js:7:512)
    at Timeline.SetTrackInstance (timelineState.js:34:385)
    at TimelineInstance._SetTimelineInstanceObjects (runtime.js:6:375)
    at TimelineInstance._PlayTimeline (runtime.js:10:367)
    at TimelineInstance.PlayTimeline (runtime.js:21:85)
    at EventBlock._RunActions_ReturnValue (eventBlock.js:27:430)
    at EventBlock._ResumeActionsAndSubEvents (eventBlock.js:28:545)
    at ScheduledWait._Run (scheduledWait.js:9:13)
    at EventSheetManager.RunScheduledWaits (eventSheetManager.js:24:96)
    at C3Runtime.Step_BeforePreTick (runtime.js:92:398)

Sometimes creating them again works, sometimes it doesn't.
I recorded it here https://streamable.com/og8gu8
Please be aware that this might get automatically deleted in 30 days or so.

## Attach a .c3p
[Creating Dynamic Layers With Their Objects And Timelines.c3p.zip](https://github.com/user-attachments/files/17090047/Creating.Dynamic.Layers.With.Their.Objects.And.Timelines.c3p.zip)

You can also find it here: https://github.com/JeFawk/CreateDynamicLayersWithTheirObjectsAndTimelines-C3Module-Code

## Steps to reproduce

Run the project following the steps in the video or the following:
1. Run project, press the 4 buttons on the bottom, from left to right: Create layer 1, 2, 3. Wait for the timeline animation to finish and press the 4th button to destroy the layers.
2. Press the first button again

## Observed result

It seems that sometimes the timeline won't work, and it throws an error in the console.

## Expected result

I expect the timeline to work at all times, not only 80% of the time, even under these conditions. If I actually am doing something wrong I expect the console to tell me about that.

## More details

**Affected browsers/platforms:** latest Chrome on Mac

**First affected release:** tried in r407 only

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r407 (stable)
Browser: Chrome 129.0.6668.58
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 7.1 gb (2.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, ANGLE Metal Renderer: Apple M1, Unspecified Version)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_render_shared_exponent
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by DiegoScirra** [comment] 2024-09-25 15:40
This falls into misuse of the feature.

When the first layer is created, all the things that are created are queued into the **TimelineController** so they can be assigned to the next timeline that starts playing, because there is a wait of 0.1 seconds in between everything is created and playback of the timeline, everything works correctly. If you just create the first layer, wait for the timeline to finish, destroy everything and repeat the process, everything works fine.

So far so good... problems start now.

When the other two layers are created, some of their instances are also queued into the **TimelineController**, the problem is that they  will never be used by any timeline before they are destroyed... the **TimelineController** doesn't know that though!

So what happens is that after everything is destroyed, those instances are still held in the **TimelineController** and it will try to use them when the next timeline starts playing, even if they are no longer valid, so the crash happens.

Off the top of my head I can't think what would be the better way to do what you are trying to do, but I think the **TimelineController** should definitely ignore invalid instances and I will add another action to clear the queue that is filled up each time you use **Set Instance**, so at least you can have manual control of that aspect.

Having said that, the primary use case of the feature is doing all the calls to **Set Instance** you need and only then calling **Play**. Also remembering that the **TimelineController** will try to start playback of as many timelines as it can given all the things that were queued. That means that if more instances than you were expecting where set with **Set Instance** before playback, other things you weren't expecting might start moving.

**Comment by DiegoScirra** [comment] 2024-09-25 18:06
From the next beta using **Set Instance** should be more resilient to improper use by just ignoring invalid instances. On top of that a new action, "Unset instances" will be available to explicitly clear the state set when calling **Set Instance**.

**Closed by DiegoScirra** 2024-09-25 18:06 UTC

**Comment by JeFawk** [comment] 2024-09-26 08:20
Very interesting, thank you for the fix and the explanation. Always good to learn more about how C3 works.
