### ISSUE TITLE
Crash when creating/viewing instance variables in R373 (all browsers & platforms)

### ISSUE THREAD

**Issue by ToadLobe** [Scirra/Construct-bugs#7709] opened 2024-01-03 20:17 UTC
## Problem description

Creating a new instance variable for any object type or editing existing instance variables causes a crash.

## Attach a .c3p

None required
## Steps to reproduce

1. Start a new project
2. Create any object
3. Add an instance variable

## Observed result

https://github.com/Scirra/Construct-bugs/assets/65856568/4109f038-1c83-4550-9f8f-60ff8cdbb06e

Crash
## Expected result

No crash
## More details

**Affected browsers/platforms:** Reproduced on both windows (chrome) and macOS (safari)

**First affected release:** R373

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: undefined is not an object (evaluating 'd.Gc.classList.add') @ Ria@https://editor.construct.net/r373/main.js:420:226 @https://editor.construct.net/r373/main.js:1881:176 @https://editor.construct.net/r373/main.js:1131:49 @https://editor.construct.net/r373/main.js:416:269 ic@https://editor.construct.net/r373/projectResources.js:3040:72 Lo@https://editor.construct.net/r373/projectResources.js:3040:504 rAb@https://editor.construct.net/r373/projectResources.js:3041:190 dispatchEvent@https://editor.construct.net/r373/main.js:1268:42 vv@https://editor.construct.net/r373/projectResources.js:48:279 Wa@https://editor.construct.net/r373/projectResources.js:656:253 jnb@https://editor.construct.net/r373/projectResources.js:707:15 @https://editor.construct.net/r373/projectResources.js:3043:28
Stack: Ria@https://editor.construct.net/r373/main.js:420:226 @https://editor.construct.net/r373/main.js:1881:176 @https://editor.construct.net/r373/main.js:1131:49 @https://editor.construct.net/r373/main.js:416:269 ic@https://editor.construct.net/r373/projectResources.js:3040:72 Lo@https://editor.construct.net/r373/projectResources.js:3040:504 rAb@https://editor.construct.net/r373/projectResources.js:3041:190 dispatchEvent@https://editor.construct.net/r373/main.js:1268:42 vv@https://editor.construct.net/r373/projectResources.js:48:279 Wa@https://editor.construct.net/r373/projectResources.js:656:253 jnb@https://editor.construct.net/r373/projectResources.js:707:15 @https://editor.construct.net/r373/projectResources.js:3043:28
Construct version: r373
URL: https://editor.construct.net/r373/
Date: Wed Jan 03 2024 20:14:37 GMT+0000 (Greenwich Mean Time)
Uptime: 11.5 s

Platform information
Product: Construct 3 r373 (beta)
Browser: Safari 17.0
Browser engine: WebKit
Context: webapp
Operating system: macOS 10.15.7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
Language setting: en-US

WebGL information
Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_pvrtc, WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex
</details>

**Comment by DiegoScirra** [comment] 2024-01-03 22:29
Duplicate of #7708. A regression was introduced in the latest beta which affects every place where there is a table showing icons.

**Closed by DiegoScirra** 2024-01-03 22:29 UTC
Labels: duplicate
