### ISSUE TITLE
Crash after closing the "Segmented Boss Fight" example preview window

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-bugs#7417] opened 2023-09-23 07:36 UTC
## Problem description

Closing the "Segmented Boss Fight" example preview window crashes Construct.

## Attach a .c3p

N/A

## Steps to reproduce

1. Open the Example Browser and find the Segmented Boss Fight example 
2. Hit the play button to preview the example.
3. Close the preview window

## Observed result

Construct crashes

## Expected result

No crash

## More details

**Affected browsers/platforms:**  Microsoft Store, Edge, Chrome

**First affected release:**  Worked in r358, broke in r359

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'lU') @ TypeError: Cannot read properties of null (reading 'lU') at d.lU (https://editor.construct.net/r359/projectResources.js:1794:44) at d.$ (https://editor.construct.net/r359/projectResources.js:1099:239) at d.loa (https://editor.construct.net/r359/projectResources.js:1128:304) at window.q6a.gTa [as Rv] (https://editor.construct.net/r359/projectResources.js:1097:471) at d.Bnb (https://editor.construct.net/r359/projectResources.js:833:285) at d.Mub (https://editor.construct.net/r359/projectResources.js:859:228) at d.Qla (https://editor.construct.net/r359/projectResources.js:859:197) at d.kH (https://editor.construct.net/r359/projectResources.js:858:131) at d.h4a (https://editor.construct.net/r359/projectResources.js:833:148) at d.m (https://editor.construct.net/r359/projectResources.js:1098:391)
Stack: TypeError: Cannot read properties of null (reading 'lU') at d.lU (https://editor.construct.net/r359/projectResources.js:1794:44) at d.$ (https://editor.construct.net/r359/projectResources.js:1099:239) at d.loa (https://editor.construct.net/r359/projectResources.js:1128:304) at window.q6a.gTa [as Rv] (https://editor.construct.net/r359/projectResources.js:1097:471) at d.Bnb (https://editor.construct.net/r359/projectResources.js:833:285) at d.Mub (https://editor.construct.net/r359/projectResources.js:859:228) at d.Qla (https://editor.construct.net/r359/projectResources.js:859:197) at d.kH (https://editor.construct.net/r359/projectResources.js:858:131) at d.h4a (https://editor.construct.net/r359/projectResources.js:833:148) at d.m (https://editor.construct.net/r359/projectResources.js:1098:391)
Construct version: r359
URL: https://editor.construct.net/r359/
Date: Sat Sep 23 2023 00:26:21 GMT-0700 (Pacific Daylight Time)
Uptime: 33.3 s

Platform information
Product: Construct 3 r359 (beta)
Browser: Edge 117.0.2045.36
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by WilsonPercival** [comment] 2023-09-23 07:41
For me the crash occurs when closing the project, not when closing the preview. I think this is a duplicate of https://github.com/Scirra/Construct-bugs/issues/7403

**Comment by Scoremonger** [comment] 2023-09-23 07:57
Oh, yep, the crash log looks the same alright, seems like a dupe. I assume previews load the whole project behind the scenes, so closing the preview window must unload the project.

**Comment by DiegoScirra** [comment] 2023-09-25 10:08
Duplicate of #7403

**Closed by DiegoScirra** 2023-09-25 10:08 UTC
Labels: duplicate
