### ISSUE TITLE
Rotate layout and drawing canvas bug

### ISSUE THREAD

**Issue by luckyrawatfreax** [Scirra/Construct-bugs#7725] opened 2024-01-08 04:20 UTC
## Problem description
I'm rotating layout at 270 degree and drawing on canvas with sprite paste on it. but drawing on canvas is not matching coordinates with touch. If I draw left to right direction in canvas its drawing from top to bottom.

## Attach a .c3p
[layoutRotate.zip](https://github.com/Scirra/Construct-bugs/files/13856213/layoutRotate.zip)

## Steps to reproduce

1. open attached file
2. preview it
3. draw 

## Observed result
output is not matching with input 

## Expected result
it should draw exactly where touch is being touched

## More details

**Affected browsers/platforms:** 
Windows / Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment] 2024-01-08 04:35
Duplicate https://github.com/Scirra/Construct-bugs/issues/6395

**Comment by AshleyScirra** [comment] 2024-01-08 14:18
Closing as duplicate of #6395.

**Closed by AshleyScirra** 2024-01-08 14:18 UTC
