### ISSUE TITLE
Document body style background color bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7840] opened 2024-02-17 01:15 UTC
## Problem description

When I press the `1` button, the background does not turn red.

## Attach a .c3p

[document_body_style_background_color_bug_r368_2s.zip](https://github.com/WilsonPercival/WilsonPercival/files/14317238/document_body_style_background_color_bug_r368_2s.zip)

## Steps to reproduce

1. Open and run the project.
2. Press `1`.

## Observed result

<img width="510" alt="observed" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/98e607f0-7271-4ff1-a154-6352856eee3a">

## Expected result

<img width="537" alt="expected" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/5b132f8a-73bf-4cd3-b3a4-e0439e1f25a9">

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Worked in `r368-2s`, broke in `r369b`. Still doesn't work in `r379s`.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 121.0.6167.161
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 1021 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment] 2024-02-19 11:35
The problem is since the introduction of HTML layers, the <body> element  has a zero height, and so does not draw any background. (I'm not sure why, I think this is just the default layout of block elements which only have absolute-positioned children.) However it is a simple workaround: change the background color of the <html> element instead, like this:

```js
document.documentElement.style.backgroundColor = "red";
```

Technically this is a breaking change but given that Construct's own background color setting in Project Properties still works correctly (as it sets the <html> background color), and there is an easy workaround, closing as wontfix.

**Closed by AshleyScirra** 2024-02-19 11:35 UTC
Labels: wontfix
