### ISSUE TITLE
dialogs Cancel and Done/OK sometimes flipped

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7526] opened 2023-11-03 16:24 UTC
## Problem description
In the Construct dialogs sometimes the Cancel and Done/OK positions are flipped, this leads to me accidentally canceling declarations of variables etc. every day and is very frustrating to me, especially as I often only notice this later and am confused why my change didn't apply.

## Attach a .c3p

[dialogFlipRepro.zip](https://github.com/Scirra/Construct-bugs/files/13252459/dialogFlipRepro.zip)

## Steps to reproduce

1. double click the global variable and look at the dialog
2. double click the condition and look at the dialog

## Observed result
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/da676887-c62a-4676-ab92-7250acf7a26c)
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/534c2018-b5ce-4eec-a0d3-5bdf0e065d2a)
the Cancel and OK/Done buttons are flipped

## Expected result
the Buttons are at the same position: The OK/Done button is always the button on the right and the cancel button is always on the left

## More details
Dialogs where the Buttons are flipped:
global vars
instance vars
new project create dialog
add custom action dialog
custom action params
add function dialog
function params
add new behavior
add new effect
create container
add family
... maybe more

I get that you could argue it's consistent for this type of dialog, but like I said it trips me up regularly and I use c3 daily for years now.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment] 2023-11-03 17:11
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/cac17af8-4403-4f77-93c8-237b16547f56)
it's not just me

**Comment by AshleyScirra** [comment] 2023-11-06 11:23
Duplicate of #3806. The dialog flow for adding actions/conditions is modeled on a wizard with a "next"/"previous" flow, rather than "OK"/"Cancel". Everywhere that uses "OK"/"Cancel" should be consistent with OK on the left and Cancel on the right; however where there is a "next"/"previous" flow the buttons are positioned to match the logical flow of the dialogs, with "next" moving right through the process and "previous" moving backwards through the process. The keyboard shortcuts should be consistent, so you can rely on Enter/Escape. By now I think if we change this we will throw off as many or more people than are confused by the current UI, so not sure changing this will actually make anything better...

**Closed by AshleyScirra** 2023-11-06 11:23 UTC
Labels: duplicate

**Comment by F3der1co** [comment] 2023-11-06 11:41
Yea that's about what I expected, tough luck luck, but thanks for the answer! :)

Weirdly while I am aware that the buttons are flipped I still intuitively press the right most button, especially when I am in some kind of flow state, I wonder if people are intuitively able to differentiate which dialog they are currently in and press the correct button (I don't think anyone reads the button names unless they are just starting out).
Enter is a solution that someone brought up on Discord as well, but for me it's not a real solution as my left hand rests on the left side of the keyboard as I commonly use shortcuts with shift, ctrl, alt etc. and my right hand is always on the mouse as to me the C3 ui feels to be designed mainly for mouse usage. So pressing pressing would requires me to move one of the hands a fair bit.

I guess I'll see if I can use the addon sdk themes to make a branch of the dark theme that changes it.
