### ISSUE TITLE
Crash ease default close bar

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7129] opened 2023-06-20 20:25 UTC
## Problem description

Construct crashes.

## Attach a .c3p

save open project: [save_open_project.zip](https://github.com/WilsonPercival/WilsonPercival/files/11806225/save_open_project.zip)

## Steps to reproduce

1. Create a new project.
2. In the right ear, click on `Timeline 1`.
3. In the left ear, select `Ease` `Default`.
4. Click `Edit`.
5. Click `Close`.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/b50f21e3-1079-4e99-a491-138ba9f6bfc2

## Expected result

Construct does not crash.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r346b

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Q.i (https://editor.construct.net/r346/main.js:1059:147) at d.exc (https://editor.construct.net/r346/main.js:1185:153) at d.nAa (https://editor.construct.net/r346/projectResources.js:1307:191) at https://editor.construct.net/r346/components/bars/propertiesBar/propertiesBar.js:65:410
Stack: TypeError: unexpected type at Q.i (https://editor.construct.net/r346/main.js:1059:147) at d.exc (https://editor.construct.net/r346/main.js:1185:153) at d.nAa (https://editor.construct.net/r346/projectResources.js:1307:191) at https://editor.construct.net/r346/components/bars/propertiesBar/propertiesBar.js:65:410
Construct version: r346
URL: https://editor.construct.net/r346/
Date: Tue Jun 20 2023 23:06:51 GMT+0300 (Восточная Европа, летнее время)
Uptime: 31 s

Platform information
Product: Construct 3 r346 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment] 2023-06-21 15:46
Can't reproduce. Neither how it is shown in the video nor by quickly clicking on Edit and closing the dialog with ESC repeatedly. Will close as there isn't anything else I can think about to reproduce it.

**Closed by DiegoScirra** 2023-06-21 15:46 UTC
Labels: can't reproduce

**Comment by fredriksthlm** [comment] 2023-06-21 16:42
For me the editor crashed instantly when I tried the above, on the first try.

Actually for me I don't even need to change ease.
Just click Timeline, then Edit, then close it. The editor crashes every time directly. It does not need to be quickly either.

**Comment by WilsonPercival** [comment] 2023-06-21 18:58
> Can't reproduce. Neither how it is shown in the video nor by quickly clicking on Edit and closing the dialog with ESC repeatedly. Will close as there isn't anything else I can think about to reproduce it.

@DiegoScirra Yes, you can choose any `Ease` except `Linear` and you will get the same crash. Velocity doesn't matter here.

**Comment by WilsonPercival** [comment] 2023-06-21 21:36
@DiegoScirra I can also repeat the crash on android.

![Screenshot_20230622-003433_Chrome](https://github.com/Scirra/Construct-bugs/assets/91274932/c7aa791c-3ac2-4782-9494-f340a0563da6)

**Comment by dop2000** [comment] 2023-06-22 14:54
For me the editor crashes immediately as I select "Default" and click "Edit".
