### ISSUE TITLE
Set Object JSON: duplicate child object

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7320] opened 2023-08-22 15:25 UTC
## Problem description

When I set JSON for a newly created object, will duplication of child objects for that object.

## Attach a .c3p

[set-obj-json-duplicate-child-issue.c3p.zip](https://github.com/Scirra/Construct-bugs/files/12410303/set-obj-json-duplicate-child-issue.c3p.zip)

## Steps to reproduce

1. click 'Create' button
2. Observe the count number of child objects

## Observed result

duplicate child object

## Expected result

no duplicate child object

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r354 (beta)
Browser: Chrome 116.0.5845.97
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 187 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Super with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-08-23 14:24
I suspect this is not a bug, as it is by design that saving and loading instances as JSON includes all child objects. I believe this was done intentionally based on prior issue reports stating that this did not work, but that it should, as otherwise it's difficult to use these features with hierarchies. @DiegoScirra - is that correct? If so please close this issue as "not a bug".

**Comment by XHXIAIEIN** [comment] 2023-08-26 04:40
Another similar case by @WilsonPercival in https://github.com/Scirra/Construct-bugs/issues/7333.

[issue#7320-case2.c3p.zip](https://github.com/Scirra/Construct-bugs/files/12444579/issue.7320-case2.c3p.zip)

You can observe that `Set from JSON` action will duplicate object,It directly replicates exponentially.

**Comment by DiegoScirra** [comment] 2023-09-21 12:11
A possible fix for this issue will be available in the next beta. It is very difficult to tell if there will be unforeseen ramifications, so will have to pay attention to this to so how it turns out.

**Closed** 2023-09-21 12:19 UTC
