### ISSUE TITLE
On Object Touched doesn't pick the touched instance

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#8033] opened 2024-05-25 08:15 UTC
## Problem description

On Object Touched doesn't pick the touched instance

## Attach a .c3p

[TouchPickBug.zip](https://github.com/Scirra/Construct-bugs/files/15442290/TouchPickBug.zip)

## Steps to reproduce

1. Touch any green sprite

## Observed result

4 instances change opacity.

## Expected result

Only the touched instance should change opacity.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 125.0.6422.78
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 531 gb
Storage usage (approx): 7.7 gb (1.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 6800 (0x000073BF) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2024-05-28 16:06
The code around this is extremely complicated, and the event blocks seem quite contrived. It's also easy to work around: don't use the redundant OR block, or rearrange the trigger to be at the top and the other events to be sub-events, and it works correctly. So closing as wontfix - just work around it by adjusting your events.

**Closed by AshleyScirra** 2024-05-28 16:06 UTC
Labels: wontfix

**Comment by dop2000** [comment] 2024-05-28 16:10
>  just work around it by adjusting your events

Working around is easy - when you know where the bug is. I lost about an hour trying to understand why the code doesn't work.
And there is no way to see the redundant OR blocks without right-clicking it.

**Comment by AshleyScirra** [comment] 2024-05-29 14:59
I was looking at #7912 and I think this is actually a duplicate of that. So I think it will be fixed in the next beta in the end anyway.
