### ISSUE TITLE
can't drag script or comment to/from event level to/from condition level

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6682] opened 2023-03-02 10:47 UTC
We can't drag scripts or comments to/from event level to/from condition level.

## Attach a .c3p
[dragScriptAndComment.zip](https://github.com/Scirra/Construct-3-bugs/files/10870413/dragScriptAndComment.zip)

## Steps to reproduce

https://user-images.githubusercontent.com/89512047/222406662-b86cd465-cb6a-477b-882b-941a6efe3d21.mp4

1.try dragging the comment and script in the event level to the condition level (or vice versa) 

## Observed result

cannot be moved

## Expected result

can be moved

## More details
It would be a lot more comfortable ux wise if we could move them like this.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2023-03-02 16:21
This is because scripts in actions have the same drag-and-drop rules as actions, and scripts as event blocks have the same drag-and-drop rules as event blocks, both of which are normally not interchangeable. I'll see if this is straightforward to change, but if not it may be better categorized as a suggestion, as so far it is by design.

**Comment by OverboyDev** [comment] 2023-03-02 16:36
![image](https://user-images.githubusercontent.com/99751718/222493220-a4ce0430-a402-472e-a330-0fa27db061ff.png)

**Comment by AshleyScirra** [comment] 2023-03-15 12:20
I'm afraid that partly due to an extraordinary number of issues being filed at the moment we simply don't have the time to investigate non-essential issues that are arguably by design. Therefore I'm closing this issue. You can file it as a suggestion if you still want us to consider it long-term.

**Closed by AshleyScirra** 2023-03-15 12:20 UTC
Labels: not a bug

**Comment by F3der1co** [comment] 2023-03-15 12:29
https://construct23.ideas.aha.io/ideas/C23-I-210 
ok, I wrote a suggestion. I hope we get this UX feature some-day.
