### ISSUE TITLE
Bullet AngleOfMotion is not set correctly if Object speed is 0 (and later changed)

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#7355] opened 2023-08-31 12:14 UTC
## Problem description

Changing Bullet AngleOfMotion doesn't work if Speed is 0 and subsequently increased.

## Attach a .c3p

[BulletAngleBug.zip](https://github.com/Scirra/Construct-bugs/files/12485917/BulletAngleBug.zip)

## Steps to reproduce

1. Run the layout.

## Observed result

Sprite moves at 0 degrees.

## Expected result

Sprite should move at 90 degrees, since the AngleOfMotion was set to 90 (check the events).

## More details

Sprite Bullet Speed is 0, the bug doesn't happen if its set to any superior value.

**Affected browsers/platforms:** 

Chrome.

**First affected release:** 

Beta 356.

## System details

<details><summary>View details</summary>

Device name	LAPTOP-DAOHK829
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.83 GB usable)
Device ID	3FC91B51-E8DD-4CFB-B006-E1141BF1C7B0
Product ID	00325-82098-04728-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	22H2
Installed on	‎20/‎11/‎2022
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

</details>

**Comment by WilsonPercival** [comment] 2023-08-31 12:24
<img width="529" alt="docs" src="https://github.com/Scirra/Construct-bugs/assets/91274932/1493eaf7-3d9d-4c64-8206-95b65d12eb82">

https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/bullet

**Comment by DinoSystem** [comment] 2023-08-31 12:51
> <img alt="docs" width="529" src="https://user-images.githubusercontent.com/91274932/264643156-1493eaf7-3d9d-4c64-8206-95b65d12eb82.png">
> https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/bullet

I see, but that's a strange feature, AngleOfMotion should be independent.

**Comment by AshleyScirra** [comment] 2023-09-01 11:01
Duplicate of #6105.

**Closed by AshleyScirra** 2023-09-01 11:01 UTC
Labels: duplicate
