### ISSUE TITLE
Construct seems to fail to use Webgl1 after 317.2

### ISSUE THREAD

**Issue by squalinho** [Scirra/Construct-bugs#7535] opened 2023-11-08 10:44 UTC
First of all, I apologize if my report is poorly worded, but as English is not my language I'm afraid I won't be completely clear.
For some time we have noticed a problem on several of our projects and it seems to be linked to WebGl1 - WebGl2. We have noticed a problem with lot of our customers on computers that do not support webgl2. The problem also occurs on an empty project without any content.
It appears that the project refuses to launch and leaves a blank screen.
By carrying out various tests we have determined that the problem occurs on NWJS exports, with a version of Construct greater than 317.2. It seems that construct after this version Construct can no longer run WebGl1. 

## Attach a .c3p

The problem occurs on an empty project

## Steps to reproduce

1. Export for windows with nwjs (regardless of the nwjs version) with Construct in version higher than 317.2
2. Test on a computer that does not support webgl2

## Observed result

The project remains on a blank screen

**Comment by WilsonPercival** [comment] 2023-11-08 10:59
I think this is a duplicate: https://github.com/Scirra/Construct-bugs/issues/7159

**Comment by squalinho** [comment] 2023-11-08 11:14
It actually seems to be the same problem. There is no solution ? This is a real problem, more and more of our customers are reporting this problem to us.

**Comment by AshleyScirra** [comment] 2023-11-08 11:24
Duplicate of #7159. As I said there, please report this to Google at crbug.com, as it's either a problem with Chrome or with broken graphics drivers, both of which are outside our control.

**Closed by AshleyScirra** 2023-11-08 11:24 UTC
Labels: duplicate

**Comment by squalinho** [comment] 2023-11-08 11:34
Ok I understand, thank you for taking the time to respond.
