### ISSUE TITLE
WebGPU not rendering anything on some Intel GPUs

### ISSUE THREAD

**Issue by NedSanders** [Scirra/Construct-bugs#7906] opened 2024-03-19 13:03 UTC
## Problem description

 Since the most recent update, whenever I preview/debug any project/layout, no visuals render. I can only see HTML elements. Debug shows that the instances are there, just not showing. I tried testing on Opera and it was fine, leading me to believe this is a Chrome-only issue.

## Attach a .c3p

 https://drive.google.com/file/d/1ijag2lmW7wA8LAwbD8nJisQpl5cqxKD3/view?usp=sharing

This is the project I first noticed this on, but upon further investigation, this is happening on all projects.

## Steps to reproduce

1. Be me
2. Preview/debug any project

It may not be possible to replicate issue, so have included a screenshot of the outcome.

![Screenshot 2024-03-19 124322](https://github.com/Scirra/Construct-bugs/assets/146987111/1cdbbde0-617e-4fdd-be10-71fcf9991ca3)

## Observed result

My background colour and all HTML items but no instances, sprites, etc. (See screenshot above)

## Expected result

To be able to see objects at runtime.

## More details

**Affected browsers/platforms:**  Chrome

 This is a consistent issue as of r383 beta, but I noticed it in r382, where it occurred several times before seeming to fix itself

**First affected release:** 

## System details

Platform information
Product: Construct 3 r383 (beta)
Browser: Chrome 122.0.6261.129
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 255 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics (0x00009A68) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

**Comment by WilsonPercival** [comment] 2024-03-19 13:53
Can not reproduce. Everything works well for me.

<img width="276" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/91274932/9b534226-ab39-46a9-8d2b-394b5e23316d">

**Comment by AshleyScirra** [comment] 2024-03-19 16:12
Can you try two things for me:

1. In preview, when nothing renders, press F12 and look for any error messages in the browser console
2. In Project Properties, in the advanced section, set 'Enable WebGPU' to 'No' and see if that helps.

I suspect there may be an issue with WebGPU on the specific hardware you have. WebGPU is now enabled by default in beta releases as of r382+ to help us identify outstanding issues such as this.

**Comment by NedSanders** [comment] 2024-03-19 17:16
@AshleyScirra Certainly. Screenshot of console below.

1. ![image](https://github.com/Scirra/Construct-bugs/assets/146987111/a920b511-7712-4056-ac33-24f965470017)

2. Disabling WebGPU worked! Thank you!

**Comment by AshleyScirra** [comment] 2024-03-20 12:27
Thanks, that confirms it is an issue with WebGPU. I will follow up by filing this issue with Google as I think it will be some kind of driver bug or hardware quirk that needs to be worked around by WebGPU.

**Comment by AshleyScirra** [comment] 2024-03-20 14:22
Can I just confirm that someone with an affected device (@NedSanders or @skinkairewalker) sees a blank screen when viewing this page?: https://downloads.scirra.com/labs/gs-webgpu/

**Comment by AshleyScirra** [comment] 2024-03-20 14:59
One more thing: could anyone with an affected device (once again @NedSanders and @skinkairewalker) please visit about:gpu in Chrome/Edge, click the 'Download report to file' button, and attach the resulting file here? The reason for this is the details logged by Construct are not very specific, but that report will include your specific hardware and driver details, which Google will need to see for the issue I am intending to file with them.

**Comment by skinkairewalker** [comment] 2024-03-20 19:25
[this ? ](https://prnt.sc/Ah5B_L-aSpaP)
[gs-webgpu.txt](https://github.com/Scirra/Construct-bugs/files/14671620/gs-webgpu.txt)

**Comment by skinkairewalker** [comment] 2024-03-20 19:26
sorry by delay xD @AshleyScirra 
[about-gpu-2024-03-20T19-26-23-995Z.txt](https://github.com/Scirra/Construct-bugs/files/14671626/about-gpu-2024-03-20T19-26-23-995Z.txt)

**Comment by skinkairewalker** [comment] 2024-03-20 19:27
> Can I just confirm that someone with an affected device (@NedSanders or @skinkairewalker) sees a blank screen when viewing this page?: https://downloads.scirra.com/labs/gs-webgpu/

[screenshot : ](https://prnt.sc/LaOAeMxXOZGR)

**Comment by AshleyScirra** [comment] 2024-03-21 12:34
Thanks for confirming. I've now filed an issue with Google here: https://issues.chromium.org/issues/330655410
It'll be followed up there, so closing this issue. However if Google have any more questions I might reply here to request some more information.

**Closed by AshleyScirra** 2024-03-21 12:34 UTC
Labels: external, webgpu

**Comment by skinkairewalker** [comment] 2024-03-21 17:48
[Solution in > ](https://github.com/Scirra/Construct-bugs/issues/7914)

**Comment by skinkairewalker** [comment] 2024-04-02 14:07
sorry for the delay,
exam week at university.
Well, I tested updating to a higher version: 30.0.101.1273, and on my video card the screen keeps blinking, but I believe it solves the problem of not rendering webgpu on intel cards. 
However, I had to downgrade so that the screen doesn't flicker...

**Comment by AshleyScirra** [comment] 2024-04-03 14:58
@NedSanders / @skinkairewalker - I'm told this is already fixed in v125+ (currently Chrome Canary) and the fix is also due to ship in v123 stable and v124 beta soon. So if you get Chrome Canary you should already be able to verify if that has it working for you.
