### ISSUE TITLE
Sprite Object Turns 180 Degrees Clockwise After Tweening Scale from 0 to 1 bug

### ISSUE THREAD

**Issue by akarmehmet** [Scirra/Construct-bugs#7567] opened 2023-11-22 20:38 UTC
### Problem description

While using the tween functionality in Construct 3 to transition a sprite object's scale from 1 to 0 initially, and subsequently from 0 to 1, an unexpected behavior occurs. Specifically, after scaling the sprite object from 1 to 0 and then back from 0 to 1, the sprite unexpectedly rotates precisely 180 degrees in a clockwise direction.

### Attach a .c3p

[ScaleTweenError.zip](https://github.com/Scirra/Construct-bugs/files/13443994/ScaleTweenError.zip)

### Steps to reproduce

1. Open and run the project.
2. Click "Scale 0" button.(right button)
3. After the sprite disappears completely, click on the "Scale 1" button on the left 
4. Wait for the sprite to grow fully

## Observed result
The sprite object rotates precisely 180 degrees clockwise.

## Expected result

The expected result was that the sprite object would scale from 0 to 1 without any rotation occurring.

## More details

**Affected browsers/platforms:** : Chrome/Safari on macOS
**First affected release:** broke in r358s

## System details

<details><summary>View details</summary>
Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 119.0.6045.159 (Official Build) (arm64)
Browser engine: Chromium
Context: browser
Operating system: macOS Sonoma 14.1.1 (23B81)
Device type: desktop
Logical CPU cores: 16
Approx. device memory: 16 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 495 gb
Storage usage (approx): 458 gb
Persistant storage: No

</details>

**Comment by F3der1co** [comment] 2023-11-22 20:56
I cannot reproduce this, it works for me correctly when I follow the steps

**Comment by WilsonPercival** [comment] 2023-11-23 04:22
@akarmehmet I can reproduce the problem. But where did you get the idea that the sprite rotates? Its angle is always 0. This is a duplicate of: https://github.com/Scirra/Construct-bugs/issues/7397

**Comment by akarmehmet** [comment] 2023-11-23 04:54
@WilsonPercival Because in my case it always turns the sprite as if it rotated 180 degrees clockwise, even though its angle remained 0 degrees.

**Comment by akarmehmet** [comment] 2023-11-23 05:12
I am sharing a video to help solve the problem. As can be seen, when the scale value of the sprite is reduced to 0 with tween, the Width and Height values become negative. Later, when enlarged with tween, they have negative height and width. However, when scaled to 0 at the 25th second of the video, the width and height values become 1.12, and when scaled back to 1, the result is as expected for the width and height values are positive.

https://github.com/Scirra/Construct-bugs/assets/38632060/219274f2-862c-4df0-b4f4-62b3aaa96527

**Comment by AshleyScirra** [comment] 2023-11-23 12:04
This is a classic floating point precision issue: scaling the size to 0 actually leaves it with a size of something like -0.000000000000015, which you can see in the debugger. This means it ends up with a flipped or mirrored state as the size is negative. For various reasons involving other issues, the Tween behavior cannot assign the end value at the end of the tween, and updates over time can accumulate a small error and so land close to but not exactly on the final value.

This should be easy to work around though: either tween to a scale of a small number like 0.001, set the size to the intended value after the tween, or tween to a fixed width and height.

**Closed by AshleyScirra** 2023-11-23 12:04 UTC
Labels: wontfix
