### ISSUE TITLE
ZIP files error when dragged into Animation Editor

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-bugs#7851] opened 2024-02-20 16:17 UTC
## Problem description

When I drag a zip file into the animation editor, as instructed in the [manual](https://www.construct.net/en/make-games/manuals/construct-3/interface/animations-editor#internalH1Link7), an error is shown. 

## Attach a .c3p

I've attached two basic zip files, each containing the same three images as JPGs and PNGs, created on MacOS Sonoma 14.3

[JPG.zip](https://github.com/Scirra/Construct-bugs/files/14348290/JPG.zip)
[PNG.zip](https://github.com/Scirra/Construct-bugs/files/14348291/PNG.zip)

## Steps to reproduce

1. Create a sprite
2. Open the sprite in the Animation Editor
3. Drag either of the zip files into any part of the Animation Editor

## Observed result

An error message is shown:

![zipImportError](https://github.com/Scirra/Construct-bugs/assets/63005234/776669ab-7f5e-402a-b863-aeea8d64334b)

## Expected result

The images would import, as mentioned in the manual, and by @DiegoScirra in this [feature request discussion](https://github.com/Scirra/Construct-feature-requests/issues/42#issuecomment-1954529558).

## More details

**Affected browsers/platforms:** MacOS Sonoma 14.3, Chrome 121.0.6167.184

**First affected release:** r380

**Note:** the error message is showing a different filename than the zipped files—the filename in the error message should read "Snake1.png", but instead reads "._Snake1.png"

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2024-02-20 17:08
Looks like this is an OSX only problem caused by the hidden folders it creates. The importer should ignore the folder and all the content. Windows sees the files, but doesn't understand them as images either.

**Comment by DiegoScirra** [comment] 2024-02-21 19:18
Will be fixed in the next beta.

Files that look like images but are not will just be ignored. In this particular case this will result in the subfolder __MACOSX being created and left empty.

Unfortunately because there is no way to determine if a folder was originally meant to be hidden or not I can't just discard it because it is empty, because someone out there might be using the bulk importer as a shortcut to create an empty subfolder structure in an object type.

**Comment by brushfe** [comment] 2024-02-21 19:55
Awesome, thanks very much!

**Comment by DiegoScirra** [comment] 2024-02-23 13:33
Ended up adding the special case to avoid reading the contents of folders named **__MACOSX**. It would be pretty rare for someone to name their folders like that manually and anyone importing a file and finding that was created would probably just delete it anyway.

**Closed** 2024-02-23 13:33 UTC
Labels: macOS
