### ISSUE TITLE
Copy/paste frames in animation results in bad frames during preview.

### ISSUE THREAD

**Issue by ruskul** [Scirra/Construct-bugs#7845] opened 2024-02-19 04:53 UTC
## Problem description

When duplicating frames in an animation, if you do not change any pixel information, during preview, when you set a sprite to the duplicated frame index, it will change the image to some large random square.  I typically work with 16x16 sprites, and the the error frame with be like 256x256, for example.

If you edit any of the pixel information in the frame, the bug will go away.  If you save and close the project, on re-opening, the bug will no longer be present.  It only seems to affect frames that are copy pasted, although you can change the collision poly and still encounter the bug so long as you don't change any pixels.

## Attach a .c3p

No project attached, as the process of saving and reloading fixes the error.  I created this one to demonstrate how I would do it, but the error at this point won't be present:

https://drive.google.com/file/d/1FpX5_jIuaaFvDFbBtHmj2elhZr9J87B3/view?usp=drive_link

The small sprite has drag behavior and the events change frames based on initial overlap.

## Steps to reproduce

1.  Create a new sprite and set the first frame to anything you want.  Make sure to set the animation playback speed to 0.
2.  duplicate several frames.
3.  In the event sheet, add logic to switch to one of the frames that you copied.

## Observed result

In my project, setting a sprite to such a frame during preview will result in an oversized box of random assets (maybe a graphics memeory spill)?  I'm not sure, but it seems different the few times this has happened.

## Expected result

Obviously, I expect the correct frame to display.

## More details

The issue specifically was occurring on the standalone app editor, running r379

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment] 2024-02-19 06:18
Sorry, but I did not understand what the problem was or the reproduction steps. Could you please attach a video demonstrating the problem, which also includes the reproduction steps?

**Comment by ruskul** [comment] 2024-02-19 06:33
Cant create a video.

The error occurs during preview, when the sprite's animation frame gets set to a frame which was created by ctrl-c ctr-v duplication of frames.

1. Create a sprite
2. Set the size of frame 1 to 16x16 (or whatever), draw anything you like.
3. Set the animation speed to 0
4. Create additional frames by copying frame 0, and pasting several times.
5. Create logic via the event sheet to set the sprites animation frame to one of the frames you created during the frame duplication process. 
6. Preview
7. When creating additional frames, do not change the pixels or image.  Simply copy paste.  You can change the collision poly, but nothing about the image.

Does this make any sense?

**Comment by WilsonPercival** [comment] 2024-02-19 07:39
I think I understand what you are talking about. When I change the frame, the sprite suddenly moves to the upper left corner, although the hotspot is exactly in the center.

https://github.com/Scirra/Construct-bugs/assets/91274932/dbaa5150-6a29-4ad9-97d5-2a39c8b7d38f

**Comment by DiegoScirra** [comment] 2024-02-23 17:53
Will be fixed in the next beta.

**Closed by DiegoScirra** 2024-02-23 17:53 UTC

**Comment by ruskul** [comment] 2024-02-28 22:10
Thank you, sorry I couldn't make a video at the time!  My description of the issue was rubbish, thanks for deciphering it!
