### ISSUE TITLE
problem with starting the application from version 385

### ISSUE THREAD

**Issue by Ceterge** [Scirra/Construct-bugs#8244] opened 2024-09-23 13:54 UTC
## Problem description

 Since version 385+ construct 3 there is an error starting the application on Android 9 and lower (I had no way to check if this also occurs on Android 10)

## Attach a .c3p

It it occurs on even empty app

## Steps to reproduce

1. Create app on construct 3 384 and 385
2. Install the application on a phone with Android 9.0 or lower.
3.Check which application will start

## Observed result

Since version 385, applications do not work correctly, even though it is possible to direct the application to Android 7+

## More details

It is related to minification, I checked on samsung, motorola and blackberry with android 9 or lower, everywhere the same error

## System details

Platform information
Product: Construct 3 r407 (stable)
Browser: Chrome 128.0.6613.138
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.375
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 1 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 630 (0x0000591B) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2024-09-24 12:31
To help further investigate this please answer the following questions:

1. Does the project work in the Chrome browser on the device?
2. What is the version of Chrome on the device? (visit chrome://version to check)
3. Does updating Chrome and/or the Android System WebView from the Google Play Store fix the problem?
4. If not, please try [remote debugging](https://developer.chrome.com/docs/devtools/remote-debugging) with the device to open Dev Tools and check the console for any errors.

**Comment by AshleyScirra** [comment] 2024-09-24 12:37
FWIW the oldest Android device we currently have access to is Android 10, and that can run an Android export from Construct r407.2 just fine. Usually out-of-date software (Chrome or Android WebView) is the cause of problems with Android compatibility.

**Comment by AshleyScirra** [comment] 2024-09-25 10:28
OK, closing this issue then as it sounds like it was just a case of out-of-date software.

**Closed by AshleyScirra** 2024-09-25 10:28 UTC
Labels: external, Android
