### ISSUE TITLE
Duplicating an existing timeline crashes construct

### ISSUE THREAD

**Issue by squalinho** [Scirra/Construct-bugs#8246] opened 2024-09-24 15:50 UTC
Duplicate timeline crash construct

## Steps to reproduce

1. Open new empty project
2. Right click on a timeline -> duplicate 
 

## Observed result

Construct crash

## More details

**Affected browsers/platforms:**Chrome

**First affected release:**r407.2 stable

## System details
 MacOS Sonoma 14.6.1 Intel

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: timeline name 'Timeline 1' already used @ Error: timeline name 'Timeline 1' already used at d.eb (https://editor.construct.net/r407-2/projectResources.js:1099:44) at d.Eg (https://editor.construct.net/r407-2/projectResources.js:1101:6) at d.za (https://editor.construct.net/r407-2/projectResources.js:1104:477) at async d.wg (https://editor.construct.net/r407-2/projectResources.js:1058:416) at async https://editor.construct.net/r407-2/components/bars/projectBar/projectBar.js:73:385
Stack: Error: timeline name 'Timeline 1' already used at d.eb (https://editor.construct.net/r407-2/projectResources.js:1099:44) at d.Eg (https://editor.construct.net/r407-2/projectResources.js:1101:6) at d.za (https://editor.construct.net/r407-2/projectResources.js:1104:477) at async d.wg (https://editor.construct.net/r407-2/projectResources.js:1058:416) at async https://editor.construct.net/r407-2/components/bars/projectBar/projectBar.js:73:385
Construct version: r407.2
URL: https://editor.construct.net/
Date: Tue Sep 24 2024 17:47:28 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 40.6 s

Platform information
Product: Construct 3 r407.2 (stable)
Browser: Chrome 129.0.6668.59
Browser engine: Chromium
Context: webapp
Operating system: macOS 14.6.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, ANGLE Metal Renderer: Intel(R) Iris(TM) Plus Graphics 655, Unspecified Version)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by DiegoScirra** [comment] 2024-09-25 13:30
Will be fixed in the next beta, was a regression introduced in r401 as a result of a fix for projects failing to load due to project objects having invalid characters in their names.

**Closed by DiegoScirra** 2024-09-25 13:30 UTC
