### ISSUE TITLE
Duplicate animation name error, again (supposedly fixed in 2019)

### ISSUE THREAD

**Issue by davidFailedToOpen** [Scirra/Construct-bugs#8104] opened 2024-07-08 04:12 UTC
## Problem description

 c3p file will not open. It won't allow the user into the file.

## Attach a .c3p 

 [crusadeOfTonkin.zip](https://github.com/user-attachments/files/16122494/crusadeOfTonkin.zip)

## Steps to reproduce

1. Error happens on trying to open. It won't allow the user into the file.
2.
3.

## Observed result

 Error message - "Duplicate Animation Name"  
![Screenshot 2024-07-08 000054](https://github.com/Scirra/Construct-bugs/assets/174982841/cdba5d80-2510-43b8-b8af-8fa7967ad291)

## Expected result

 Open the file.

## More details
 Same issue from old bug report from 2019 by [bgerards](https://github.com/bgerards), in which [DiegoScirra](https://github.com/DiegoScirra) claimed the bug was fixed. 

 Opera GX. Chrome, Firefox on Windows

**Affected browsers/platforms:**  Opera GX. Chrome, Firefox on WindowsWindows

 r397

**First affected release:**  worked in r397 and broke in r397

## System details

 
![image](https://github.com/Scirra/Construct-bugs/assets/174982841/4e4d92c6-0a48-437e-ae82-8e9b46d13e3b)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by davidFailedToOpen** [comment] 2024-07-08 04:15
> 2494/crusadeOfTon

[crusadeOfTonkin.zip](https://github.com/user-attachments/files/16122599/crusadeOfTonkin.zip)
I'm not sure if the attachment works

**Comment by davidFailedToOpen** [comment] 2024-07-08 04:16
okay now it does

**Comment by AshleyScirra** [comment] 2024-07-08 15:15
Unfortunately this issue lacks steps to reproduce the problem in the first place, so it is impossible for us to know how to identify and fix the actual original cause of this.

Unfortunately the provided project file also relies on a third-party addon *RGBA channel separation* which I don't have so I cannot open the project. You may have to restore a backup. If your project still opens in r388.2, see [this post](https://www.construct.net/en/forum/construct-3/general-discussion-7/help-today-construct-update-182656#forumPost1109783). As there is no action we can take on this issue, closing.

**Closed by AshleyScirra** 2024-07-08 15:15 UTC
Labels: no repro

**Comment by davidFailedToOpen** [comment] 2024-07-08 21:55
Pardon me for the lack of steps but a previous bug report from bgerards in 2019 with the same exact problem wrote the same exact thing, had a good response, and was solved. But yeah I think I didn't make it clear enough what were the steps so I'm going to reformulate it. Step 1: Open the file. The bug occurs when you open the file and there is nothing more afterwards. I am sure it is not impossible to reproduce as you only need to open the file. 

Also, I'm quite confused on what the no repro label means. I clicked on it and it brought up a bug report with a similar problem to mine, only that mine has an error of a duplicate animation and the bug occurs when you open the file while their bug occurs when you open a layout. 

About the third-party addon RGBA channel separation, I am 100% certain it is not the cause of the problem, but just in case, I removed it from the project.c3project file by deleting the lines of the addon. Here is the deleted part: 	

```
	{
			"type": "effect",
			"id": "separatechannel",
			"name": "RGBA channel separation",
			"author": "Ludonaut / oppenheimer",
			"bundled": false,
			"version": "0.1"
		}
	],
```

I'm not so sure if this was properly removed. I figured it started from the opening bracket and ended at the closing square bracket followed by the comma, according to what I learned from sources.

Anyways, here is the new file of the game, without the addon: 
[tonkinNoAddons.zip](https://github.com/user-attachments/files/16134697/tonkinNoAddons.zip)

To solve the bug, I want to know how which bit I need to remove to remove the the duplicate animation successfully and turn it back into a valid c3p file. I already tried removing the duplicate animation.  What I did after was I made a copy of the c3p file, renamed the format from c3p to zip, extracted it, located the JSON file in the objectTypes folder, opened it using notepad,  found a duplicate animation on two different subfolders, deleted one of them (don't know if done correctly), saved the changes and exited, compressed as zip file, renamed the format from zip to c3p, then it gave me this error when I tried opening it on the construct 3 website: main.js:907 [Project] Exception opening:  Error: missing file path 'project.c3proj'
You could also send me back the fixed file, but, it would be the minimized version which I don't need. I don't know if cutting the JSON file and pasting it in the non-minimized version would work either.

I hope you understand and take your time to read through my message. Thanks for your consideration

**Comment by AshleyScirra** [comment] 2024-07-09 13:36
The steps to reproduce need to start with a working project that opens successfully, and end with a project that fails to open with this error. Without this it's impossible to identify what the problem is. As it stands all we have is the last step, with an already broken project, and no clue whatsoever as to what caused it to end up in that state. Sometimes using good guesswork informed by our long experience, we can be lucky and figure things out anyway even with missing information, but that just means you were lucky, and not that it's how problems are always solved.
