### ISSUE TITLE
Bugs with deleting animations/frames in the editor

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#7092] opened 2023-06-04 11:08 UTC
There are several issues, I believe they are all related.

## Attach a .c3p

[DeleteAnimationBugs.zip](https://github.com/Scirra/Construct-bugs/files/11645455/DeleteAnimationBugs.zip)

## Steps to reproduce

Bug 1:
Open the sprite in the animation editor.
Select "Origin" image point. Then click any frame or animation, then press Del on keyboard.
Result: nothing happens. 
Expected result: the frame/animation should be deleted.

Bug 2: 
Select "image point 2". Then click any frame or animation and press Del key on keyboard.
Result: the image point is deleted, instead of the frame or animation. It's easy to miss that and remove important image points by accident!
Expected result: the frame/animation should be deleted.

Bug 3: 
Select one or two frames, right-click them. There is "Delete" option in the context menu:

![image](https://github.com/Scirra/Construct-bugs/assets/36763350/77abf7cd-bb26-4040-a4fe-d7d44023cc61)

Then select three or more frames, right-click. The "Delete" option disappears:

![image](https://github.com/Scirra/Construct-bugs/assets/36763350/210466ab-cec8-4458-916e-305dcf0d39af)

Expected result: "Delete" option should be available.

## More details

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:** Used to work before

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r344 (stable)
Browser: Chrome 113.0.5672.129
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 265 gb
Storage usage (approx): 159 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment] 2023-06-04 12:27
https://github.com/Scirra/Construct-bugs/issues/7087

**Comment by DiegoScirra** [comment] 2023-06-05 10:20
The first two issues are a regressions introduced in r336 from attempting to fix #6827. Both problems should be fixed now.

The third issue seems to be a very old one which no one had noticed before because it is very subtle. It will also be fixed.

**Closed** 2023-06-05 10:22 UTC
