### ISSUE TITLE
Changes in object picking between versions related to OR / Touch

### ISSUE THREAD

**Issue by Fishaphrodite** [Scirra/Construct-bugs#7967] opened 2024-04-24 17:41 UTC
## Problem description

Construct apparently changed slightly how OR events featuring touch will pick objects, or so it seems, I'll attach a .c3p to this post for the issue, but basically, when having a singular ObjectName instance and testing a conditions set like:

Is Touching ObjectName
OR Key LeftArrow is Down

the actions that follow will not pick the ObjectName instance if the "Is Touching" doesn't happen as well, this seems new to version 384, as versions prior did pick the instance anyway

## Attach a .c3p

[BugReportTouchORKeyboardPicking.zip](https://github.com/Scirra/Construct-bugs/files/15098251/BugReportTouchORKeyboardPicking.zip)

## Steps to reproduce

1.Rename the BugReportTouchORKeyboardPicking.zip file into a BugReportTouchORKeyboardPicking.c3p, and open it in release 383 of Construct
2.Run the preview, and press the left arrow on the keyboard; while the arrow is down, observe the text object's text change into an arrow
3.Open the same project in version 384, run the preview, press the left arrow on the keyboard, observe the text doesn't change

## Observed result

The way the project reacts changes between versions

## Expected result

No changes in how the project reacts between versions

## More details

**Affected browsers/platforms:** Chrome, Firefox

**First affected release:** changed between v383 and v384

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r388.2 (stable)
Browser: Firefox 125.0
Browser engine: Gecko
Context: browser
Operating system: Linux (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
Language setting: en-US
Local storage

Storage quota (approx): 91 gb
Storage usage (approx): 786 mb (0.8%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Intel
Renderer: Intel(R) HD Graphics, or similar
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 255
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    WEBGL_compressed_texture_astc
    WEBGL_compressed_texture_etc
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm;codecs=opus)
    WebM Vorbis (audio/webm;codecs=vorbis)
    MPEG-4 Opus (audio/mp4;codecs=opus)
    MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav;codecs=1)

Supported encode formats:

    WebM Opus (audio/webm;codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm;codecs=av01.0.00M.08)
    WebM VP9 (video/webm;codecs=vp9)
    WebM VP8 (video/webm;codecs=vp8)
    MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
    MPEG-4 VP9 (video/mp4;codecs=vp9)
    MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

Supported encode formats:

    WebM VP8 (video/webm;codecs=vp8)

</details>

**Comment by WilsonPercival** [comment] 2024-04-25 02:41
Yes you are right. I think this fix introduced a regression: https://github.com/Scirra/Construct-bugs/issues/7888

**Comment by AshleyScirra** [comment] 2024-04-25 13:06
I'm afraid that in this case, the project is in fact working correctly in r384+. The project previously relied on a bug in the 'Is touching object' condition to work correctly, which was fixed in r384 (#7888).

The reason the text does not update when pressing a keyboard button in the latest release is because 'Is touching object' now correctly handles picking. When you are *not* touching LeftText, then no instances meet the condition, and so none are picked. However the OR block can run due to pressing a keyboard key, in which case it runs the actions but with zero LeftText instances picked; therefore the LeftText action does not affect any LeftText instances. (This is a common gotcha with OR blocks: they can run with no instances picked and so actions won't do anything.) Previously a bug in the 'Is touching object' condition incorrectly picked a LeftText instance and ran actions on it even though it did not meet the condition.

This is now consistent with 'Cursor over object': if you replace the 'Is touching object' condition with 'Cursor over object', you can observe the same result in both r383 and r384+. I think it is best to ensure these two conditions work identically and that 'Is touching object' respects the same picking rules as everything else. It's unfortunate that a bug fix is a breaking change - any bug fix is potentially a breaking change if someone's project depended on the bug to work correctly - but in this case I think the best thing to do is update affected projects rather than reintroduce a bug.

**Closed by AshleyScirra** 2024-04-25 13:06 UTC
Labels: not a bug

**Comment by Fishaphrodite** [comment] 2024-04-25 13:20
Thanks for the answer, I preferred to open a bug report in case it wasn't intended as it was a change in how it is handled, but I agree that it does make sense in that way.
