### ISSUE TITLE
Json editor problem

### ISSUE THREAD

**Issue by Kernonen** [Scirra/Construct-bugs#7364] opened 2023-09-04 19:26 UTC
I opened an old project with many json files. In previous versions of Construct 3 (file last opened last spring), json array editor did open correctly. 
On this old file (2 years), only first cell is displayed. When json files downloaded, file is fine and whole. Project behaves correctly as if json file is whole. 
No crash. 
Happens only with json from a file more than 2 years ago. 
Editor works fine with the file from the project I'm working on now and that I started last march. 

## Attach a .c3p

https://www.dropbox.com/scl/fi/5xy9e4ul0ff3lm2q0c07q/JsonEditorBug.c3p?rlkey=9zf5lygtdwjildv1pxvtg5ki8&dl=0

## Steps to reproduce

1.  Open json file array editor
2. See editor only displays one cell
3. Download json file to see there's a lot more than what is just displayed in the editor

## Observed result

Json array editor shows only one cell

## Expected result

Json array editor should display the whole file

## More details

**Affected browsers/platforms:**  Chrome, macOS, Ventura 

**First affected release:** first spotted in r356 but may have happened since the previous one when json array editor was totally broken. 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r356 (beta)
Browser: Chrome 116.0.5845.140
Browser engine: Chromium
Context: webapp
Operating system: macOS 13.4.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 1.6 gb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M2 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by WilsonPercival** [comment] 2023-09-04 21:24
https://github.com/Scirra/Construct-bugs/issues/7347

**Comment by AshleyScirra** [comment] 2023-09-05 10:23
I verified this appears to be working correctly in the next beta release, so I believe this is indeed a duplicate of #7347.

**Closed by AshleyScirra** 2023-09-05 10:23 UTC
Labels: duplicate

**Comment by Kernonen** [comment] 2023-09-05 13:28
I updated to r357 and problem still persists
