### ISSUE TITLE
Bad Guys not dying.

### ISSUE THREAD

**Issue by ironhide1975** [Scirra/Construct-bugs#8094] opened 2024-06-29 22:26 UTC
Randomly enemies will not die when their health reaches zero. Even though I have an action that checks for their health continuously, on rare occasions they will continue to exist. 

Randomly enemies will not die when their health reaches zero.

## Steps to reproduce

Play Wily Live 1 and sometimes the Pirannahs will not die after their health is zero.

## Observed result

Enemy will persist with negative health.

## Expected result

When health hits zero for famEnemyHealth, enemy should be destroyed.

## More details

**Affected browsers/platforms:** 

I use Safari...

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2024-06-30 00:57
This sounds like a problem with your events.

Often times you can run into what you are describing because of a condition that looks something like **when life = 0 then do something**.

The problem is that if life goes below 0, then the condition is never met, so a better condition ends up being **when life <= 0 then do something**. Doing that even if the variable goes below 0, the condition will still be met.

Anyway, this is not the kind of issue that this tracker is for. For this kind of issues it's better to use the forums. It's also a good idea to include your project if possible because it will be much easier for anyone that might be interested in helping you out to tell what is going on if they can just look at the events.

Closing.

**Closed by DiegoScirra** 2024-06-30 00:57 UTC
Labels: not a bug, ignored guidelines
