### ISSUE TITLE
UglifyJS: Black Screen on Mobile 

### ISSUE THREAD

**Issue by Azraellx** [Scirra/Construct-bugs#8255] opened 2024-09-28 15:38 UTC
## Problem description
When I export with UglifyJS minify tool, the game does not run while on mobile (IOS, I don't have an Android to test). The game does run on browser using a computer (Windows). 

## Attach a .c3p

[UglifyTest.zip](https://github.com/user-attachments/files/17174918/UglifyTest.zip)

## Steps to reproduce

1. Export to HTML5 game 
2. Use the settings below

![image](https://github.com/user-attachments/assets/04285b3c-35d0-47e0-84bd-544766d2dae9)

## Observed result

This is the exact file attached above uploaded to a Cloudflare pages (hosting site). 
https://ugfitest.pages.dev/
You can see it works on browser, but not mobile 

## Expected result

Work on mobile 

## More details

![image](https://github.com/user-attachments/assets/671a0c3d-b815-4e3c-a6ca-9eca9b38cd85)
These were the objects I used 

**Affected browsers/platforms:** 
Tested on Safari and Chrome on IOS 17.6.1 — iPhone 15 pro

**First affected release:** 
Latest stable release (never tried on previous releases) r407.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2024-09-30 09:55
When you say "work on mobile", can you clarify exactly what you mean? Are you exporting an Android app and running that, or using a browser on the device, or something else? Please make sure the steps to reproduce include the entire process you are using to observe the issue.

**Comment by q3olegka** [comment] 2024-10-01 05:45
I also got a black screen. As far as I understand, this problem is also related to iOS early versions. It seems that no UglifyJS works on version 16 (simple and advanced)

**Comment by AshleyScirra** [comment] 2024-10-01 15:27
That sounds like #8236, which was already fixed. It's difficult to help with incomplete information - the original report omits the platform information so it's not clear which version of Construct was used. Please try to always follow the bug report guidelines - they are there to help avoid confusion like this.

**Comment by Azraellx** [comment] 2024-10-01 15:30
> When you say "work on mobile", do you mean using the device's browser? Which devices and browsers and their software versions you've tested?
Yes sorry, I only tested on Safari and Chrome on IOS 17.6.1. This was not a native app export. And my phone is iPhone 15 pro. I will update the ticket with this information. 

> I tried running the exported link you provided and it works fine on an Android 14 device running Chrome 129, so it seems to be working fine for me.
Okay, thanks for testing it, then it may be IOS specific

**Comment by Azraellx** [comment] 2024-10-01 16:09
I should of mentioned, the reason I believed it to be an UglifyJS issue in the first place, was because this black/grey screen issue does not happen when I use the other minifier: Closure compiler

**Comment by AshleyScirra** [comment] 2024-10-01 16:41
OK, I can reproduce using iOS 17 with a minified export using UglifyJS. It looks like a Safari bug that was fixed in Safari 18, as it works there... so, ugh, this looks like a nightmare bug - the minifier is generating code that runs in to a bug with Safari 17 and older only. This is going to be a tough nut to crack.

**Comment by Azraellx** [comment] 2024-10-01 16:51
Oh damn. Not a Safari bug :/

**Comment by AshleyScirra** [comment] 2024-10-09 14:40
I think I found a way to configure UglifyJS to work around the Safari bug. I've deployed the fix directly to the minify server, so it should already take effect if you re-export your project using UglifyJS in any release now. It looks like it solves the problem for me, but can you confirm minified exports are working for you now too?

**Comment by q3olegka** [comment] 2024-10-10 07:12
I checked it out. On iOS 16+, the simple version works, but the advanced version does not. But, the advanced version also does not work on Windows PC (in all browsers) and on android. Here is the error:

![image](https://github.com/user-attachments/assets/add8e5dc-239a-4ef3-9c0a-4ca68b2a41b7)

**Closed** 2024-10-10 10:09 UTC
Labels: difficult, safari

**Comment by Azraellx** [comment] 2024-10-16 15:42
Works great! Thanks Ashley!
