### ISSUE TITLE
Tween size is broken when object has parents

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7608] opened 2023-12-04 01:47 UTC
## Problem description

Tweening size of an object that has parents resolves with the wrong values

## Attach a .c3p
[tween parent bug.zip](https://github.com/Scirra/Construct-bugs/files/13541061/tween.parent.bug.zip)

## Steps to reproduce

1. Preview

## Observed result

tween is wrong

## Expected result

tween is correct

## More details

**Affected browsers/platforms:** Tested Chrome only

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2023-12-04 10:55
Duplicate of #7608

**Closed by DiegoScirra** 2023-12-04 10:55 UTC
Labels: duplicate
