### ISSUE TITLE
Function Parameter Move Bug

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-bugs#8072] opened 2024-06-18 14:50 UTC
## Problem description

It gives an error when changing the parameter location.

## Attach a .c3p

[func.zip](https://github.com/user-attachments/files/15888360/func.zip)

## Steps to reproduce

1. Move SelectObject Parameter to top

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r394/projectResources.js, line 1742, col 126
Message: Uncaught TypeError: Cannot read properties of null (reading 'accept')
Stack: TypeError: Cannot read properties of null (reading 'accept') at self.o6a.KZ (https://editor.construct.net/r394/projectResources.js:1742:126) at self.o6a.accept (https://editor.construct.net/r394/projectResources.js:1740:276) at d.KZ (https://editor.construct.net/r394/projectResources.js:1742:126) at d.accept (https://editor.construct.net/r394/projectResources.js:1740:276) at self.o6a.KZ (https://editor.construct.net/r394/projectResources.js:1742:126) at self.o6a.accept (https://editor.construct.net/r394/projectResources.js:1740:276) at window.nI.accept (https://editor.construct.net/r394/projectResources.js:1802:227) at window.eG.KZ (https://editor.construct.net/r394/projectResources.js:1696:425) at window.eG.accept (https://editor.construct.net/r394/projectResources.js:1482:433) at window.eG.accept (https://editor.construct.net/r394/projectResources.js:1696:387)
Construct version: r394
URL: https://editor.construct.net/r394/
Date: Tue Jun 18 2024 17:50:07 GMT+0300 (GMT+03:00)
Uptime: 32.7 s

Platform information
Product: Construct 3 r394 (beta)
Browser: Chrome 125.0.6422.176
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 3GB (0x00001C02) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by XHXIAIEIN** [comment] 2024-06-18 15:58
I can reproduce, The key to reproducing is that when Set value to Function.call(), use the **Array.at()** referenced then switch Parameter, which to crash.

**Comment by XHXIAIEIN** [comment] 2024-06-20 14:44
This is another variation on this bug. If the function is reference, add parameters and then adjust the order of parameters. Crashes and permanently destroys the project

[issue-8072.c3p.zip](https://github.com/user-attachments/files/15915762/issue-8072.c3p.zip)

![Snipaste_2024-06-20_22-41-58](https://github.com/Scirra/Construct-bugs/assets/45864744/2e18cce8-1f64-40b4-be02-0f547600094e)

**Comment by AshleyScirra** [comment] 2024-07-17 15:52
This was a tricky one, but I think it should be fixed in the next beta.

FWIW I only tested the project in the original report - the project provided by @XHXIAIEIN is already corrupt and so cannot be tested - as usual we need reliable steps to reproduce starting with a working project and ending with a broken project, and if you only provide a broken project we can't reproduce the issue.

**Closed by AshleyScirra** 2024-07-17 15:52 UTC
