### ISSUE TITLE
Blank screen on focus/unfocus input field on Chrome mobile on some devices

### ISSUE THREAD

**Issue by zizmsall** [Scirra/Construct-bugs#7704] opened 2024-01-02 14:06 UTC
## Problem description

Blank/black screen when focusing or unfocusing an input field. The keyboard is showing, but the content of the game is blank

## Attach a .c3p

Am attaching the guess the number from exemple page

## Steps to reproduce

On mobile, touch the input field then touch anywere else in the layout

1.
2.
3.

## Observed result

Blank/black screen

## Expected result

to be able to still see the game

## More details
This seems to be specific to chrome mobile. Our previous work/games (published online) that we've developed months ago are not impacted by this issue.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by zizmsall** [comment] 2024-01-02 14:08
The link of the c3p file https://drive.google.com/file/d/1IxzXAmiHJV8cEJPpBRikn734u7vSY4hR/view?usp=sharing

**Comment by WilsonPercival** [comment] 2024-01-02 21:21
Yes, it works well in `r371b`. But starting from `r372b` it doesn't work well.

**Comment by AshleyScirra** [comment] 2024-01-03 17:16
This reproduces for me in the latest release, but also r371, also r368, and I went as far back as r327 from January 2023 and it still reproduces for me there using Remote Preview with the stock 'Guess the number' example. So my best guess is Google changed something about how the Virtual Keyboard works in Chrome on Android and broke how this works in Construct. I'll see if we can get it working again.

**Comment by zizmsall** [comment] 2024-01-03 17:23
> This reproduces for me in the latest release, but also r371, also r368, and I went as far back as r327 from January 2023 and it still reproduces for me there using Remote Preview with the stock 'Guess the number' example. So my best guess is Google changed something about how the Virtual Keyboard works in Chrome on Android and broke how this works in Construct. I'll see if we can get it working again.

Same for me i went as far as r327 as well. Thank you for looking into it!

**Comment by AshleyScirra** [comment] 2024-01-03 18:06
I'm not sure what happened exactly, but I've found what seems to be a relatively straightforward way to get this working better for the next beta. However it still seems to behave slightly strangely, but it looks like a Chrome issue that was a regression a few months back: https://bugs.chromium.org/p/chromium/issues/detail?id=1466893
Hopefully once that is fixed it will work properly, but I think that part is out of our hands.

**Comment by zizmsall** [comment] 2024-01-03 18:13
Again thanks for looking into it Ashley and happy to know that you have a fix on its way with the next beta. By anychance do you have an ETA? Sorry if it seem like im pressuring, it's not. It's just that we have a big campaign launching in a couple of days and our client has already marked this as a bug on our app :'(
Again thanks!

**Comment by WilsonPercival** [comment] 2024-01-03 22:02
> Again thanks for looking into it Ashley and happy to know that you have a fix on its way with the next beta. By anychance do you have an ETA? Sorry if it seem like im pressuring, it's not. It's just that we have a big campaign launching in a couple of days and our client has already marked this as a bug on our app :'( Again thanks!

@zizmsall Updates come out every week.

**Comment by AshleyScirra** [comment] 2024-01-04 17:15
This fix got included in r373.2 which came out earlier today.

**Comment by zizmsall** [comment] 2024-01-04 17:21
> This fix got included in r373.2 which came out earlier today.

Amazing! Thank you very much Ashley 🙏🙏🙏

**Comment by zizmsall** [comment] 2024-01-06 11:57
@AshleyScirra the bug is resolved when previewing the game, but we still have the bug when we publish the game in r373.2
Even with the guess my number example (to reproduce, export and upload on a server)
We have our client on our back since our campaign is live and users are complaining about the issue. Thanks in advance for your help in resolving this

**Comment by zizmsall** [comment] 2024-01-08 13:21
Hi @AshleyScirra sorry if it's felt like pressure, not my intention :(
Any hack that we can implement on our export code to fix this?
Thanks 🙏

**Comment by AshleyScirra** [comment] 2024-01-08 13:42
The code change we made should also apply to APKs. However I will reopen and take another look for that case.

**Comment by zizmsall** [comment] 2024-01-08 14:29
Thank you @AshleyScirra. We are using HTML5 export feature, it's for a web app.
I appreciate your help!

**Comment by AshleyScirra** [comment] 2024-01-08 17:20
I've got another fix for this that should mean it works in Android apps as well for the next beta. Hopefully that's the end of it.

**Closed by AshleyScirra** 2024-01-08 17:20 UTC
Labels: Android

**Comment by zizmsall** [comment] 2024-01-08 17:23
Thank you very for this Ashley 🙏

**Comment by AshleyScirra** [comment] 2024-01-09 15:31
Thanks for confirming!
