### ISSUE TITLE
BBCode outlines generates "spikes" with some characters

### ISSUE THREAD

**Issue by technofou** [Scirra/Construct-bugs#8318] opened 2024-11-10 16:05 UTC
## Problem description

When using the BBCode outline feature paired with a bigger width, some characters generate "spikes" at their apex that shouldn't be present.

![image](https://github.com/user-attachments/assets/38ae943f-5575-47e4-b4fd-e963bf1b3929)

## Attach a .c3p

https://www.dropbox.com/scl/fi/rtovi447hyis2w91yr79c/font_stroke_test.c3p?rlkey=ywn6z06vi4578qtksxjz5dvqd&dl=0
[font_stroke_test.zip](https://github.com/user-attachments/files/17692188/font_stroke_test.zip)

## Steps to reproduce

1. Create a text object
2. Apply as BBCode a thick outline or outlineback such as [outline=#000000][lineThickness=10] or equivalent

## Observed result

A spike will be generated, even at a small outline size, on some character apex.

## Expected result

Most of the characters render correctly and we expected to have a clean outline with outline in conjuction with a forward white text for additional effects control or simply with outlineback with a single text object. 

## More details

We thought it was an issue with our font Sofia Pro Soft Bold and tried to manually fix the affected characters with FontForge. To isolate the issue, we applied the same settings on a new project with Arial (what we consider the most stable and well made font) and discovered that, although some characters are better, the issue is still present.

We tested with a remote preview on two phones to validate that it wasn't a rendering issue on our workstation and it was still present.

**Affected browsers/platforms:** 

Currently Chrome & Edge (Windows), Chrome (Android), Safari (iOS)

**First affected release:** 

Using the latest (stable) version of Construct

**Comment by AshleyScirra** [comment] 2024-11-11 11:46
This is a duplicate of #7684. I'm afraid there isn't any good solution at the moment - the browser is drawing this, not Construct, and from reading associated browser bug reports there isn't a good way for browsers to fix this either, as it depends on the specification's algorithm for stroke rendering of text with a high thickness. You'll just have to work around this, perhaps by pre-rendering text to an image, or using some other kind of effect for the text outline.

**Closed by AshleyScirra** 2024-11-11 11:46 UTC
Labels: duplicate
