### ISSUE TITLE
Multiple Crash: Searching / editing ImagePoint / Adding Behaviors

### ISSUE THREAD

**Issue by I-N-C-O-G-N-I-T-O** [Scirra/Construct-bugs#7713] opened 2024-01-04 01:08 UTC
## Problem description

Blank project with a single sprite the following triggers a crash.

## Attach a .c3p
[crash_1_3_23.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13824758/crash_1_3_23.c3p.zip)
## Steps to reproduce

1. Searching anything or Find All References.
2. Clicking ImagePoint Button via editor.
3. Add (any) behavior to sprite.

## Observed result

Crash

## Expected result

Not crash

## More details

Chrome/Safari, macOS

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r373/main.js, line 1131, col 65
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'add')
Stack: TypeError: Cannot read properties of undefined (reading 'add') at Ria (https://editor.construct.net/r373/main.js:420:227) at new lr.g.J.Table.qAc (https://editor.construct.net/r373/main.js:1881:173) at pa.j (https://editor.construct.net/r373/main.js:1131:44) at CCG.Fi (https://editor.construct.net/r373/main.js:416:268) at fF.g.J.o2c.ic (https://editor.construct.net/r373/projectResources.js:2924:95) at fF.g.J.o2c.Lo (https://editor.construct.net/r373/projectResources.js:2924:209) at fF.g.J.o2c.Tzb (https://editor.construct.net/r373/projectResources.js:2924:430) at Array. (https://editor.construct.net/r373/projectResources.js:2922:448) at window.pob.dispatchEvent (https://editor.construct.net/r373/main.js:1268:42) at iCa (https://editor.construct.net/r373/projectResources.js:48:376)
Construct version: r373
URL: https://editor.construct.net/r373/
Date: Wed Jan 03 2024 17:06:11 GMT-0800 (Pacific Standard Time)
Uptime: 159.7 s

Platform information
Product: Construct 3 r373 (beta)
Browser: Chrome 120.0.6099.129
Browser engine: Chromium
Context: browser
Operating system: macOS 14.2.1
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5500M OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by Sir-LoLz** [comment] 2024-01-04 03:21
I am having this issue too

**Comment by DiegoScirra** [comment] 2024-01-04 10:22
Duplicate of #7708. This was a regression introduced in r373. It currently affects any place where there is a table showing icons.

**Closed by DiegoScirra** 2024-01-04 10:22 UTC
Labels: duplicate
