### ISSUE TITLE
Follower behavior snaps to initial position, instead of interpolating to position. 

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-bugs#7879] opened 2024-03-05 19:02 UTC
## Problem description

When an object starts to follow another, it immediately teleports to the target objects initial position, instead of gradually moving from its current position to the target's positions. this looks strange when you issue different follow commands when different conditions are met.  and looks worse when there its following by distance and there is a (pixel delay) offset

## Attach a .c3p
there are two examples each in a different layout to illustrate the issue, and there are comments in the events.
https://drive.google.com/file/d/1PLEG_l7rWciSB4GX5V9h2S7ZZ0TLSjTH/view?usp=sharing

## Steps to reproduce

1. add a sprite (player)
2. add a sprite (follower)
3. add follow behavior to follower sprite
4. add top down behavior to player sprite
5. position follower sprite away from player sprite in layout
6. add delay to follow behavior
7. on start of layout start following player instance

## Observed result

the follower teleport instantly to the player. when this happens and the follower is setup with distance and you trigger the follow action it looks janky having the follower teleport to the players offset (see commented example), the follower should be able to interpolate to the targets initial position..

in the example below, the blue cube starts following the pink cube when the pink cube x is greater than the blue cube x, there is also a 100 pixel "delay", since the mode is distance. notice once the condition is trigger the blue clue teleports behind the pink cube.

![follower-blinks](https://github.com/Scirra/Construct-bugs/assets/7579560/f8c32847-6daf-4f60-8957-7a0e44ee42bb)

## Expected result

when the follower starts following instead of teleporting to the targets current position, he should gradually move to that position.  there might be use cases where teleporting is acceptable, but there are lots of use cases where teleporting to it is not. 

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r382

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r382 (beta)
Browser: Edge 122.0.2365.66
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 560 gb
Storage usage (approx): 104 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by brushfe** [comment] 2024-03-07 16:03
I found the same snapping issue, using follow on one sprite with a target using 8-direction

**Comment by AshleyScirra** [comment] 2024-03-08 12:07
This is currently by design. The problem is if you follow something on a 2 second delay, then for the first 2 seconds, there is no data to follow. The Follow behavior avoids changing the object during this time. As soon as data becomes available, then it starts updating the object according to the object history, which means instantly placing it to a historical position. Often this is easy to work around: just place the follow object on top of the followed object and you won't see it change. You could also do other approaches like start it invisible and quickly fade it in as data becomes available.

I don't think it's obvious to say that it should interpolate to the starting position. If you wanted to do something like a fade-in approach, interpolating from the start position to the first history entry might actually interface with that. It also means making an assumption that it knew where the object was X seconds ago, whereas the behavior does not have that data. This is why the behavior has a "Has follow data" condition - it allows the project to decide what to do during that time. You could also use the Tween behavior to implement what you want for the start. There are also other techniques, like instead of changing whether you follow X and Y at runtime, just follow both, and follow an invisible object that sets its X or Y position according to custom logic, and it should also work like you want.

So I don't think there's any obvious change to make here, and there should be some good workarounds, so closing as not a bug - if you do think there should be further improvements made then you can file a suggestion for that.

**Closed by AshleyScirra** 2024-03-08 12:07 UTC
Labels: not a bug

**Comment by brushfe** [comment] 2024-03-08 12:35
@AshleyScirra So is this the same bug as the above? 

https://drive.google.com/file/d/13FAkeVTWoplJ4hnoAeyQO3E6ZXS7m0P7/view?usp=drive_link

This uses Distance follow. Use the arrow keys to move the lead sprite — once it crosses the X coordinate of the follower, the follower snaps to the following distance of 16 pixels (which is visually the same bug as above).

In my example, the follower shouldn't snap. It should only follow once the distance to the lead is >= 16 (this is how every follower i've seen in games works, anyway). 

If this is a different bug, let me know and I'll file a separate issue. Or if this is somehow intended, how would you prevent this snapping?
