### ISSUE TITLE
nw.js 114 error

### ISSUE THREAD

**Issue by johnyc3** [Scirra/Construct-bugs#7110] opened 2023-06-12 20:16 UTC
## Problem description

Building with newest nw.js 114 , the game does not load, and shows this error. (nothing to do with any addons)

![Sprite-0001](https://github.com/Scirra/Construct-bugs/assets/131197974/56d8b176-ed1d-4647-a934-d4d81b2b1aac)

## Attach a .c3p

skymen's file below

## Steps to reproduce

1.skymen's comment below

## Observed result

The game loads black screen

## Expected result

Works

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

344.2 Stable

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Laserwolve** [comment] 2023-06-12 21:09
@johnyc3, this looks like an NW.js issue, with 0.76.1 and newer:
https://github.com/nwjs/nw.js/issues/8075
https://github.com/Laserwolve-Games/DaggerQuest/issues/42
I don't think it's related to Mikal's plugin. [DaggerQuest](https://github.com/Laserwolve-Games/DaggerQuest) has no add-ons and experiences this issue. I was unable to create a minimal reproducible example so I refrained from filing a bug report.

It's most likely related to worker mode. Set `Use worker` to `No` as a temporary workaround.

**Comment by skymen** [comment] 2023-06-12 21:12
Did some testing, as mentionned in the github issue above and yep this isn't linked to Mikal's 3D Object addon
From my testing, this is only broken inside workers, not on the main thread

- Worker disabled:
https://drive.google.com/file/d/1KO2yJpoG3yo7fXO0i64iWeTAwpZG_5-A/view?usp=drive_link

- Worker enabled:
https://drive.google.com/file/d/1_k4_dQT8B1XWPcjUNGnqAAdNGaMxV330/view?usp=drive_link

(Sorry, file too big for Github)

The bug still happens in 0.77.0 but started in 0.76.1 as mentionned in the issue mentionned by @Laserwolve 

version 113 of C3's NW.js uses 0.76.0 and version 114 uses 0.77.0 which is why it's broken only on 114

**Comment by johnyc3** [comment] 2023-06-12 21:37
ok thanks guys. edited

**Comment by AshleyScirra** [comment] 2023-06-15 13:03
This looks like [this bug in NW.js](https://github.com/nwjs/nw.js/issues/8075) so closing this issue as it will be followed-up there.

**Closed by AshleyScirra** 2023-06-15 13:03 UTC
Labels: external
