### ISSUE TITLE
Renaming custom actions crashes the engine

### ISSUE THREAD

**Issue by staarmaan** [Scirra/Construct-bugs#7357] opened 2023-09-01 02:13 UTC
Renaming a custom action crashes the engine, but rarely not always.

## Attach a .c3p
[CustomActionCrash.zip](https://github.com/Scirra/Construct-bugs/files/12492087/CustomActionCrash.zip)

## Steps to reproduce
1.Create any type of object.
2.Create a new custom action for the object.
3.Rename the created custom action to anything else.

## Observed result
The whole engine crashes.
![customActCrashTest1](https://github.com/Scirra/Construct-bugs/assets/109689489/674efcf5-89c6-4c98-9885-6ad12d08956d)
![customActCrashTest2](https://github.com/Scirra/Construct-bugs/assets/109689489/975eabf3-e638-4fbd-9755-cf75ef0b7885)

## Expected result
I expect to being able to rename the actions to anything that's not "Action" and a number, like in past releases.

## More details
Affected browsers/platforms:
Construct 3 App, Windows 11

First affected release:
From r328 onwards. This didn't use to happen to me before, but now it does and it happens in any project and in any release that contains custom actions.

## System details
<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 2 gb
Storage usage (approx): 174 mb (8.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by staarmaan** [comment] 2023-09-01 02:15
Correction:

**Comment by AshleyScirra** [comment] 2023-09-01 11:04
Duplicate of #7321

**Closed by AshleyScirra** 2023-09-01 11:04 UTC
Labels: duplicate
