### ISSUE TITLE
Safari text wrapping bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#6920] opened 2023-04-14 14:06 UTC
## Problem description

The text does not wrap.

## Attach a .c3p

[safari_text_wrapping_bug_r337_2b.zip](https://github.com/WilsonPercival/WilsonPercival/files/11233637/safari_text_wrapping_bug_r337_2b.zip)

## Steps to reproduce

1. Open a project.

## Observed result

![observed](https://user-images.githubusercontent.com/91274932/232067042-4931ec85-631b-4f83-a0f8-23301f40ad8c.png)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/232067055-8373a9f5-dc20-42b3-9167-44bc23e050c3.png)

## More details

**Affected browsers/platforms:** Safari

**First affected release:** broke in r337-2b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r337.2 (beta)
Browser: Safari 15.2
Browser engine: WebKit
Context: browser
Operating system: macOS 10.15.7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

OES_texture_float_linear
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_lose_context
WEBGL_debug_shaders
WEBGL_debug_renderer_info
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
KHR_parallel_shader_compile
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
Supported encode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

H.264 (video/mp4; codecs=avc1.42E01E)

</details>

**Comment by AshleyScirra** [comment] 2023-04-17 10:37
I think this is a duplicate of #4978, caused by this Safari bug: https://bugs.webkit.org/show_bug.cgi?id=46987
I'm afraid there's not much we can do about it - Apple need to fix the issue with Safari.

**Closed by AshleyScirra** 2023-04-17 10:37 UTC
Labels: duplicate, external, safari
