### ISSUE TITLE
Crash When Close Timeline Ease editor dialog

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8314] opened 2024-11-05 03:38 UTC
## Problem description

Crash When Close Timeline Ease editor dialog

![image](https://github.com/user-attachments/assets/772235d6-c290-4e4e-925b-16bed217f3b9)

![image](https://github.com/user-attachments/assets/c5da300c-4f22-4fa3-9b9d-157214b50b05)

![image](https://github.com/user-attachments/assets/fa94b721-61fe-40ce-81ba-50616257197b)

## Steps to reproduce
1. Select a Timline from Project
2. Click 'Edit' of Ease editor
3. close Ease Editor

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2024-11-05 10:55
Do you have an example project? I can't reproduce this from a empty project.

**Comment by DiegoScirra** [comment] 2024-11-07 19:58
This happens when UI animations are turned off.

**Comment by DiegoScirra** [comment] 2024-11-11 16:07
Will be fixed in the next beta.

**Closed by DiegoScirra** 2024-11-11 16:07 UTC
