### ISSUE TITLE
CPU performance leak when using an OR-block

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#7298] opened 2023-08-12 08:16 UTC
## Problem description

This is a pretty odd issue - we noticed that sometimes game performance drops significantly over time, when nothing is really happening on the layout. 
Looks like a condition like this is causing CPU performance leak:

![image](https://github.com/Scirra/Construct-bugs/assets/36763350/67588a4d-98da-4b79-be05-d730c0d7343a)

## Attach a .c3p

[CPU_leak.zip](https://github.com/Scirra/Construct-bugs/files/12326906/CPU_leak.zip)

## Steps to reproduce

1. Run in debug mode, keep the window focused and observe CPU utilization.

## Observed result

CPU utilization for that particular event grows:

![image](https://github.com/Scirra/Construct-bugs/assets/36763350/15dbc093-ef9a-40b9-ae22-7fd4cf932aa9)

## Expected result

No performance drop.

## More details

Changing the order of conditions in the event fixes the problem.

## System details

<details><summary>View details</summary>
Platform information
Product: Construct 3 r353 (beta)
Browser: Chrome 115.0.5790.171
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 265 gb
Storage usage (approx): 3.5 gb (1.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DinoSystem** [comment] 2023-08-12 20:04
I thin this is due to the fact CPU output scales with the needed power: if you have an example project which does basically nothing, the CPU work at its minimum, so even a performant event is shown using a high % of CPU power.

**Comment by nerdError** [comment] 2023-08-12 22:12
> I thin this is due to the fact CPU output scales with the needed power: if you have an example project which does basically nothing, the CPU work at its minimum, so even a performant event is shown using a high % of CPU power.

Its not really important what absolute value is in this case. As i understand the OP, the problem is that it's increases over time (from 2% to 20%), so relatively it is 10x increase and this is already a lot

**Comment by DinoSystem** [comment] 2023-08-12 23:22
> Its not really important what absolute value is in this case. As i understand the OP, the problem is that it's increases over time (from 2% to 20%), so relatively it is 10x increase and this is pretty a lot
> 
> And anyway, just the fact that it does increase over time is very suspicions already

Good point

**Comment by dop2000** [comment] 2023-08-13 00:49
Yeah, in a real game after a few idle minuted the performance drop is so big, the game becomes unplayable.

**Comment by DinoSystem** [comment] 2023-08-13 00:54
I suggest uploading the example as a single file instead of a folder, would make it easier for Scirra

**Comment by dop2000** [comment] 2023-08-13 00:57
> I suggest uploading the example as a single file instead of a folder, would make it easier for Scirra

It's a C3P file renamed to ZIP, because github doesn't allow attaching c3p files.

**Comment by AshleyScirra** [comment] 2023-08-14 14:48
It turns out there was an internal array not being cleared in this specific case, so it was gradually piling up more and more work over time. (OR blocks have super complicated code in the engine which varies a lot depending on the specific conditions used - somewhat regrettable but we're stuck with it for now.) It should be fixed in the next beta.

**Closed by AshleyScirra** 2023-08-14 14:48 UTC
