### ISSUE TITLE
Bug with list object and unwanted scrolling

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-bugs#8286] opened 2024-10-18 21:05 UTC
## Problem description

Creating an html object on a different layer than a list object, scrolls the list objects back to the top.

Firstly I'm not sure who is the culprit here, the list object or the html object, or the list with a combination of any other DOM object.
This only happens if the list object and the created html object are not on the same layer, when they are on the same layer it works as it should.

## Attach a .c3p

[listBug.zip](https://github.com/user-attachments/files/17440665/listBug.zip)

## Steps to reproduce

1. Scroll down the list.
2. Click the search button.

## Observed result

List scrolls back to start.

## Expected result

List stays at current scroll position.

## More details

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:** Tested on the latest beta.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2024-10-24 16:39
This specific case should be fixed in the next beta, but note it's difficult to avoid this in general: the problem here is a HTML element is created underneath the list in Z order. If the element is removed and reinserted to the DOM, then its state is reset, which is why the scroll position goes back to the top - this is a long standing issue with the way the DOM works. Therefore sometimes doing other changes to Z order will still force Construct to move the element in the DOM and cause it to be reset. However in the next beta Construct is a bit smarter about how it does this and tries to preserve existing elements as much as possible, so hopefully the problem is mitigated in common cases.

**Closed by AshleyScirra** 2024-10-24 16:39 UTC

**Comment by avishaymizrav** [comment] 2024-10-24 16:54
Great, thank you!

**Comment by avishaymizrav** [comment] 2024-11-06 01:00
@AshleyScirra There are still some issues with this.
When I scroll the bottom layer (where the html objects are created) it keeps resetting the scroll position of the listbox.

Sometimes it even go above the z-index of a textbox that is on a layer above it, not sure when though, sometimes it does, sometimes it doesn't, I'm still trying to figure out what the conditions are.
