### ISSUE TITLE
I found a way to break the "update addon" button :)

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7176] opened 2023-07-06 18:51 UTC
## Problem description

Hello!

This one is a very weird one.

Here are two addons:

[Both Animate Text addons.zip](https://github.com/Scirra/Construct-bugs/files/11971255/Both.Animate.Text.addons.zip)

Both are the "same addon", same ID at least.

The newer one is a complete rewrite of the addon using my new addon framework, but it contains the same code.
When I install either one on its own, it works fine, but if I "update" the older addon into the newer one, I get this error message

![image](https://github.com/Scirra/Construct-bugs/assets/11213825/06074adf-d045-4e20-b79e-90a965219bf9)

It looks like the old addon isn't being overwritten by the new one for some reason

## Attach a .c3p

n/a

## Steps to reproduce

1. Install 1.0.3.9
2. Install 1.1.0.2
3. Go in safe mode
4. Uninstall 1.1.0.2

## Observed result

Error when installing the 2nd, and when uninstalling it in safe mode, the old addon is still installed

## Expected result

Old addon should be overwritten

## More details

I've never had this issue before, but one big thing this new framework does is completely change the addon structure, so the addon.json isn't the same, the files being loaded are the same either.

**Affected browsers/platforms:** Most likely all of them

**First affected release:** No idea

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by skymen** [comment] 2023-07-06 18:53
While I'm here, this bug was "unfixed" maybe a year or two ago and I never bothered reporting it again
https://github.com/Scirra/Construct-bugs/issues/1306

Same thing, update a normal addon with a developer addon and it breaks.

**Comment by AshleyScirra** [comment] 2023-07-07 15:23
Seems to work fine for me in r348. No error occurs when installing the updated addon and it can be uninstalled again successfully without needing safe mode.

Not sure what you're seeing but maybe it's something to do with a bad configuration involving developer mode? If I can't reproduce there's nothing I can do, so closing, but you can file again if you find there is a missing step or something.

**Closed by AshleyScirra** 2023-07-07 15:23 UTC
Labels: can't reproduce, sdk

**Comment by skymen** [comment] 2023-07-08 00:21
No clue what happened. I cleanly uninstalled the addon and tried again and it works fine now.
