### ISSUE TITLE
Is touching object in OR blocks always return true when it shouldn't

### ISSUE THREAD

**Issue by letnrodrigues** [Scirra/Construct-bugs#7968] opened 2024-04-24 22:45 UTC
## Problem description

A block checking for "Is touching ObjectA OR Is touching ObjectB" always return true even if you are not touching any of these objects if a condition is true in the level above.

![image](https://github.com/Scirra/Construct-bugs/assets/29272812/6c52277b-f3f6-462e-b136-c2a698f59033)
Simply adding the condition to verify if a instance variable in objectB is true breaks the OR block. If this arbitrary condition is removed, the OR block works as intended (being true only if any of the objects are in fact being touched).

## Attach a .c3p

[OR block bug.zip](https://github.com/Scirra/Construct-bugs/files/15101553/OR.block.bug.zip)

## Steps to reproduce

1. Create two arbitrary objects
2. Add the Touch object
3. Create an on any touch start event
4. Add any condition relating to one of the objects to the on any touch start event
5. Add a OR block checking if either the objects are being touched

## Observed result

Observe that the OR block will always be true even if any the objects are not being touched.

## Expected result

The OR block should only return true if its established conditions are met.

## More details

**Affected browsers/platforms:** Tested only in Chrome.

**First affected release:** This started to happen on r388 and did not happen on r379.

**Comment by WilsonPercival** [comment] 2024-04-25 02:35
You wrote that it worked well in `r379s`, although it didn't. I opened your project in `r379s` version and can reproduce the same error.

Duplicate of https://github.com/Scirra/Construct-bugs/issues/7912

**Comment by letnrodrigues** [comment] 2024-04-25 03:39
Interesting. This minimal project is reproduction of a more complex code that we use that works as expected in r379 but behaves like this in r388.

**Comment by WilsonPercival** [comment] 2024-04-25 03:53
In that case, I guess the problem lies elsewhere.

**Comment by AshleyScirra** [comment] 2024-04-25 13:12
Here is a version of the project that can be opened in r379: [issue7968.zip](https://github.com/Scirra/Construct-bugs/files/15110439/issue7968.zip)

I cannot observe any difference in how the project works between r379 and r388.2, so there does not appear to have been any change or regression with this project.

If a different project is affected, it is possible it was previously relying on a bug to work correctly which has now been fixed, as explained in #7967.

**Closed by AshleyScirra** 2024-04-25 13:12 UTC
Labels: can't reproduce

**Comment by amyhapple** [comment] 2024-04-25 13:49
If it helps with the solution, I noticed that by removing the comparison event from the ObjectB variable, the code starts to work normally. Just like moving this condition after the Pick Object using OR.
But really, this comparison should work normally at the beginning of the code.
