### ISSUE TITLE
Audio: Fade to Stop then Audio: Play --> Doesn't work with Firefox

### ISSUE THREAD

**Issue by plazatin** [Scirra/Construct-bugs#8272] opened 2024-10-03 11:00 UTC
## Problem description

Fade to Stop then Play doesn't work with Firefox. Need to fade back in. Volume shows correctly and the file is playing but still need to fade it in.

## Attach a .c3p
[firefox-fade-audio-play-issue.zip](https://github.com/user-attachments/files/17243013/firefox-fade-audio-play-issue.zip)

## Steps to reproduce

1. Play Music
2. Fade Out to Stop
3. Play again 

![image](https://github.com/user-attachments/assets/3d188db8-4067-4a6e-b1e2-4b8d07e7a480)
![image](https://github.com/user-attachments/assets/a70223b1-5fc6-49e6-a93a-d44f4d269945)

## Observed result
No sound in FFox. Firefox debug shows the file being played at normal volume, but it still doesn't have any sound coming out unless you fade in.

## Expected result
Fade to Stop, then play again should play the audio.

## More details

**Affected browsers/platforms:** 
Issue on Firefox mobile (android) and desktop

**First affected release:** 
Don't know when but I am on r407.2. I did see someone run into this issue accidentally several months back, maybe around March 2024, when he showed me a recording of my game (back then I thought it was a slow loading issue, but I later realized the music had already played, it should already be loaded), so I believe this issue has been around for quite some time now..

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r407.2 (stable)
Browser: Chrome 129.0.6668.60
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 310 gb
Storage usage (approx): 157 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB (0x00001C03) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment] 2024-10-08 16:24
I think this is a duplicate of #7480 which is caused by a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1860581

I'm afraid Mozilla need to fix that - I commented on the issue it was merged in to asking for an update.

**Closed by AshleyScirra** 2024-10-08 16:24 UTC
Labels: duplicate, external, firefox
