### ISSUE TITLE
Save is broken in 372!

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#7683] opened 2023-12-19 00:25 UTC
Save/Load game seems to be broken in 372.

1. Create a new project
2. Set up an event that changes an instance on a timer (es. every X sec append "." to text)
3. Set up Key to save
4. Run the project and save

Result: Game freezes!
Expected: game works as normal

In my project, it also shows an error on game load, as well as not running events on "on save load".

I hopw this is fixed in 372.2 as it's a major issue for my project :(

**Comment by WilsonPercival** [comment] 2023-12-19 00:33
Minimum project: 
[issue7683.zip](https://github.com/Scirra/Construct-bugs/files/13709703/issue7683.zip)

Steps to reproduce:
1. Open a project.
2. Launch and open the console.
3. Press `1`.

**Comment by DinoSystem** [comment] 2023-12-19 00:43
This also used to happen **very rarely** before 372

**Comment by DiegoScirra** [comment] 2023-12-19 11:38
Closing as duplicate of #7679

**Closed by DiegoScirra** 2023-12-19 11:38 UTC
