### ISSUE TITLE
Browser.WentOnline/Offline not workin in apk

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#8078] opened 2024-06-21 12:16 UTC
## Problem description

The Browser's Went Online/Offline events are not working on android apk (debug apk)

## Attach a .c3p

1. install the apk on an android phone
2. disable wifi/network

## Observed result
Text remains the same

## Expected result
Text should say "Offline"

**Comment by AshleyScirra** [comment] 2024-06-21 13:12
Looks like a duplicate of #5693.

**Closed by AshleyScirra** 2024-06-21 13:12 UTC
Labels: duplicate
