### ISSUE TITLE
Bug Crash error when try export using Nwjs v111 linux 64

### ISSUE THREAD

**Issue by JonaszO** [Scirra/Construct-bugs#6832] opened 2023-03-27 10:04 UTC
![craSH](https://user-images.githubusercontent.com/22713396/227910746-816e9c3f-0cb7-40f4-81d9-8baccbfc27d0.png)

**Comment by JonaszO** [comment] 2023-03-27 10:25
also v 110 cause crash ( ithin when minyfing script using advanced method)

**Comment by DiegoScirra** [comment] 2023-03-27 11:20
This doesn't reproduce on a blank project. Please provide a project that reproduces the problem. Having said that and given what the error looks like, this might be an internet connection issue, which asides from giving better feedback instead of crashing, there isn't much we can do about.

**Comment by AshleyScirra** [comment] 2023-04-03 11:57
Works for me and report is not actionable so closing.

**Closed by AshleyScirra** 2023-04-03 11:57 UTC
Labels: ignored guidelines, can't reproduce
