### ISSUE TITLE
Bug with debugger and dialog

### ISSUE THREAD

**Issue by DeividHiGamboa** [Scirra/Construct-bugs#6598] opened 2023-02-22 03:45 UTC
## Problem description
In the dialog there is an error with the debugger, when you click to exit the breakpoint does not change and you have to go to cpu and click run to remove it, which does not happen in browser tab and popup window, I hope they solve this since it is annoying to use breakpoints like this, thanks in advance

## Attach a .c3p

[Bug dialog.zip](https://github.com/Scirra/Construct-3-bugs/files/10799782/Bug.dialog.zip)
## Steps to reproduce

https://user-images.githubusercontent.com/109392555/220513917-f46a39bd-8bc0-4d7c-9e68-51def7b28d77.mp4
## Observed result
When closing the dialog the breakpoint does not change

## Expected result

That when closing the dialog the point of interruption returns to the normal state
## More details

**Affected browsers/platforms:** 
Windows 10/Chrome/Edge and maybe on other platforms and browsers

**First affected release:** 
i dont know
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 110.0.5481.97
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 545 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 600 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-02-22 11:54
I can't reproduce this. For me closing the debugger does clear the breakpoint state after a moment.

Do you have any browser extensions or privacy settings that might be blocking detection of a popup window being closed?

**Comment by WilsonPercival** [comment] 2023-02-22 13:29
> I can't reproduce this. For me closing the debugger does clear the breakpoint state after a moment.
> 
> Do you have any browser extensions or privacy settings that might be blocking detection of a popup window being closed?

@AshleyScirra I can reproduce. But it doesn't work in the `Default` theme. This works in the `Dark` theme. It seems to me that you should give greater importance to the choice of topic, because it is often the decisive moment for the ability to reproduce the problem.

![aa](https://user-images.githubusercontent.com/91274932/220633760-d39fadf4-238d-4af1-bd14-6513fbcad043.png)

**Comment by DeividHiGamboa** [comment] 2023-02-22 14:53
> I can't reproduce this. For me closing the debugger does clear the breakpoint state after a moment.
> 
> Do you have any browser extensions or privacy settings that might be blocking detection of a popup window being closed?

I think I don't have any settings that prevent this because the popup works fine, it's just the dialog that doesn't work, there must be something wrong, try with the dark theme so maybe you can reproduce it

**Comment by DeividHiGamboa** [comment] 2023-02-22 14:56
> > I can't reproduce this. For me closing the debugger does clear the breakpoint state after a moment.
> > Do you have any browser extensions or privacy settings that might be blocking detection of a popup window being closed?
> 
> @AshleyScirra I can reproduce. But it doesn't work in the `Default` theme. This works in the `Dark` theme. It seems to me that you should give greater importance to the choice of topic, because it is often the decisive moment for the ability to reproduce the problem.
> 
> ![aa](https://user-images.githubusercontent.com/91274932/220633760-d39fadf4-238d-4af1-bd14-6513fbcad043.png)

I'll try the default theme to see if it works as expected

**Comment by DeividHiGamboa** [comment] 2023-02-22 23:57
> > I can't reproduce this. For me closing the debugger does clear the breakpoint state after a moment.
> > Do you have any browser extensions or privacy settings that might be blocking detection of a popup window being closed?
> 
> @AshleyScirra I can reproduce. But it doesn't work in the `Default` theme. This works in the `Dark` theme. It seems to me that you should give greater importance to the choice of topic, because it is often the decisive moment for the ability to reproduce the problem.
> 
> ![aa](https://user-images.githubusercontent.com/91274932/220633760-d39fadf4-238d-4af1-bd14-6513fbcad043.png)

It doesn't work for me with any theme, what will it be?

**Comment by WilsonPercival** [comment] 2023-02-23 00:15
> 

@AshleyScirra I don't know.

**Comment by WilsonPercival** [comment] 2023-02-23 00:15
> > > I can't reproduce this. For me closing the debugger does clear the breakpoint state after a moment.
> > > Do you have any browser extensions or privacy settings that might be blocking detection of a popup window being closed?
> > 
> > 
> > @AshleyScirra I can reproduce. But it doesn't work in the `Default` theme. This works in the `Dark` theme. It seems to me that you should give greater importance to the choice of topic, because it is often the decisive moment for the ability to reproduce the problem.
> > ![aa](https://user-images.githubusercontent.com/91274932/220633760-d39fadf4-238d-4af1-bd14-6513fbcad043.png)
> 
> It doesn't work for me with any theme, what will it be?

I don't know.

**Comment by AshleyScirra** [comment] 2023-02-23 11:09
It worked for me fine with the dark theme too. So I suspect it is not to do with the theme, hence why I asked if you have any browser extensions or privacy settings that might be blocking detection of a popup window being closed. @DeividHiGamboa - can you answer that question?

**Comment by DeividHiGamboa** [comment] 2023-02-23 19:59
> It worked for me fine with the dark theme too. So I suspect it is not to do with the theme, hence why I asked if you have any browser extensions or privacy settings that might be blocking detection of a popup window being closed. @DeividHiGamboa - can you answer that question?

Hello, no, I don't have any extension or configuration that blocks this, I tried with edge and firefox and the same thing also happens, maybe it's because my pc is low-end, have you tried construct on a 4gb ram pc and an intel celeron? If it works as it should then I don't know what causes the problem, I await your response to try to find a solution to this

**Comment by AshleyScirra** [comment] 2023-03-17 11:31
I can't reproduce this at all, and I've looked over the code and I can't understand why this wouldn't work. It clears the breakpoint highlight when the debug window is closed, and it all looks like it's coded and working fine to me. I'm afraid that means there's no way to further investigate this, so closing the issue.

**Closed by AshleyScirra** 2023-03-17 11:31 UTC
Labels: can't reproduce
