### ISSUE TITLE
There is no way to know what height the keyboard is on android/ios

### ISSUE THREAD

**Issue by DeividHiGamboa** [Scirra/Construct-bugs#7343] opened 2023-08-28 23:41 UTC
## Problem description

In the browser, if there is a text entry that can be hidden with the keyboard, it goes up and is not hidden, but in an apk this happens and the text entry is hidden below the keyboard, I was thinking that they could use keyboard api to be able to know the height of the keyboard
Link: [Keyboard api](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard_API) 

I hope you can add this because it is very useful for chats and more functions. Thanks in advance

## Attach a .c3p

Create a blank project

## Steps to reproduce

1.create project
2.Add text entry and put it at the bottom
3.export to android 
And this is how it looks like the keyboard covers the text input
## Observed result

Keyboard covers text input
## Expected result
That there is a way to know the height of the keyboard to put the text input above the keyboard

## More details

**Affected browsers/platforms:** 
Affects android and ios, in exports not in browser

**First affected release:** 
I have always believed

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2023-08-29 10:57
This appears to be a feature request and not a bug report, and it looks like it was already posted as a suggestion [here](https://construct23.ideas.aha.io/ideas/C23-I-386) as well, so closing.

**Closed by AshleyScirra** 2023-08-29 10:57 UTC
Labels: enhancement
