### ISSUE TITLE
Video playback fails on iPad 7th Generation

### ISSUE THREAD

**Issue by ma6x** [Scirra/Construct-bugs#8363] opened 2024-12-18 19:26 UTC
## Problem description

Videos do not play in Safari or in xcode exports on the iPad 7th Generation regardless of iOS. I’ve tested multiple formats (MP4 H.264, H.265, AV1), and the issue seems isolated to this device. The same videos work fine on all other iOS devices tested. **This is a problem because you cannot exclude iPad 7th gen devices from being able to run the project as they are supported by iOS 18 too.**

## Attach a .c3p

[videotest.c3p.zip](https://github.com/user-attachments/files/18187897/videotest.c3p.zip)

## Steps to reproduce

(if you have an iPad 7th Generation available)

1. Remote preview the project and open it on safari with an iPad 7th generation.
2. Observe how as it cycles through each video the screen remains grey as they are unable to play.
3. Repeating this process on any other apple device shows that at least some of the videos do play.

(if you DO NOT have an iPad 7th Generation available)

1. Export the project to Xcode
2. Run the project with a simulator of the ipad 10th generation. 
3. Observe how as it cycles through each video the screen remains grey as they are unable to play.
4. Repeating this process on any other apple device simulator shows that at least some of the videos do play.

## Observed result

The videos do not play when running on an iPad 7th gen or on a simulator of the same device.

## Expected result

The videos should play like on other devices.

## More details
I have already reported this bug to apple, but I thought it would be worth reporting here as well. 
https://bugs.webkit.org/show_bug.cgi?id=284891

**Comment by AshleyScirra** [comment] 2024-12-20 14:50
I'm afraid we don't have that specific device to test on at the moment, but the project does appear to correctly play the H.264 and WebM format videos on an iPad 5th generation with iOS 17 and an iPhone 12 Pro Max with iOS 18.1 which are the devices I have immediately to hand.

Such issues are very likely to do with the system software for that specific model of iPad - likely a graphics driver bug as that is the most common cause of this type of issue. The browser handles video decoding, not Construct. Further if the problem was caused by Construct, it would likely affect every device, not just a specific device. So I'm afraid this is out of our control and only Apple will be able to fix this. As you already filed an issue with Apple I'm closing this issue as it will be followed up there - I added myself to follow that issue. It may be useful to upload the video files to a server somewhere and see if the issue reproduces in the Safari browser loading the videos directly, as that would be an easier way to reproduce the issue and possibly help it get fixed quicker.

**Closed by AshleyScirra** 2024-12-20 14:50 UTC
Labels: iOS
