### ISSUE TITLE
Unhandled rejection sound crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#6533] opened 2023-02-14 19:11 UTC
## Problem description

Construct crashes.

## Attach a .c3p

[baba.zip](https://github.com/WilsonPercival/WilsonPercival/files/10735952/baba.zip)

save open project: [save_open_project.zip](https://github.com/WilsonPercival/WilsonPercival/files/10735957/save_open_project.zip)

## Steps to reproduce

1. Open a project.
2. Create a folder in the `Sounds` folder.
3. Drag the file to the new folder.
4. Press Ctrl + X and then Ctrl + V.

## Observed result

https://user-images.githubusercontent.com/91274932/218832959-f4713776-cb58-4315-bc9d-1b7a633a9f31.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'rP') @ TypeError: Cannot read properties of null (reading 'rP') at nV (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:52:437) at Array. (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:87:410) at window.ueb.dispatchEvent (https://editor.construct.net/r330/main.js:1235:42) at window.ueb.U0 (https://editor.construct.net/r330/main.js:2513:491) at d.Za (https://editor.construct.net/r330/projectResources.js:941:255) at v (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:67:375) at async Promise.all (index 0) at async y (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:67:472)
Stack: TypeError: Cannot read properties of null (reading 'rP') at nV (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:52:437) at Array. (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:87:410) at window.ueb.dispatchEvent (https://editor.construct.net/r330/main.js:1235:42) at window.ueb.U0 (https://editor.construct.net/r330/main.js:2513:491) at d.Za (https://editor.construct.net/r330/projectResources.js:941:255) at v (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:67:375) at async Promise.all (index 0) at async y (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:67:472)
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Tue Feb 14 2023 20:47:07 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 56.4 s

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r330b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 193 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-02-15 16:24
I can't seem to reproduce this. When I press Ctrl+X then nothing is selected in the project bar so I can't paste anything. If I select the 'Sounds' folder and paste, it works fine. I can't really see what you're doing in the video because I can't see when you press keyboard shortcuts (one of the reasons the written list of steps to reproduce is more useful than the video). Am I missing something?

**Comment by WilsonPercival** [comment] 2023-02-15 16:36
> I can't seem to reproduce this. When I press Ctrl+X then nothing is selected in the project bar so I can't paste anything. If I select the 'Sounds' folder and paste, it works fine. I can't really tell what you're doing in the video because I can't see when you press keyboard shortcuts (one of the reasons the written list of steps to reproduce is more useful than the video). Am I missing something?

@AshleyScirra I recorded another video to reproduce the problem. Play steps:

1. Open a project.
2. Create a folder in the `Sounds` folder.
3. Drag the file to the new folder.
4. Right click on the new folder to open the context menu.
5. Click `Cut` in the context menu. You will notice that the new folder is still selected and there is a huge window to take the next step.
6. Press Ctrl + V.

https://user-images.githubusercontent.com/91274932/219092699-5a62455b-6e3f-4235-8892-ab4cdc62dbce.mp4

**Comment by GeekManOfficial** [comment] 2023-02-16 13:29
https://user-images.githubusercontent.com/95054989/219377688-b8c712e8-9440-4437-a1c4-b5a65c2e4e1c.mp4

i can reproduce this

**Comment by AshleyScirra** [comment] 2023-02-20 15:01
I still can't reproduce this one - the item disappears immediately when I press 'Cut'. However I suspect it is similar to other issues filed recently and we have some general improvements in this area for handling rapid operations before they have completed, so marking to check when the next release is out.

**Comment by AshleyScirra** [comment] 2023-02-21 15:39
r331 is now out, please check again there.

**Comment by WilsonPercival** [comment] 2023-02-21 15:51
> r331 is now out, please check again there.

@AshleyScirra I can still repeat the crash. It seems that I have reduced the time window. So I should reduce the idle time between Ctrl + X and Ctrl + V button presses.

https://user-images.githubusercontent.com/91274932/220393830-5daf9ec8-b52c-46c8-ac4e-c1b17d5b9d2e.mp4

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at O.i (https://editor.construct.net/r331/main.js:1035:147) at CCG.mh (https://editor.construct.net/r331/main.js:377:410) at EU (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:1:156) at Jeb (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:68:236) at async CCG.dn (https://editor.construct.net/r331/main.js:882:324)
Stack: TypeError: unexpected type at O.i (https://editor.construct.net/r331/main.js:1035:147) at CCG.mh (https://editor.construct.net/r331/main.js:377:410) at EU (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:1:156) at Jeb (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:68:236) at async CCG.dn (https://editor.construct.net/r331/main.js:882:324)
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Tue Feb 21 2023 17:47:31 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 91.5 s

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment] 2023-03-17 11:19
I eventually figured out how to reproduce this one. It should be fixed in the next release cycle.

**Closed by AshleyScirra** 2023-03-17 11:19 UTC
