### ISSUE TITLE
Error: released image asset which still has texture references

### ISSUE THREAD

**Issue by rilem** [Scirra/Construct-bugs#7954] opened 2024-04-20 13:15 UTC
## Problem description

I load a custom texture from an URL when my objects are created. When I try to load a texture from URL at a later point, the project throws an error and the texture is not loaded.

## Attach a .c3p

[texture load issue.zip](https://github.com/Scirra/Construct-bugs/files/15048302/texture.load.issue.zip)

## Steps to reproduce
R387 Beta

1. run scene
2. open browser console
3. click on the tiled background
4. look at console

## Observed result

Texture is not loaded (unless the first instance is clicked, but error is still shown).

## Expected result

Texture is loaded correctly from the project files.

## More details

This used to work in a previous release without issues. Not sure when, it's been a while since I opened the project this is related to.

**Comment by MikalDev** [comment] 2024-04-20 19:04
Seeing something when switching layouts and with tilemap and load from URL

<img width="690" alt="c3ImageAssetError" src="https://github.com/Scirra/Construct-bugs/assets/33675273/c94a8665-7ea1-405f-9fb0-6cf47d81b5bd">

See the first error (the other errors are different trying to debug and crate a repo case, they are probably unrelated.)

**Comment by MikalDev** [comment] 2024-04-21 03:19
Looks like something to do with releasing an image asset with multiple references. It behaves differently between r382 and r383, it looks like in r382 the releasetextures() call is not done, but in r383 it is called and in my case tries to release when there are 6 other refs outstanding and throws the error.

**Comment by MikalDev** [comment] 2024-04-21 03:26
Trying the above test project it also fails between r382 -> r383

**Comment by AshleyScirra** [comment] 2024-04-23 11:50
This is a regression from the implementation of dynamic Sprite animations in r383. The timing is quite tricky as this is a regression since the previous stable release, and we are due a new stable release imminently, which makes it a high risk time to introduce a new fix. I don't think it merits delaying the stable release though, so the fix for this is included in r388 stable which will be out shortly, and hopefully it will be OK.

**Closed by AshleyScirra** 2024-04-23 11:50 UTC

**Comment by krishnaraj9** [comment] 2024-04-23 21:17
My game got stuck after updating C3 to r388. It is showing this error in console.

"Error: released image asset which still has texture references"

**Comment by MikalDev** [comment] 2024-04-24 00:29
r388 fixed my issue, I no longer get the Error released image asset, thanks Ashley.
