### ISSUE TITLE
player stuck or freeze on move thorough object randomely

### ISSUE THREAD

**Issue by worldruller** [Scirra/Construct-bugs#7753] opened 2024-01-18 07:30 UTC
## Problem description

when player jump on jump through game object behaviours then player sometime stuck on that object like freeze on them

## Attach a .c3p
[JumpGitProj.zip](https://github.com/Scirra/Construct-bugs/files/13973373/JumpGitProj.zip)

## Steps to reproduce

1. open proj
2. start playe and after some time randomely player stuck on object
3.

## Observed result

player stuck or freeze 

## Expected result

player should be jumped of that object

## More details

simple bounce game

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment] 2024-01-18 08:04
Can not reproduce.

**Comment by WilsonPercival** [comment] 2024-01-18 08:24
> > Can not reproduce.
> 
> can you try more .it happen randomely

@worldruller Can you record a video showing how the character is stuck?

**Comment by worldruller** [comment] 2024-01-18 08:37
[Uploading Construct 3 2024-01-18 14-03-12.zip…]()
here is the video

**Comment by WilsonPercival** [comment] 2024-01-18 08:46
> Uploading Construct 3 2024-01-18 14-03-12.zip… here is the video

Once you move a video file, you need to wait for it to download instead of posting a comment.

**Comment by worldruller** [comment] 2024-01-18 08:52
> > Uploading Construct 3 2024-01-18 14-03-12.zip… here is the video
> 
> Once you move a video file, you need to wait for it to download instead of posting a comment.

did you have video ?

**Comment by worldruller** [comment] 2024-01-18 09:01
> > > > Uploading Construct 3 2024-01-18 14-03-12.zip… here is the video
> > > 
> > > 
> > > Once you move a video file, you need to wait for it to download instead of posting a comment.
> > 
> > 
> > did you have video ?
> 
> No, because you didn't wait for it to load.

sorry, here is the video
[Uploading Construct 3 2024-01-18 14-03-12.zip…]()

**Comment by worldruller** [comment] 2024-01-18 09:01
try new project, it should be work, it show how exactly issue is occur

**Comment by WilsonPercival** [comment] 2024-01-18 09:07
> > > > > Uploading Construct 3 2024-01-18 14-03-12.zip… here is the video
> > > > 
> > > > 
> > > > Once you move a video file, you need to wait for it to download instead of posting a comment.
> > > 
> > > 
> > > did you have video ?
> > 
> > 
> > No, because you didn't wait for it to load.
> 
> sorry, here is the video Uploading Construct 3 2024-01-18 14-03-12.zip…

You didn't wait for it to load, so I can't watch it.

**Comment by worldruller** [comment] 2024-01-18 09:10
[Construct 3 2024-01-18 14-03-12.zip](https://github.com/Scirra/Construct-bugs/files/13974383/Construct.3.2024-01-18.14-03-12.zip)

**Comment by worldruller** [comment] 2024-01-18 09:10
try now

**Comment by worldruller** [comment] 2024-01-18 09:25
did you get it ?some time player also freeze on tile exactly on tile

**Comment by worldruller** [comment] 2024-01-18 10:03
hello,hi did you understand issue ?

**Comment by WilsonPercival** [comment] 2024-01-18 11:35
@worldruller Why is the video on a completely different level than the one you provided as a project file?

**Comment by worldruller** [comment] 2024-01-18 11:50
it is same

**Comment by worldruller** [comment] 2024-01-18 11:50
are you seeing new project ?

**Comment by WilsonPercival** [comment] 2024-01-18 12:02
@worldruller The project you attached does not have rotated platforms. This is the platform the character in the video is stuck on.

**Comment by worldruller** [comment] 2024-01-18 12:09
that's is not different there is just randomness of rotation tile that, some of them are in normal and some of them are in rotated.
what you just saw on video ,that player stuck on rotated tile, player also stuck on flat tile and it happen randomly. If you know this pls help me

**Comment by WilsonPercival** [comment] 2024-01-18 12:14
> that's is not different there is just randomness of rotation tile that, some of them are in normal and some of them are in rotated. what you just saw on video ,that player stuck on rotated tile, player also stuck on flat tile and it happen randomly. If you know this pls help me

I asked you to make a video of the character getting stuck in the project you attached.

**Comment by worldruller** [comment] 2024-01-18 12:15
video is from that project

**Comment by AshleyScirra** [comment] 2024-01-18 12:16
The project uses the Platform behavior on an animated sprite whose collision polygon changes between frames. In the [documentation](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/platform) it advises to do this instead:

> For the most reliable platform movement, it is recommended to use a invisible rectangle sprite with no animations with the Platform movement. Then, the animated player object can be positioned on top of that. Otherwise, the changing size and collision polygon of the object as its animation plays can interfere with the Platform movement's floor, wall and slope detection, causing a shaking or glitchy movement.

So this looks like a mistake in the project, so closing.

**Closed by AshleyScirra** 2024-01-18 12:16 UTC
Labels: not a bug

**Comment by worldruller** [comment] 2024-01-18 12:22
> The project uses the Platform behavior on an animated sprite whose collision polygon changes between frames. In the [documentation](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/platform) it advises to do this instead:
> 
> > For the most reliable platform movement, it is recommended to use a invisible rectangle sprite with no animations with the Platform movement. Then, the animated player object can be positioned on top of that. Otherwise, the changing size and collision polygon of the object as its animation plays can interfere with the Platform movement's floor, wall and slope detection, causing a shaking or glitchy movement.
> 
> So this looks like a mistake in the project, so closing.

why you closed this . i didn't understand this .

**Comment by worldruller** [comment] 2024-01-18 12:27
> The project uses the Platform behavior on an animated sprite whose collision polygon changes between frames. In the [documentation](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/platform) it advises to do this instead:
> 
> > For the most reliable platform movement, it is recommended to use a invisible rectangle sprite with no animations with the Platform movement. Then, the animated player object can be positioned on top of that. Otherwise, the changing size and collision polygon of the object as its animation plays can interfere with the Platform movement's floor, wall and slope detection, causing a shaking or glitchy movement.
> 
> So this looks like a mistake in the project, so closing.

what should i do in this? it is because of player animation ?

**Comment by worldruller** [comment] 2024-01-18 13:06
> The project uses the Platform behavior on an animated sprite whose collision polygon changes between frames. In the [documentation](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/platform) it advises to do this instead:
> 
> > For the most reliable platform movement, it is recommended to use a invisible rectangle sprite with no animations with the Platform movement. Then, the animated player object can be positioned on top of that. Otherwise, the changing size and collision polygon of the object as its animation plays can interfere with the Platform movement's floor, wall and slope detection, causing a shaking or glitchy movement.
> 
> So this looks like a mistake in the project, so closing.

how to solve this, please guid me

**Comment by AshleyScirra** [comment] 2024-01-19 14:00
Try this tutorial which covers correctly setting up a Platform behavior: https://www.construct.net/en/tutorials/platformer-game-2329
