### ISSUE TITLE
Mirroring messes up Sine behavior angles of hierarchy children

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#8245] opened 2024-09-23 18:40 UTC
## Problem description

Mirroring an object causes Sine behavior to be messed up in all hierarchy children.

## Attach a .c3p
[test mirror.zip](https://github.com/user-attachments/files/17102612/test.mirror.zip)

## Steps to reproduce

1. Click "Mirror"

## Observed result
Sine behavior angle is messed up.

## Expected result
Sine behavior angle updates relative to the new angle.

**Comment by Alaadel** [comment] 2024-09-24 05:53
Update: there is a [workaround](https://www.construct.net/en/forum/construct-3/general-discussion-7/mirroring-messes-sine-183691#forumPost1113230) but it involves multiple steps:
1. loop over the Sine parts (steps 2-4)
2. set cycle position to 0
3. update sine initial state
4. disable Sine
5. after the loop, mirror the object
6. loop over the same parts and enable sine

This workaround requires the sprites to have the same angle as the instances, which is not necessarily the case in all situations.
There is a potential fix, which is to offset the angle of the instance, but the implementation I found doesn't work in all cases.

If C3 can have an option that can help with this process, that would be nice.

**Comment by AshleyScirra** [comment] 2024-09-24 12:16
Minimal repro: 
[issue8245.zip](https://github.com/user-attachments/files/17114356/issue8245.zip)

**Comment by Alaadel** [comment] 2024-10-16 08:28
Hello,
Any updates on this please?

**Comment by AshleyScirra** [comment] 2024-10-18 17:00
BTW, I'm not actually clear there's a bug here yet - the core problem is the Sine behavior reacts to unexpected changes in properties like the angle by resetting the initial value, which basically de-syncs the oscillation. So for this to work like you want it to, it is going to be necessary to involve setting the cycle position to 0 and then updating the initial state, regardless of whether there is a bug here. So it may be that your workaround is basically already the best way of handling this.

**Comment by AshleyScirra** [comment] 2024-10-24 15:25
This actually looks like the same issue as #7685, so marking as a duplicate of that.

**Closed** 2024-10-24 15:37 UTC
Labels: duplicate
