### ISSUE TITLE
Set timeline instance messes up the animation

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7291] opened 2023-08-10 16:25 UTC
## Problem description
I have a character, built from various parts. Parts belong to the same family. I need to create multiple instances of this character, and make them animate independently.
First, there is no tool that easily applies animations built for 1 hierarchy, to other similar hierarchies. So I used Set Time Line instance.
I gave each track a name, and each part a track name, then I loop over the parts and set it to the corresponding track, before playing the timeline.
The issue is that while playing the animation in the editor moves the hands, playing it at runtime moves the left leg!

I revised my code multiple times and tested many alterations, but the issue remains. The TimelineController plugin doesn't offer much debugging tools either .. I hope my code is correct.

Another issue is that after I copied the timeline from my original project to make the minimal one, the pasted timeline has changed the movement. Instead of a proper archer animation, I get what you see in the file!

## Attach a .c3p
[test timeline.zip](https://github.com/Scirra/Construct-bugs/files/12314816/test.timeline.zip)

## Steps to reproduce

1. Play the timeline in the editor.
2. Run the game.
3. Click the button

## Observed result
In the editor, the hands move.
In the preview, the left leg moves.

## Expected result
Same movement in the editor and preview.

## More details

**First affected release:** latest beta

**Comment by DiegoScirra** [comment] 2023-09-07 15:20
The pick **"pick own children"** is only picking the direct child of the root instance, so **Set Timeline Instance** ends up only being called for that one instance. If you change it to **"pick all children"** it works as expected.

As for the issue with copying and pasting a timeline... can you create a project that reproduces the problem? As in a project with the correct animation that when you copy from it and paste into a different project produces incorrect results.

**Comment by Alaadel** [comment] 2023-09-10 06:48
> The pick **"pick own children"** is only picking the direct child of the root instance, so **Set Timeline Instance** ends up only being called for that one instance. If you change it to **"pick all children"** it works as expected.
> 
> As for the issue with copying and pasting a timeline... can you create a project that reproduces the problem? As in a project with the correct animation that when you copy from it and paste into a different project produces incorrect results.

Thank you.
Using `pick all children` **doesn't** make it work as expected.

1. Please open the timeline and check the original motion.
2. Change `pick own` to `pick all` as suggested (line 4).
3. Run preview.
4. Click the button on the right. The original object moves like the original timeline.
5. Click the button on the left to create a new object.
6. Click the button on the right multiple times to check the movement of the new object.

Result:
The new object (that was created at runtime) doesn't move as the original.

**Comment by DiegoScirra** [comment] 2023-09-11 14:13
This will be fixed when the next release cycle starts.

I did notice that in the example project the **track id** values in the timeline tracks and the corresponding values in the instance variables where flipped. Make sure that those are matching the next time you try this out, as well as using **"pick all children"**.

**Closed by DiegoScirra** 2023-09-11 14:13 UTC

**Comment by Alaadel** [comment] 2023-09-14 07:19
Thank you.
I did that, but the issue still persists.
[test timeline.zip](https://github.com/Scirra/Construct-bugs/files/12605923/test.timeline.zip)

Using `pick all` makes the original object move incorrectly. Using `pick own` makes the original move correctly.
In both cases, the clones move incorrectly.

**Comment by DiegoScirra** [comment] 2023-09-14 07:52
The fix hasn't gone out yet. It will be available in the next beta.

I just mentioned the track ids being mixed up because I noticed it while fixing the problem.
