### ISSUE TITLE
Stuck at generating Spritesheet (or just taking forever)

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8129] opened 2024-07-23 15:31 UTC
## Problem description
A Project with many small assets, as is the case with pixel art, is stuck at generating spritesheets (or just taking forever).
Setting the max spritesheet size to 512 minimizes the problem where it only takes a bit of time. So I guess the issue is that there is an enormous amount of possibly configurations to try if the spritesheets have the size of 2048 or 4096.

## Attach a .c3p
https://github.com/ReflextionsDev/Zombiehood
While it's not a minimal project, this is the one where I notices the issue. As the events are irrelevant and I don't want to spend the time adding thousands of animation frames to a project, I think this works well as a repro.

## Steps to reproduce

1. change the max spritesheet size to 2048 or 4096
2. start preview or use the show spritesheet option

## Observed result
Project freezes while building spritesheets 
edit: after a long long wait it does finish

## Expected result
No freezing. Maybe some kind of strategy where it doesn't try all possible combinations once the permutations amount is over a certain threshold. Maybe a less optimized spritesheeting algorithm we can opt into.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2024-07-24 11:51
The project uses an extraordinary number of images - over 14,000 in the project. It also uses extraordinary number of images in individual objects, which is the cause of this problem - such as over 3000 in *npc_sprite* alone. It looks like this is one mega-sprite with images for what are meant to be several different object types, but all merged in to the same object. Construct isn't meant to be used like this - for example its memory management means it can either entirely load this object with all 3000 images, or not at all. A better approach is to use multiple object types and add them all to a family. Then things like memory management will work better and you'll avoid running in to weird limitations like the spritesheet building taking ages. The reason it takes so long is it tries to build a spritesheet with several thousand images which ends up getting pathologically slow, which isn't surprising as [bin packing](https://en.wikipedia.org/wiki/Bin_packing_problem) is [NP-hard](https://en.wikipedia.org/wiki/NP-hardness).

I've changed the next beta to put a hard limit on 1000 sprites per spritesheet, which seems to mitigate this - it still takes a while, but finishes relatively quickly for me even with a spritesheet size of 4096, rather than appearing to get stuck as it's so slow. So it should work better there, but in future I would advise against designing projects like this.

**Closed by AshleyScirra** 2024-07-24 11:51 UTC
Labels: performance
