### ISSUE TITLE
Playable Ads Webview resize event fail

### ISSUE THREAD

**Issue by PlayablesAdChampagne** [Scirra/Construct-bugs#7743] opened 2024-01-15 12:30 UTC
## Problem description

When publishing Playable Ads in unity dashboard there is a bug in iOS 17, there is an incorrect change of the application window after playing an advertising video before launching Playable Ads itself, on android and ios below 17 version no problems are observed.

Response from Unity Ads support:

We have checked your creative, and the CONSTRUCT 3 engine probably has an issue with iOS 17. Our Webview provides the correct "signal" (events) to the playable, but something in your playable itself is preventing canvas from being updated with the correct sizes on iOS 17, and it's been rendered in 1x1 pixels.
Please check the source code of your creative or contact CONSTRUCT's support team with this issue.

## Attach a .c3p

[source.zip](https://github.com/Scirra/Construct-bugs/files/13938758/source.zip)

## Steps to reproduce

1. Download Unity's Playable Ads verification app from [here](https://apps.apple.com/us/app/ad-testing/id1463016906)
2. Go to "Creative Pack Tester" and scan the QR code, or post a Playable Ad (index_un.html) to the Unity Dashboard site from [here](https://cloud.unity.com/home/organizations/) (When uploading through the site, be sure to select the publishing mode "Video & Playable end card", otherwise no errors are observed)
![image](https://github.com/Scirra/Construct-bugs/assets/144243915/3c393d68-1f96-4624-9003-b453d860744c)
![image](https://github.com/Scirra/Construct-bugs/assets/144243915/32725dc4-97c3-4104-9596-320d7237d8ec)

3. Initialize and play the Creative Pack to observe the problem

## Observed result

After the video, Unity sends a Webview event and the Playable Ad is scaled to 1x1 size regardless of mraid.addEventListener('sizeChange',resizeWindow);

![image](https://github.com/Scirra/Construct-bugs/assets/144243915/a6d3e4de-766b-48cd-aa8f-566b94ca6aba)

## Expected result

Playable Ad successfully plays, rendered at the correct scale

![image](https://github.com/Scirra/Construct-bugs/assets/144243915/d96c51e8-b397-4a91-8979-64525d3a4ca6)

## More details

**Affected browsers/platforms:** 

IOS 17, IPhone 13

**First affected release:** 

The bug is observed in all releases of Construct 3

## System details

<details>
<summary>
Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 120.0.6099.72
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 110 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 (0x00002206) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</summary>
</details>

**Comment by AshleyScirra** [comment] 2024-01-15 16:11
Construct sizes the display to whatever the browser or webview tells it. If this worked prior to iOS 17 and is only broken on iOS 17, I would say this is likely a bug in iOS, not Construct. This is unsurprising as iOS has a history of viewport/window size bugs and we already have a bunch of workarounds for iOS.

The only case Construct will size itself to 1x1 is if the browser/webview tells Construct that the window size is 0x0. In that case a zero size could cause a crash, so Construct clamps the minimum size to 1x1. So I suspect this is an iOS 17 bug that causes the window size to incorrectly be reported as 0x0, and Construct uses a minimum size of 1x1 to avoid crashing. It may not be possible to work around this, as Construct cannot know what the true window size is if it is being reported as 0x0.

It is best to report such things directly to Apple so they can fix the root cause instead of relying on engine workarounds. I will take a look at this and see if we can work around it anyway, but as I mentioned this may not be feasible and you may need to file a bug with Apple anyway, so I would advise you do that first as well.

**Comment by AshleyScirra** [comment] 2024-01-15 16:16
BTW are you using the 'Playable ad' export option, or the 'Web (HTML5)' export option? Your steps don't seem to mention which.

**Comment by PlayablesAdChampagne** [comment] 2024-01-15 16:37
> BTW are you using the 'Playable ad' export option, or the 'Web (HTML5)' export option? Your steps don't seem to mention which.

Hello! Thanks for your reply, sad that it's more complicated than I thought, I'll try knocking on Apple's door.

I'm using the 'Playable Ad' export option.

**Comment by AshleyScirra** [comment] 2024-01-15 17:21
We already have code to try to work around broken resize events on iOS, and that code should already be running in Playable Ads (assuming the user agent is not overridden so it doesn't look like iOS). So I'd guess it's now so broken even our workaround code isn't working. Again I'll test this when I get time to double check, but I think this will fall in to the category of system bugs it's infeasible for us to fix, so I'd definitely report it to Apple as a regression in iOS 17.

**Comment by AshleyScirra** [comment] 2024-02-06 15:29
I can't figure out how to test this. If I export a Playable Ad from Construct, and go to create a new creative pack on the Unity Dashboard, it asks for an app store URL which I don't have so I just put in the Ad Tester app URL. Then if I upload index.html for the "Playable end card" it just shows some validation errors and it won't let me create it (see screenshot below).

I'd say this is very likely an iOS bug anyway - I doubt there is much we can do about it even if I can successfully test it. But am I missing something here?

![image](https://github.com/Scirra/Construct-bugs/assets/768723/0344a8ee-ee29-4541-96b9-53fbe7f3896b)

**Comment by PlayablesAdChampagne** [comment] 2024-02-08 09:59
@AshleyScirra 
Hi, you have to call the mraid.open(url) function when you click on the CTA button, in my example it looks like the screenshot below.
Make sure that the url on the site and in the creative are the same
Thank you!
![image](https://github.com/Scirra/Construct-bugs/assets/144243915/2fd09a48-aee5-4771-ad3b-2491d0ed22f3)
![image](https://github.com/Scirra/Construct-bugs/assets/144243915/cbae2576-c49c-4d5e-a3e5-06a0f6a9e83a)

**Comment by AshleyScirra** [comment] 2024-02-08 11:46
I'm using the project you provided in the original issue. If that project does not pass validation, please provide one that does, so I can be sure I'm testing correctly.

**Comment by PlayablesAdChampagne** [comment] 2024-02-08 12:20
Yeah, sorry, I forgot to mention that I add additional scripts for advertising networks after exporting, try this source instead of the previous one.
[source.zip](https://github.com/Scirra/Construct-bugs/files/14209103/source.zip)

**Comment by AshleyScirra** [comment] 2024-02-13 16:26
It still fails validation for me. Please make sure you provide everything necessary to successfully test this otherwise I won't be able to help.

![image](https://github.com/Scirra/Construct-bugs/assets/768723/5bd67c6b-6065-4e52-8414-a3e7b82fc819)

**Comment by AshleyScirra** [comment] 2024-03-05 17:27
Given the difficulty reproducing this, and the likelihood it is a bug in iOS, closing this issue. I would advise following up with Apple if you still have trouble. If it worked on iOS 16 and broke with iOS 17+ that is usually a strong signal the problem is with iOS itself.

**Closed by AshleyScirra** 2024-03-05 17:27 UTC
Labels: external, iOS
