### ISSUE TITLE
Platformer landing issue after r344

### ISSUE THREAD

**Issue by KylesoulErmite** [Scirra/Construct-bugs#7086] opened 2023-06-01 12:35 UTC
## Problem description

Hi,

I'm running an issue after the last update. When my player is landing on a vertical moving platform moving down, the player is still falling. It doesn't do it when the player is already on the platform. I tested this on the last stable version (r336) and there is no issue.

## Attach a .c3p

https://drive.google.com/file/d/1iSLWI1gfjWeqW6Uno1vz8-KzyfolGhaP/view?usp=sharing

## Steps to reproduce
This bug needs the last stable version. (r344) You can run it on r336 to compare.
1. You can control the player by using direction arrow keys ("up" to jump)
2. You can see already a character landing on a moving platform moving down doing this bug at the start of the layout.
3. Jump on a moving platform when it moving down.

## Observed result

The character with platformer behavior is still making the falling and landing animation.

## Expected result

The player should land properly and stay idle on the ground (moving platform)

## More details
Tested on all browsers

**Comment by KylesoulErmite** [comment] 2023-06-01 17:32
Oh sorry, my bad...
Here the public link : https://drive.google.com/file/d/1B1HIOipuK3VnIuw-hhQ53yh2ac9Coh1S/view?usp=sharing

**Comment by yojona** [comment] 2023-06-01 22:29
same here, thought it was just me

**Comment by AshleyScirra** [comment] 2023-06-02 10:04
Please provide a minimal project, using the fewest events and objects possible, as per the bug report guidelines. I'm afraid projects as complex as the one you provided are virtually impossible to debug.

**Comment by KylesoulErmite** [comment] 2023-06-02 13:19
Here : https://drive.google.com/file/d/1iSLWI1gfjWeqW6Uno1vz8-KzyfolGhaP/view?usp=sharing

I've made this simpliest as possible. I hope that's better. :)

**Comment by TomoloGames** [comment] 2023-06-03 12:40
I see that this is labeled "Need info" so here is a file with only an object with platform behavior and an object with sine behavior so that you can easily see what the problem is. 

https://1drv.ms/u/s!AhjxouGcV5_T133Tm-y8FWf2jMGL?e=CAhwxj

**Comment by KylesoulErmite** [comment] 2023-06-03 12:58
@TomoloGames Thanks. Now there are all the info needed in the simpliest project.

**Comment by TomoloGames** [comment] 2023-06-09 20:01
@AshleyScirra - My game is unplayable with these bugs, any idea when this will be fixed? Or is there a way to open the project in an earlier version (r336) somehow?

**Comment by GameSoul7Eugene** [comment] 2023-06-10 04:02
@TomoloGames,

You can launch (almost) any C3 release from the following link:
_**editor.construct.net/r[RELEASE_NUMBER]**_

Here is the link to the previous stable release (before Platform behavior was fixed):
[editor.construct.net/r336](https://editor.construct.net/r336)

**Comment by TomoloGames** [comment] 2023-06-10 09:20
@GameSoul7Eugene - Yes I know that but that doesn't help since I saved my project in r344 so if I launch a previous release it won't let me open my project.

**Comment by GameSoul7Eugene** [comment] 2023-06-10 14:24
@TomoloGames, If your project doesn't use any of the new features in R344, you can easily downgrade it to R336. To do this:

1. Make a backup of your project! In case something goes wrong.
2. If your project is in C3P format, unzip it first and open the "project.c3proj" file located at the root of your project's file structure using Notepad.
3. Change the value of the JSON key "savedWithRelease" to 33600 (which means R336).
4. Save the changes and try to open your project in the older release (as a project folder).

I hope this helps you!

**Comment by TomoloGames** [comment] 2023-06-10 15:01
@GameSoul7Eugene - It worked, you're a lifesaver! A thousand thanks for helping me out :)

**Closed** 2023-06-15 14:10 UTC

**Comment by AshleyScirra** [comment] 2023-09-05 10:22
Based on my last comment I verified this was working. If you still have trouble with the latest release please file a new issue.

**Comment by TomoloGames** [comment] 2023-09-05 12:17
> Based on my last comment I verified this was working. If you still have trouble with the latest release please file a new issue.

Based on my last comment I verified it's not working. It works great in R336 but though. I don't use simulate control jump, I use negative vector y because I use triple jumps. I won't file yet another bug report but if you are interested then you can check out this quick project I made for you. Try to jump while the sine-object is going up. 

https://drive.google.com/file/d/1FsCoKlLX23wQviu2OVcCx6P3gk6fv4G4/view?usp=sharing
