### ISSUE TITLE
fog exponential banding on android with webGL

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7899] opened 2024-03-14 09:53 UTC
## Problem description
the fog exponential effect looks incorrect on mobile android with webGL

## Attach a .c3p
[fogDebug.zip](https://github.com/Scirra/Construct-bugs/files/14600334/fogDebug.zip)

## Steps to reproduce

1. preview on android with webGL

## Observed result
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/bd553d4b-8f12-44ed-ae17-64530102e6e5)
fog is not a smooth gradient but shows hard bands (precision?)

## Expected result
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/375f4c4c-58a8-4827-9dcb-90c9f644e5b4)
smooth gradient

## More details
Does work correctly with webGPU

**Affected browsers/platforms:** 

**First affected release:** 

## System details
Chrome 122.0.6261.105
Android 14, Pixel 8

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment] 2024-03-14 10:10
Perhaps it has something to do with this: https://github.com/Scirra/Construct-bugs/issues/5510

**Comment by F3der1co** [comment] 2024-03-14 10:19
yes, seems to be the same issue! But my phone is very up to date, so that is weird.

for more information I saved Chrome://gpu from my phone:
[about-gpu-2024-03-14T10-08-32-756Z.txt](https://github.com/Scirra/Construct-bugs/files/14600690/about-gpu-2024-03-14T10-08-32-756Z.txt)

One thing I noticed from it is:
```
*   clampFragDepth (OpenGL workarounds): Disabled
    condition: isNvidia
    gl_FragDepth is not clamped correctly when rendering to a floating point
    depth buffer
```

**Comment by AshleyScirra** [comment] 2024-03-15 14:30
This is a duplicate of #5510. I'm afraid I've no idea why it happens and I can't find any solution. It does reproduce on my Android phone which allowed me to experiment a bit, but nothing seems to help. Construct requests a 24-bit depth buffer with 8-bit stencil buffer: `DEPTH24_STENCIL8` in WebGL, and `"depth24plus-stencil8"` in WebGPU. This seems to work fine in virtually all cases, except some specific Android devices. I tried increasing the depth buffer precision in WebGL to `DEPTH32F_STENCIL8` (32-bit float depth buffer), which didn't help; tried removing writing to `gl_FragDepth`, which didn't help; tried increasing the precision to `highp`, which didn't help. So I guess it's either a graphics driver bug (a likely culprit in many cases of graphics issues), or there is some loophole in the OpenGL spec that allows certain calculations to be done at a lower precision which some Android devices are taking advantage of (whereas WebGPU is more robustly specified and so tends to perform things at float32 precision by default unless explicitly written to use something like float16). Either way, I don't think there's anything we can do. At least it works in WebGPU, which should ultimately replace WebGL.

The only thing that makes a difference is adjusting the near and far distances: make the near distance as far away as possible, and the far distance as near as possible, to make the depth range between them as small as possible, and it renders a bit better.

**Closed by AshleyScirra** 2024-03-15 14:30 UTC
Labels: duplicate

**Comment by F3der1co** [comment] 2024-03-15 14:37
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/f908ae5b-cb9e-4a34-83c1-683022b7143a)

**Comment by F3der1co** [comment] 2024-03-15 14:37
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/570894ce-4080-4636-81ea-a53cbd1a7a6c)

**Comment by AshleyScirra** [comment] 2024-03-15 14:48
Just one of many difficult complications that come up if you try to make a 3D engine 🫠
