### ISSUE TITLE
Project not resuming and remaining frozen after changing tab/app

### ISSUE THREAD

**Issue by duoplay88** [Scirra/Construct-bugs#7481] opened 2023-10-22 09:46 UTC
## Problem description
Try to open browser after switch to other app. Then html5 game freeze.

## Attach a .c3p
Please test with this game. 
https://editor.construct.net/#open=tweening

## Steps to reproduce

1.open the game using Chrome version 118 (latest) on Android 
2.switch to other app
3.back to chrome 
4.try to touch any position on screen to move the character. 

## Observed result
The game is not responding anymore. 

## Expected result
Expect to see "[Construct] resuming" in inspect log. And the game is responding. 

## More details
Happen on Chrome and Firefox latest version only on Android. I test many Android device and result is the same. 

**Affected browsers/platforms:** 

**First affected release:** not sure. Sorry. I Test on r358

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment] 2023-10-23 13:38
This appears to be a recently introduced bug in Chrome for Android: when I change tab and back it fires four page visibility events, the first three saying hidden (two apparently being redundant events), and the last saying visible. Construct has historically expected as many hidden events as visible events (mainly because there are other causes of suspending the page so it keeps a count), and this change to Chrome for Android broke that assumption and so left the page suspended. I say this is probably recent as this is how Construct has worked for years and I don't recall this ever being a problem in the past.

I've worked around this for the next beta so it should correctly handle inconsistent page visibility events and always resume when the page is made visible.

**Comment by letnrodrigues** [comment] 2023-10-23 15:03
Just for the record, this issue is also happening on Chrome for desktop. Since last week (also when Chrome updated) we're experiencing this bug multiple times across all platforms. It seems to be kind of random in that sometimes we change tabs and go back and it freezes and sometimes it doesn't. A lot of our customers are also experiencing this with builds that were working before and it seems to be clearly related to the issue linked above. Other browsers are working fine.

**Comment by AshleyScirra** [comment] 2023-10-23 15:07
I couldn't reproduce this on desktop, but the issue I linked to appears to mention it happening on desktop. I tried following the steps in that issue on desktop and couldn't reproduce it there either. Perhaps there is some specific thing you need to do on desktop to reproduce it?

**Comment by AshleyScirra** [comment] 2023-10-23 15:10
I'm going to leave this issue opened and pinned as I would guess a lot of people are about to run in to this. It's probably a regression in Chrome 118 which has just started rolling out in the past week.

**Comment by letnrodrigues** [comment] 2023-10-23 15:17
It's hard to be specific because for us it seems to be happening very randomly, as in sometimes it happens as soon as we open one of our builds and change tabs and sometimes it doesn't happen for hours and then we alternate tabs and it never resumes. It doesn't seem that anything within our pages is remotely causing it, it seems to be some weird browser stuff going on, and I'm still not able to guess what could cause it. Maybe the way we interact with other tabs and then go back?

Only thing we know for sure is that Construct never emits the "resumed" event in console, we only get the "suspended" event, indicating that it's precisely the issue we're reporting here.

**Comment by AshleyScirra** [comment] 2023-10-23 15:39
@WilsonPercival - thanks, I can reproduce on desktop too now - it looks like the thumbnail hover is what triggers the issue there. I'll comment on the Chrome issue with that info.

**Comment by AshleyScirra** [comment] 2023-11-07 13:43
Chrome 119 is now rolling out to stable so closing issue - it should be fixed there.

**Closed by AshleyScirra** 2023-11-07 13:43 UTC
Labels: external, Android
