### ISSUE TITLE
Camera effects flash in IOS

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7958] opened 2024-04-22 06:21 UTC
## Problem description

After add the effect to the UserMedia, preview on iOS, whether using safari or Chrome, will appear constantly flashing. It's probably a platform problem because I've tried other effects and still happened.

## Attach a .c3p

https://editor.construct.net/#open=camera-effects

## Steps to reproduce
1. Remote preview
2.
3.

## Observed result

constantly flashing

## Expected result

normal work

## More details

**Affected browsers/platforms:** iOS 17.4.1

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2024-04-22 15:47
The provided link opens the latest stable release, which does reproduce the issue. However our bug report guidelines advise to test the latest beta release to avoid reporting issues that have already been dealt with, and I cannot reproduce this in the latest beta, so closing. I think this is a bug in Safari that we worked around already.

**Closed by AshleyScirra** 2024-04-22 15:47 UTC
Labels: can't reproduce, iOS
