### ISSUE TITLE
Crash pasting timeline with inconsistent plugin references

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7233] opened 2023-07-18 17:43 UTC
## Problem description

Construct crashes.

## Attach a .c3p

[crash_timeline_invalid_property_id_r351b.zip](https://github.com/WilsonPercival/WilsonPercival/files/12084179/crash_timeline_invalid_property_id_r351b.zip)

## Steps to reproduce

1. Open a project.
2. Cut out `Timeline 1`.
3. Remove the `Text` object from the project.
4. Create a sprite and name it `Text`.
5. Insert `Timeline 1`.
6. Duplicate `Timeline 1`.

## Observed result

[observed.webm](https://github.com/WilsonPercival/WilsonPercival/assets/91274932/ecf525a0-7701-4a77-a235-f127f2e06768)

## Expected result

Construct does not crash.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r351b

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: invalid property id 'text' @ Error: invalid property id 'text' at d.Sp (https://editor.construct.net/r351/projectResources.js:811:362) at d.Lib (https://editor.construct.net/r351/projectResources.js:812:376) at https://editor.construct.net/r351/projectResources.js:1254:38 at pw (https://editor.construct.net/r351/projectResources.js:93:139) at mTa.Aea (https://editor.construct.net/r351/projectResources.js:1254:16) at d.Om (https://editor.construct.net/r351/projectResources.js:1121:182) at d.RE (https://editor.construct.net/r351/projectResources.js:1039:190) at d.RE (https://editor.construct.net/r351/projectResources.js:1039:277) at d.lw (https://editor.construct.net/r351/projectResources.js:1014:247) at d.Hh (https://editor.construct.net/r351/projectResources.js:995:312)
Stack: Error: invalid property id 'text' at d.Sp (https://editor.construct.net/r351/projectResources.js:811:362) at d.Lib (https://editor.construct.net/r351/projectResources.js:812:376) at https://editor.construct.net/r351/projectResources.js:1254:38 at pw (https://editor.construct.net/r351/projectResources.js:93:139) at mTa.Aea (https://editor.construct.net/r351/projectResources.js:1254:16) at d.Om (https://editor.construct.net/r351/projectResources.js:1121:182) at d.RE (https://editor.construct.net/r351/projectResources.js:1039:190) at d.RE (https://editor.construct.net/r351/projectResources.js:1039:277) at d.lw (https://editor.construct.net/r351/projectResources.js:1014:247) at d.Hh (https://editor.construct.net/r351/projectResources.js:995:312)
Construct version: r351
URL: https://editor.construct.net/r351/
Date: Tue Jul 18 2023 20:18:37 GMT+0300 (Восточная Европа, летнее время)
Uptime: 181.1 s

Platform information
Product: Construct 3 r351 (beta)
Browser: Chrome 114.0.5735.199
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by AshleyScirra** [comment] 2023-08-14 17:23
@DiegoScirra - steps try to paste a timeline referring to the wrong plugin ID. Copying a timeline should also copy the plugin ID of referenced objects, and pasting should validate that the matched objects have the expected plugin ID.

**Comment by DiegoScirra** [comment] 2023-08-31 17:01
Can't reproduce this anymore. When you try to paste the timeline, C3 doesn't allow you to do it because it references things that don't exist in the project anymore.

In this case pasting the timeline should create all the missing  objects in the project, as it does when pasting on a different project. Doing that could introduce new problems and it is not an urgent requirement, so I will not attempt to do it now. Closing.

**Closed by DiegoScirra** 2023-08-31 17:01 UTC
Labels: can't reproduce
