### ISSUE TITLE
Crash find all references in view used addons

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-bugs#7859] opened 2024-02-22 12:31 UTC
## Problem description

Construct crashes.

## Steps to reproduce

1. Create a new project
2. Insert any object on the layout
3. Right-click **project folder** → _Tools_ → _View used addons_
4. Right-click **added plugin** → _Find all references..._

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Broke in `r100b` as it is the oldest version I can test. Still doesn't work in `r380b`.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: d.tu.H is not a function @ TypeError: d.tu.H is not a function at Fwb (https://editor.construct.net/r380/components/bars/findReferencesBar/findReferencesBar.js:6:258)
Stack: TypeError: d.tu.H is not a function at Fwb (https://editor.construct.net/r380/components/bars/findReferencesBar/findReferencesBar.js:6:258)
Construct version: r380
URL: https://editor.construct.net/r380/
Date: Thu Feb 22 2024 13:14:07 GMT+0100 (Central European Standard Time)
Uptime: 469.7 s

Platform information
Product: Construct 3 r380 (beta)
Browser: Edge 120.0.2210.133
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 4000 (0x00000166) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by WilsonPercival** [comment] 2024-02-22 12:45
I can't reproduce it on a new computer.

Duplicate of https://github.com/Scirra/Construct-bugs/issues/6701

**Comment by DiegoScirra** [comment] 2024-02-23 18:23
The hiding animation of the used addons dialog gives some time for a couple of things to be able to take place in the wrong order.

**Closed** 2024-02-23 18:33 UTC
