### ISSUE TITLE
https://editor.construct.net/ will randomly error and not be able to be used at all

### ISSUE THREAD

**Issue by npmccauslin** [Scirra/Construct-bugs#8253] opened 2024-09-26 23:41 UTC
## Problem description

Navigating to https://editor.construct.net/ will sometimes have a full page error and prevent any work, the specific error is:
![Screenshot 2024-09-26 at 4 28 17 PM](https://github.com/user-attachments/assets/86d04e0b-75c3-458b-95ef-33eec5a508a3)

Console errors:
* `Failed to load resource: the server responded with a status of 400 ()`
* `Understand this error m=credential_button_library:71 [GSI_LOGGER]: The given origin is not allowed for the given client ID.`

## Attach a .c3p
None, it's just trying to access the editor in general.

## Steps to reproduce

1. Might be tough to reproduce because it doesn't even happen to me that often but it's annoying when it does.

## Observed result

![Screenshot 2024-09-26 at 4 34 40 PM](https://github.com/user-attachments/assets/df0bcc78-ad00-4128-8916-aad9dbc2cb74)

## Expected result

Not blow up

## More details

I tried clearing my cache and plugins but that doesn't help, though moving to another browser or incognito does, it's really annoying to have to do this every time.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2024-09-27 10:21
I've never seen this happen or heard of anyone else with this problem, so it seems like an issue specific to your system.

When the error happens, can you try pressing F12 and check for any error messages in the console? That might help indicate what is happening. I would guess a browser extension is interfering, so try removing them all and see if that helps. I'm afraid these issues can be extremely difficult to resolve unless we can reproduce them ourselves.

**Comment by XHXIAIEIN** [comment] 2024-09-29 05:38
> I've never seen this happen or heard of anyone else with this problem, so it seems like an issue specific to your system.
> 
> When the error happens, can you try pressing F12 and check for any error messages in the console? That might help indicate what is happening. I would guess a browser extension is interfering, so try removing them all and see if that helps. I'm afraid these issues can be extremely difficult to resolve unless we can reproduce them ourselves.

I know that China users often have this problem. Most likely it is due to network connection problems.  Some regions may not be able to access certain Construct servers during certain times, and this happens quite randomly.

**Comment by npmccauslin** [comment] 2024-09-29 16:50
@AshleyScirra yeah it's a tough one and like I said there is a work around and for example of inconsistency --> 
To @XHXIAIEIN point:
Construct now works fine, same browser instance, same tab, all I did was hit refresh again, it just took a few days.

**Comment by AshleyScirra** [comment] 2024-09-30 10:09
Closing as this appears to be a networking issue rather than a problem with Construct itself.

**Closed by AshleyScirra** 2024-09-30 10:09 UTC
Labels: can't reproduce
