### ISSUE TITLE
Video stop looping

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-bugs#8154] opened 2024-08-06 08:24 UTC
## Problem description

Video stop looping after minimize window.

## Attach a .c3p

[videoloop.zip](https://github.com/user-attachments/files/16507243/videoloop.zip)

## Steps to reproduce

1. Preview project and wait 5 seconds
2. Minimize preview window and wait 20 - 30 seconds
3. Try this steps 3 times if video not stopped.

## Observed result

Video stopped

## Expected result

Video looping

## More details

<details><summary>Video Details</summary>

```
GENERAL
Complete name                            : s.webm
Format                                   : WebM
Format version                           : Version 2
File size                                : 347 KiB
Duration                                 : 1 s 200 ms
Overall bit rate                         : 2 370 kb/s
Frame rate                               : 30.097 FPS
Writing application                      : vp8 v1.3.0
Writing library                          : Unity VP8VideoMedia 2022.3.35f1 (011206c7a712)

VIDEO
ID                                       : 1
Format                                   : VP8
Codec ID                                 : V_VP8
Duration                                 : 1 s 196 ms
Bit rate                                 : 2 269 kb/s
Width                                    : 720 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 1.000
Frame rate mode                          : Constant
Frame rate                               : 30.097 FPS
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.145
Stream size                              : 331 KiB (95%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
```

</details>

**Affected browsers/platforms:** Chrome (Firefox works perfect no issue)

**First affected release:** Tried in r300 and still same issue, idk lower versions.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r400 (beta)
Browser: Chrome 127.0.6533.89
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 135 gb
Storage usage (approx): 152 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 3GB (0x00001C02) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment] 2024-08-06 15:54
This looks like some kind of bug in Chrome that will be hard work to track down. It would be a big help if you could find a way to reproduce this quickly and reliably, as having steps that involve waiting and aren't reliable is a major hurdle.

**Comment by CrackHub** [comment] 2024-08-06 17:40
I can only find the problem with this method. (Only 1. and 2. steps) If I found another way I can send it.

**Comment by AshleyScirra** [comment] 2024-10-28 16:05
Since this can be reproduced with video playback in a tab without the use of Construct at all, this looks like a Chrome bug. I've filed it here: https://issues.chromium.org/issues/375973479
Closing this issue as it will be followed up there.

**Closed by AshleyScirra** 2024-10-28 16:05 UTC
Labels: external, chrome

**Comment by AshleyScirra** [comment] 2024-10-30 11:01
Google responded to the issue and apparently the problem is the video file is incorrectly encoded. I can't reproduce the problem with a different video file, so this does seem to be the case. So I think ultimately the problem is with the video file itself, not Chrome or Construct.

**Comment by CrackHub** [comment] 2024-10-31 12:48
Okey thank you, I think it is Unity problem then.  I'll try to report them.
