### ISSUE TITLE
Unhandled rejection cannot undo inside another undo redo call crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#6597] opened 2023-02-22 02:20 UTC
## Problem description

Construct crashes.

I started checking this bug after the fix: https://github.com/Scirra/Construct-3-bugs/issues/6494

It seemed to me that you created a barrier in the form of a pop-up window `Working...`. But during this window, I can still press `Ctrl + Z` to roll back a step.

I also wrote a small `keylogger` to make it easier for you to understand what time to press the keys. It does not work perfectly, sometimes the keys stick, but this is not critical here.

## Attach a .c3p

save open project: [save_open_project.zip](https://github.com/WilsonPercival/WilsonPercival/files/10799405/save_open_project.zip)

## Steps to reproduce

1. Open the `cannot_read_properties_of_null_music_crash_r329b.zip` project.
2. Highlight the `Music` folder.
3. Press `Ctrl + C`.
4. Press `Ctrl + V`.
5. Wait for the `Working...` window to appear and press the `Ctrl + Z` button.
6. When you see a subfolder with a file on the project panel, quickly press `Ctrl + X` twice and start quickly pressing `Ctrl + Z`.

## Observed result

https://user-images.githubusercontent.com/91274932/220503540-70a593c4-5676-4043-8630-3da26ce0a1dc.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled rejection
Reason: Error: cannot undo inside another undo/redo call @ Error: cannot undo inside another undo/redo call at window.sc.Dh (https://editor.construct.net/r331/projectResources.js:1865:138) at d.Dh (https://editor.construct.net/r331/projectResources.js:1740:9) at https://editor.construct.net/r331/main.js:2511:354 at window.Geb.Dh (https://editor.construct.net/r331/main.js:2511:397)
Stack: Error: cannot undo inside another undo/redo call at window.sc.Dh (https://editor.construct.net/r331/projectResources.js:1865:138) at d.Dh (https://editor.construct.net/r331/projectResources.js:1740:9) at https://editor.construct.net/r331/main.js:2511:354 at window.Geb.Dh (https://editor.construct.net/r331/main.js:2511:397)
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Wed Feb 22 2023 03:52:07 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 42.1 s

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r331b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 198 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-03-10 14:53
Merged in to #6531

**Closed by AshleyScirra** 2023-03-10 14:53 UTC

**Comment by DiegoScirra** [comment] 2023-03-20 15:39
Can't reproduce, but should be fixed when the next release cycle starts. Marking as complete in #6531
