### ISSUE TITLE
Issue with iOS Export

### ISSUE THREAD

**Issue by ChrisByAppli** [Scirra/Construct-bugs#7456] opened 2023-10-10 13:04 UTC
## Problem description

I have a construct 3 application crash when i'm trying to export a game on iOS platform.

## Attach a .c3p

With any C3p files.

## Steps to reproduce

1. Export iOS 
2. xCODE +14 ios
3. BUG

## Observed result

A red screen with a report 
Error report information
Type: unhandled exception
File: https://editor.construct.net/r358/main.js, line 1917, col 242
Message: Uncaught TypeError: d.getModifierState is not a function
Stack: TypeError: d.getModifierState is not a function at rr.g.ki.NLa (https://editor.construct.net/r358/main.js:1917:242) at aj.g.avc.zd (https://editor.construct.net/r358/main.js:1919:416) at https://editor.construct.net/r358/main.js:1919:139
Construct version: r358
URL: https://editor.construct.net/
Date: Tue Oct 10 2023 14:57:43 GMT+0200 (UTC+02:00)
Uptime: 47 s

Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 117.0.5938.149
Browser engine: Chromium
Context: webapp
Operating system: macOS 14.0.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: fr-FR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

## Expected result

Obtain an export of my game in xCode format.

## More details

**Affected browsers/platforms:** 
Chrome / macOS m2

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment] 2023-10-10 13:15
@ChrisByAppli Can not reproduce. Everything works well for me.

https://github.com/Scirra/Construct-bugs/assets/91274932/a5b2b9d4-94c4-47c0-9b2b-bd529ae63518

**Comment by DiegoScirra** [comment] 2023-10-10 13:29
Can't reproduce.

What are the exact reproduction steps? The crash report suggests something to do with keyboard input. I have tried going through the options by pressing ENTER instead of clicking, but I still could not reproduce the problem.

**Comment by ChrisByAppli** [comment] 2023-10-10 14:22
i have to delete the #include phrase to run my project.

**Comment by AshleyScirra** [comment] 2023-10-11 11:22
It works fine for me too. I'm afraid there's not much we can do if we can't reproduce the issue, so closing. Perhaps you have some browser extension installed which is interfering with Construct - try disabling any browser extensions and see if that helps, or try a different browser.

**Closed by AshleyScirra** 2023-10-11 11:22 UTC
Labels: can't reproduce, iOS
