### ISSUE TITLE
Project Bar performance bottlenecks in large projects

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-bugs#7611] opened 2023-12-04 12:33 UTC
## Problem description

Large Project Series: A project with 18k objects (stress test)

Slow to Open and Close Dropdown Arrows In Project View (Even those with 1 item)

## Attach a .c3p

[Large_Project_Debug_0.zip](https://github.com/Scirra/Construct-bugs/files/13545911/Large_Project_Debug_0.zip)

## Steps to reproduce

1. Click on the dropdown arrow pertaining to Layouts in the Project View.
2. Click it again
3. Note the time it takes in each case

**Comment by AshleyScirra** [comment] 2023-12-11 13:48
I suspect all of #7610, #7612, #7613, #7614 and #7615 all have the same cause: the Project Bar sometimes does redundant updates of all of its items, and in a large project that covers thousands (or tens of thousands?) of items, which means it's regularly slow. I'm marking those all duplicates of this issue as I have a single fix in for the next beta which I think should substantially improve all these cases. However in some cases the test project's long family member lists still causes an issue, but I think real-world projects should not use so many family members as that, so it might be OK, but marking as 'check next release' so we can review how it works for your real-world project.

**Comment by DinoSystem** [comment] 2023-12-11 15:50
Wow this fixed would really make my life easier, considering my project's size!

**Comment by OneRepCloser** [comment] 2023-12-11 16:02
> Wow this fixed would really make my life easier, considering my project's size!

@DinoSystem 

Roughly how large is your project, if I may ask (Project statistics)?

**Comment by DinoSystem** [comment] 2023-12-11 16:26
Name: DinoSystem
Layouts: 2
Event sheets: 12
Total number of events: 16064
Total number of conditions: 21957
Total number of actions: 24022
Total lines of JavaScript code: 0
Object types: 459
Families: 61

**Comment by AshleyScirra** [comment] 2023-12-12 13:59
r371 is now out - @OneRepCloser, is it better with your real project?

**Comment by OneRepCloser** [comment] 2023-12-13 06:30
Hello Ashley, thank you for the revisions.

## Initial Testing

Project search functionality has improved.

Opening and closing event sheets seems faster.

Clicking on event sheet tabs seems faster.

However, the time it takes to clone and rename objects still persists (and this was the catalyst for me posting these issues initially, as I was waiting ~15 seconds for a single object to clone and I needed to clone quite a few of them).

However, you've mentioned this might still be an issue if a project has a high family count (which mine does).

## Family Count

I have 149 families in my project, which I use both for organization and performance; otherwise, I'd have families with hundreds of instance variables.

## Family Count Use Case

Let's say we have a family called Characters with 500 objects.

Of those 500, 5 of them have sounds directly associated with their animation frames.

Let's make a family for these 5, called Characters_With_Frame_Sounds.

### Performance Rationale

In terms of performance, my rationale was that picking objects would be more efficient if you start with the family for which this picking is only possible. Let's say 100 out of those 500 characters are instantiated, and of those, only 1 has sounds associated with their animation frames.

If I create a family pertaining only to those objects which have sounds associated with their frames, and I check On_Frame_Changed for that 1 character instead of 100 characters, I'd expect this to be more efficient.

This performance optimization is more for future planning, though, and just serves as an example of a use case.

Another use case: Characters_With_Solids. I recall at one point there were performance impacts if objects had behaviors attached to them even if they weren't being utilized. This was a significant catalyst in my decision to use more specialized families instead of attaching behaviors to hundreds of objects in a single family.

### Organization Rationale

It's much easier for me to keep track of which objects have sounds associated with their frames if they are inherently in that specific family, as opposed to maintaining this distinction with instance variables.

This also prevents instance variable bloat in families.

What I could do as an alternative, for the organizational aspect, is to set aside specific layouts for these characters so I don't get them mixed up and just accept the instance variable bloat issue.

Nonetheless, as a project gets larger, organization tends to become even more important, so having to limit my family count is unfortunate, but if this issue is unavoidable, I may have to find an alternative.

## Consideration

So the question becomes, is it worth it to give up the benefits having specialized families (sub-families?) so that object cloning and object renaming becomes faster? (more of a rhetorical question, user-preference)

Regardless of all the above, if I had the foresight of how family count can drastically (at least in my case) slow down object cloning and object renaming, I would have probably prioritized having fewer families at the cost of these potential performance and organizational benefits.

## Alternative - Dictionaries vs. Instance Variables

My project has around 800 characters, and the instance variable count was getting out of control for these characters, and I think it was contributing to slow object cloning. Thus, I decided to use a dictionary associated with these characters so that instance variables are assessed in real-time rather than in the editor.

Considering how far I'm into this project, it might take months for me to fully set this up for all objects, but would you recommend this transition to dictionaries to contain the instance variables?

**Comment by AshleyScirra** [comment] 2023-12-13 14:55
The problem is that if you add, remove or rename an object in a family, it currently updates all the items under the families it is in in the Project Bar. So for example if you have 10 families each with 100 items under it, and each family has "SpriteA", and you rename "SpriteA" to "SpriteB", currently it will have to update 1000 items. This should still be faster in r371 than it was in r370: previously it would update all items in the entire project bar, but now it only does the relevant families. It's not really clear from your post if this is any faster for your real-world project in r371, but it should be, and it could quite possibly be much faster (as it is only processing a subset of items rather than all items). For virtually all reasonable projects in existence I wouldn't have thought updating all family items like that would pose a performance problem - there are many other cases where branches of the Project Bar are recreated and normally even in large projects it is scoped to a small enough range that it's not noticeable, and modern browsers are so fast that even updating 1000 items should be a reasonably fast operation.

It's possible that family updates could still be made faster, but it is much more complicated, and I suspect yours is the only project, or one of very few projects, that exist where it would make a meaningful difference. Unfortunately I don't think we can afford to prioritise such work, especially as it's possibly not a reasonable use case.

The only valid performance rationale is "I measured a meaningful improvement". Doing things speculatively, or before knowing it really is a performance problem, is usually pointless and just complicates things and causes other problems, like this one. See [Optimisation: don't waste your time](https://www.construct.net/en/blogs/construct-official-blog-1/optimisation-dont-waste-time-768). My advise is make your project in the most obvious, easy way possible; only try to optimise it if performance is not good enough; and then only optimise things based on actual measurements that make a meaningful difference. If you followed this advice I suspect you would not need all these families and would not have this editor performance problem either.

**Closed by AshleyScirra** 2023-12-13 14:55 UTC
Labels: performance

**Comment by OneRepCloser** [comment] 2023-12-13 16:00
Your point about performance does make sense (I've seen you mention it a lot, and for good reason), but this disregards the organizational benefit of having sub-families and the avoidance of instance variable bloat.

Nonetheless, thank you for the advice.

**Comment by OneRepCloser** [comment] 2023-12-13 16:24
@AshleyScirra 

If I may ask, why must all items within the family be updated when a single item within the family is renamed, destroyed or cloned?

Are processes beyond alphabetical sorting and duplicate name checking occuring? (That's all I can see on my end).

**Comment by OneRepCloser** [comment] 2023-12-13 16:56
After considering how I might reduce family counts, I realize this would necessitate adding a significant amount of code as a compensatory measure.

Given this realization, I think I'll accept the drawbacks associated with a high family count for now, as the advantages appear too beneficial at the moment.
