### ISSUE TITLE
r355 : Array table opens as JSON string 

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-bugs#7339] opened 2023-08-27 14:25 UTC
## Problem description

When creating an Array Table file in C3 r354 and opening it in r355, it appears as a JSON code file.

<img width="1027" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/30116964/5222af72-ac56-4c21-be1f-367631bdd525">

## Attach a .c3p
[array_bug.zip](https://github.com/Scirra/Construct-bugs/files/12448171/array_bug.zip)

## Steps to reproduce

1. Open C3 r354
2. Create an Array in the Array Editor
3. Save File
4. Open C3 r355
5. Open said file
6. Open Array File

## Observed result

Array is being opened as a JSON String.

## Expected result

Array to be opened in Array editor in a table format.

## More details

r355

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Edge 115.0.1901.203
Browser engine: Chromium
Context: webapp
Operating system: macOS 13.5.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 2.1 gb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment] 2023-08-27 14:32
Duplicate https://github.com/Scirra/Construct-bugs/issues/7329

**Comment by AshleyScirra** [comment] 2023-08-29 10:59
Duplicate of #7328.

**Closed by AshleyScirra** 2023-08-29 10:59 UTC
