### ISSUE TITLE
Construct 3 IOS Build not working - Time Out

### ISSUE THREAD

**Issue by portugalcsm** [Scirra/Construct-bugs#7046] opened 2023-05-16 13:01 UTC
Construct 3 IOS Build not working - Time Out

Trying to export to IOS 16 - Xcode but getting a Time Out issue...
https://www.youtube.com/watch?v=MeHfMSzCGro

Anyone else with the same issue?

BTW, the other exports are working fine. Just IOS is messed up.

**Comment by AshleyScirra** [comment] 2023-05-16 13:47
Duplicate of #7040 and #7045. Please stop repeatedly contacting support and filing issues about this. It could just be a problem with your Internet connection, in which case it is impossible for us to help. Please see the [Forum & Community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035). We also cannot provide support if all you share is a video. Please see the bug report guidelines as we need all that information to be able to help.

**Closed by AshleyScirra** 2023-05-16 13:47 UTC
Labels: duplicate
