### ISSUE TITLE
Black bars in fullscreen on iOS in Iphone X

### ISSUE THREAD

**Issue by TecenGOD** [Scirra/Construct-bugs#6963] opened 2023-04-22 16:52 UTC
## Problem description

On iOS, the iPhone displays black bars on the R336 version as well as on the R338 beta. This is the same problem as described in #4358
The problem is not permanent and occurs at 20-30% of the game launch

![o4Ij7S3YkJk](https://user-images.githubusercontent.com/7480088/233795931-fcddeef2-5a4e-4314-85d8-1c1898d633a8.jpg)

## Attach a .c3p

[FullscreenBUG_.zip](https://github.com/Scirra/Construct-bugs/files/11301837/FullscreenBUG_.zip)

## Steps to reproduce

1. Export a project to IOS
2. Build in Xcode
3. Start the game and see the black bars with a different chance

## Observed result

Starting a game with black stripes with a 20-30 chance%

## Expected result

Running the game in full screen

## More details
Testing took place on R336 and R336. Used Iphone 11 with the latest version of iOS 16.4.1
The latest Xcode update and Cordova update were also used

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by TecenGOD** [comment] 2023-04-25 15:40
> 

Hmm, I tried rotating the phone in different orientations. This is not a frequent problem, but it does appear and the pattern is not clear... But the problem is the same as it was in the past in #4358

**Comment by AshleyScirra** [comment] 2023-04-25 16:39
Looking at #4358, the end conclusion was that the problem was resolved, so I would suspect any subsequent issue is different and therefore it would not be useful to refer back to the prior issue.

I'm afraid without a way to reproduce the problem the issue is not actionable, in which case our policy is to close the issue. If you can find a more reliable way to reproduce the problem then you can file a new issue.

**Closed by AshleyScirra** 2023-04-25 16:39 UTC
Labels: difficult, can't reproduce, iOS
