### ISSUE TITLE
Objects don't always keep the Z order at game load

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#7292] opened 2023-08-11 00:30 UTC
## Problem description

When loading a game, objects often don't keep the Z order they had when saving.

## Attach a .c3p

[Layer BUG TEST.zip](https://github.com/Scirra/Construct-bugs/files/12317913/Layer.BUG.TEST.zip)

## Steps to reproduce

1. Save the game.
2. Destroy the sprites.
3. Load the game.

## Observed result

The red sprite, that was on top of the green one when the game was saved, is now below it.

## Expected result

The red sprite should keep its Z order and be on top of the green sprite.

## More details

- The issue seems to be related to object UID for some reason.
- The issue seems to happen with different objects, not several istances of the same object.
- If you don't destroy the sprites, the proper Z order is still loaded as intended.

**Affected browsers/platforms:** 
Chrome.

**First affected release:** 
r353

## System details

<details><summary>View details</summary>

Device name	LAPTOP-DAOHK829
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.83 GB usable)
Device ID	3FC91B51-E8DD-4CFB-B006-E1141BF1C7B0
Product ID	00325-82098-04728-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	22H2
Installed on	‎20/‎11/‎2022
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

</details>

**Comment by AshleyScirra** [comment] 2023-08-14 14:00
I think this is a regression caused by dynamic layers in r353, as that involved some complicated changes to savegame code. Thanks for spotting it, it should be fixed in the next beta.

**Closed by AshleyScirra** 2023-08-14 14:00 UTC
