### ISSUE TITLE
Sub layers in Dark Theme

### ISSUE THREAD

**Issue by TecenGOD** [Scirra/Construct-bugs#7063] opened 2023-05-25 08:59 UTC
## Problem description

Sub layers in the Dark theme do not have "arrows" when they are collapsed or expanded. It is very difficult to visually understand when sub layers are expanded and when they are not.

![image](https://github.com/Scirra/Construct-bugs/assets/7480088/e269bddb-5f01-4f97-84c9-e3a958358a7d)

![image](https://github.com/Scirra/Construct-bugs/assets/7480088/1b43ffdc-441a-4812-b5a7-e0a4ee1a6507)

## Observed result

There are no arrows for sub layers, such arrows are available in the default theme

## Expected result

See arrows for sub layers, as in the default theme

## System details

Platform information
Product: Construct 3 r336 (stable)
Browser: Edge 113.0.1774.50
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.50
Language setting: en-US

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment] 2023-05-25 09:20
has already been fixed in the beta :)

**Comment by AshleyScirra** [comment] 2023-05-25 10:59
Duplicate of #5303. As per the bug report guidelines please test the latest beta to avoid reporting problems that have already been solved.

**Closed by AshleyScirra** 2023-05-25 10:59 UTC
Labels: duplicate
