### ISSUE TITLE
Possible post r389 and r409 performance regression

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-bugs#8269] opened 2024-10-02 03:27 UTC
## Problem description

Post r389, there seems to be performance regression as seen in #8259 .

A change was done in r409 to improve the performance regression, but there still seems to be a significant delta in performance between r389 and r409.

## Attach a .c3p
[PerfTest5.zip](https://github.com/user-attachments/files/17219328/PerfTest5.zip)

This is the same test used in #8259 

## Steps to reproduce

Run test on r389 and r409, note CPU and FPS.

## Observed result

Testing on r389 and r409, note CPU and FPS, in our testing in the community there looks to more than a 10% difference.

## Expected result

Similar performance.

## More details

Doing some chrome dev perf traces, it seems like GetX and GetY have the biggest perf difference between r389 and r409. As an experiment, I exported r409 to html and edited the commonACEs.js file to revert _only_ GetX() and GetY() to their prior definition in r389. This was only an experiment to see if a possible cause could be found.

Testing again, the modified r409 version did get a nice performance boost. Here are the three together screen grab from community:

![r389](https://github.com/user-attachments/assets/91c019ee-9414-4f02-af22-347906cd2f81)

I have 3 versions available on the web, first is vanilla r409, second is r409 with GetX() and GetY() modified, third is the rest of the similar functions to GetX and GetY modified. The last one has the best performance.

https://kindeyegames.com/perfOrig/
https://kindeyegames.com/perfMod/ (GetX, GetY changed)
https://kindeyegames.com/perfModMore/ (remaining similar functions changed)

Example of the changes done:
```javascript
return GetWorldInfo(this).GetX()
```
(r409)
back to
```javascript
return this.GetWorldInfo().GetX()
```
(r389)

**Affected browsers/platforms:** 

**First affected release:** 
r390
r409 (partial fix)

So, this is mainly an observation, it would obviously be nice to not have performance regressions, but C3 is being updated for SDK V2 and other features, so I understand it is a question of priorities. if the changes above appear to be the cause, perhaps there is another way to get the same 'feature' result without as much perf impact?

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by JeFawk** [comment] 2024-10-02 10:32
Unsure if this is related, but I'm working on 2 projects, one on the LTS version, another one on the latest stable. 

The latest stable's editor has weird performance problems: sometimes copy-pasting lags, like a lot: it creates the block smaller, and waits for a few seconds, then pastes the content in it.
Other times when pasting, it pastes double.

Noticed random lag in other areas but from the top of my head I cannot remember.

**Comment by AshleyScirra** [comment] 2024-10-02 11:11
In general, it is not feasible to continue developing software with no performance regressions ever. In the past we've had cases where adding a single JavaScript object property increases the memory bandwidth in some benchmark causing a measurable reduction of a few percent in the benchmark score. Or perhaps somewhere we have to insert an `if` that introduces branching in to some intensive benchmark and so slightly reduces the speed - which is what I think happened here. But it's impractical to continue developing Construct if we decide it's not acceptable to add new object properties or `if` statements if they ever produce any kind of measurable performance regression on any kind of benchmark. The real question is: does it affect real-world projects?

I will investigate this anyway in case there is anything feasible that can be done, as I would agree ideally Construct updates should not regress performance where it is possible to avoid it. But really it's a sign of how insanely fast JavaScript and the Construct engine already are that tiny changes can produce measurable differences, and I do think this kind of difference is extremely unlikely to actually affect any real-world projects.

**Comment by dop2000** [comment] 2024-10-02 12:34
> So the real question is: does it affect real-world projects?

This is our game running on my desktop:
![image](https://github.com/user-attachments/assets/58b80aee-a11f-44c4-8b5b-175bfb282871)

2-3 fps deficit is pretty consistent. 
Obviously at 90 fps it's not a problem, but many people play on very low-end devices like chromebooks or Steam Deck with FPS ~30-40. And for such players every frame counts.
I was hoping that the fix for #8320 would improve the performance in the latest releases, but it's actually worse than in pre-390 versions.

**Comment by Jase0000** [comment] 2024-10-02 13:15
Uhhh politely, if your project is getting 95fps on your desktop, and if this bug was fixed tonight and gained you 2 to 3 fps, your project would be stuttery on anyone using a desktop with 120hz or higher monitor, feels like something else is causing your cpu and framerate to be so low.

I've found chromebooks and older laptops to be more of a problem for gpu usage, and rarely cpu usage, depending on how the project's events are designed. Steam deck surely could handle your project at smooth 60fps as it can run triple A games and emulators often at 60fps? 

At the risk of going offtopic, what are your cpu stats in the debugger? Do you use groups and have a specific group hammering the cpu?

I do wish to see all the optimisations. The original post of 14 FPS decrease on a basic template file with not much going on is certainly jarring to see.

**Comment by F3der1co** [comment] 2024-10-02 13:31
I guess Moonstone Island has a lot of systems running in the background, Also idk how powerful the desktop is in this case.

Still regressions like these should definitely be avoided, especially if there is no real major tangible upside that requires that change in the codebase.

**Comment by dop2000** [comment] 2024-10-02 13:36
@Jase0000 Some players are going crazy with farming and decorating, building huge farms and houses, placing thousands of objects. The screenshot above is one of such saves, basically a stress test scenario.
And yes, I know that Steam Deck can handle AAA games, but for some reason the game runs not so great on it. I blame NWjs.

**Comment by F3der1co** [comment] 2024-10-02 13:49
I mean also AAA games tend to use precompiled lower level languages for the performance critical systems, with engineers focusing on optimizing to extremes like SIMD and using much more multi threading. 
Compared to js with a fairly rigid event system built on top, mostly running on a single thread.

**Comment by dop2000** [comment] 2024-10-02 14:34
@Jase0000  I don't want to discuss the inner workings of our project. It has 11K events, we've been developing it for over 3 years and went through many rounds of optimization. Like I said, that screenshot is a stress test scenario, and actually both previews were running simultaneously, because I wanted to push CPU to 100%. (per Ashley's recommendation)
Not all players will have so many objects in the game, but also not all players have powerful gaming computers.

**Comment by Jase0000** [comment] 2024-10-02 15:39
@dop2000 well that was wasted effort on my part at attempting to help, not even a "thanks but no", just a stern reply.

You posted to this bug report, with a stress test screenshot without stating that it is a stress test screenshot and quoting the reply of "does this affect real world projects?" which you later revealed is a unique uncommon situation that only some players will do, so no, that's not a real world example.

Let's say Scirra looks at your screenshot and sees that you are getting 2 to 3 FPS drop: there's no object count, different time in the game on each screenshot - how does anyone know if you had different logic depending on time of day, or your tests had 2 more stray objects in one of the tests affecting cpu, or an NPC might be doing different AI routine on one of the tests, etc.? What _is_ it stress testing, is it draw calls peaking in cpu debugger? Lots of moving objects, lots of npcs? Did you disable all AI, particles, and it's just a map with maybe some animations? If you reveal your object count is 10000 then yeah I bet your cpu is crying even on desktop. 

When stress testing anything, take blank project or example project, disable vsync, FPS will fluctuate, we all know that, rarely will FPS stay at one value.

I do believe you have optimised well, if your desktop is getting 20%-30% cpu on a 144hz display in a more "normal" real world map, then this means if you switch your monitor hz to 60, youll be getting less than 10% to 15% cpu usage, that's incredibly low! I still struggle with lowering draw calls and often sit around 20% on a project with far less images existing at once like your project. 

Your players would recognise that they are on weaker hardware and would expect FPS drops when doing such high amount of chaos in _any_ game, including yours.

It is unreasonable to expect a chromebook or low-end device to handle that stress test map but I'd like to think your regular maps work well on such devices, even with a 2 to 3 FPS drop from this bug. If those type of devices can't run normal maps in your game, then I bet money this bug report isn't going to help that, someone teetering on 57fps is probably going to have FPS drops when particles come onscreen and such, therefore it's why I feel a core optimisation of your project would help significantly more than anything Scirra could do. But hey if you've washed your hands with optimising as it's been 3 years of it then, sure, it's your choice. Makes sense, there's a cap at some point, can't support every low-end device. 

For what it's worth, I too was disappointed that I did not observe any performance different with the "pick children" change, was excited for days but, you win some you lose some I guess.

**Comment by dop2000** [comment] 2024-10-02 16:06
@Jase0000 
> just a stern reply.

Sorry! I appreciate the advice, I just meant that this is probably not a good place to discuss our project, it steers the discussion away.

> of "does this affect real world projects?" which you later revealed is a unique uncommon situation that only some players will do

According to Ashley, "it is only worthwhile to benchmark performance when running at 100% CPU". I can't do this on my PC without pushing the game to the limit. It's an artificial scenario, but still possible for some players.

> how does anyone know if you had different logic depending on time of day

Both previews are running the same project, same save file, same everything. And I repeated the test several times to be sure.

I wanted to demonstrate that there is in fact a drop in difference in a real world project. It is small, but it's still quantifiable.
I am actually curious to see similar tests for other people's games.

**Comment by Jase0000** [comment] 2024-10-02 16:32
@dop2000 it's OK no worries, I was probably locked into problem solving mode and was jarred when it was dismissed entirely, then again why am I giving unsolicited advice on a bug report, could be taken as me undermining your skill as a game dev especially over many years of your efforts (sorry if I came across that way). I did veer off topic too far. 

I see why you stress tested now, no device to test. I see Ashley's response about artificial benchmarking, not sure if your test will fall under that even though you're limited with devices to test, but who knows.

The OP example is quite alarming especially for a far more simple example losing 10% performance... I also wonder who else has noticed any change. I'll check between c3 versions when I'm back at my computer and will report back, assuming I am able to successfully go back to old version.

I am not wised up about sdkv2 but I have a seed of fear - is this currently just a few changes now to the runtime that have lowered cpu performance, but when fully moved to sdkv2, would that mean every aspect of the runtime gets a small performance loss, totalling a huge loss overall in cpu performance far worse than a 10% reduction?

**Comment by DinoSystem** [comment] 2024-10-02 16:33
I  experience this from 389 -> 390! Didn't manage to reliably show this in a new project, but in my game, which is huge, that difference was palpable

**Comment by dop2000** [comment] 2024-10-02 16:37
> when fully moved to sdkv2, would that mean every aspect of the runtime gets a small performance loss, totalling a huge loss overall in cpu performance far worse than a 10% reduction?

Exactly! I think everyone here is worried about this.

@DinoSystem Could you test 389 -> 409?

**Comment by DinoSystem** [comment] 2024-10-02 16:51
Yes, in my game, same exact situation, objects etc, 388.2 is consistantly smoother of any newer version, included 409

**Comment by F3der1co** [comment] 2024-10-02 19:25
Yea I remember, it had like 1-3 fps difference when I tested, but I chalked it up to margin of error or some other cause at that time.

**Comment by dop2000** [comment] 2024-10-03 04:27
Here is a new test, as real world as it can get. Started a new game, everything is by default.
Recorded fps and cpu values every 0.1s for two minutes.
Hardware - laptop with i5-7200U, 8GB RAM.

Character standing idle:
r368: average FPS 59.63, average CPU 39.56%
r409: average FPS 59.418, average CPU 47.57%

Character running around the home island in circles:
r368: average FPS 56.58, average CPU 78.54%
r409: average FPS 55.10, average CPU 78.21% 

Performance drop is small, but it does exist. It would probably be more significant if it wasn't balanced by that "pick children" change. (we are using hierarchies a lot)

**Comment by Jase0000** [comment] 2024-10-03 09:30
Couldn't downgrade to r389 for my main project (I also can't revert to LTS with this project, fails to open) but opened other project with far less going on, and can indeed observe 4% cpu difference:

R389
19% cpu

R409
23% cpu

It's only a slight change and thankfully not 10% difference, although if I had it my way then no, no performance lossess especially CPU as I'm always optimising for cpu usage more than anything in the last few years, but, I'm worried as sdkv2 is implemented more, this is going to increase.

**Comment by Chadori** [comment] 2024-10-04 09:57
I can also confirm this problem. To add, mobile has it worse.

**Comment by AshleyScirra** [comment] 2024-10-08 16:29
I've done more optimization work for the next release to try to further mitigate this. I believe it should run as fast as older releases in most cases again. It is quite a complex change so it is not something we would consider merging to LTS in this case. Marking to check next release to see how it benchmarks in real-world projects.

**Comment by AshleyScirra** [comment] 2024-10-09 12:45
r410 is now out with the change, please try that out - hopefully it restores performance to the original level.

**Comment by MikalDev** [comment] 2024-10-09 21:53
I think it does a nice lift from r409, doesn't quite seem to hit r389, but a nice improvement, I appreciate the work done.

Here's some results from the temple demo, with uncapped frame rate. Yes, this is not a game, this is just for benchmarking to see the difference. I will again say that I understand Scirra has to tradeoff the priorities between perf and requirements of SDKV2, so at some point the performance difference will be considered acceptable vs the requirements of SDK V2. It is also good to benchmark, so the tradeoffs can be better understood.

Unless someone wants to push this further, I am going to close this issue.

Uncapped FPS temple:
R389: 109 FPS https://kindeyegames/perf389-u
R410: 98 FPS https://kindeyegames/perf410-u
R409: 87 FPS https://kindeyegames/perf409-u

![Screenshot_2024-10-09_143859](https://github.com/user-attachments/assets/41ba4284-a3b9-486e-ba2e-160cf32763b1)

**Comment by F3der1co** [comment] 2024-10-14 19:23
due to #8278 this cannot be tested in real projects at the moment

**Comment by AshleyScirra** [comment] 2024-10-18 15:57
I think since r410+ performance should be close to its original level. I don't think there is any more evidence of serious remaining performance regressions, so closing. I'd note that the provided project PerfTest5 appears to mainly be a benchmark of the 'Set color' action which isn't very realistic, so I don't think it's worth going to a lot of effort to further optimize that.

**Closed by AshleyScirra** 2024-10-18 15:57 UTC
Labels: performance
