### ISSUE TITLE
problem displaying translucent png files in the project preview 

### ISSUE THREAD

**Issue by mika222lol** [Scirra/Construct-bugs#7864] opened 2024-02-27 12:08 UTC
## Problem description

object type - sprite. png image with a transparent background and with pixels of different transparency.
the image looks great on the layout and in the sprite editor, but the image is displayed incorrectly in the project preview. all translucent pixels appear to be illuminated. for example, I need to upload an image with a soft gradient on a transparent background. in the preview this image looks terrible. i tried different types of blend mode for sprite but nothing helped...
I work in google chrome on the latest version of comstruct 3, I use an ipad. image color profile - sRGB IEC61966-2.1

## Attach a .c3p

https://drive.google.com/file/d/1PYGcMkTT30CDijGomIjW49pAKV34DkKj/view?usp=drivesdk

## Steps to reproduce

1.open project
2.enable project preview 

## Observed result

Uncorrect image

## Expected result

Correct image
## More details

 google chrome for ipad

**Affected browsers/platforms:** 
Google chrome
 
Current version r379

**First affected release:**  r379

## System details

—

<details><summary>View details</summary>

PASTE HERE

</details>

Uploading RPReplay_Final1709037358.mp4…

**Comment by WilsonPercival** [comment] 2024-02-27 12:14
Could you provide the project file and screenshots?

**Comment by WilsonPercival** [comment] 2024-02-27 13:13
Can not reproduce. Everything is displayed well for me both in the layout editor and in the preview. Can you provide screenshots? Я заметил, что вы пытались прикрепить видео, но вы не дождались, пока оно загрузится, поэтому мы не сможем его посмотреть.

<img width="315" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/91274932/4476be67-a5c5-420d-956d-5fee7595fbb3">

<img width="331" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/91274932/620a88ce-798f-4975-97d7-a8dd4818ead7">

**Comment by AshleyScirra** [comment] 2024-02-27 13:31
It looks identical for me in the Layout View vs. preview. What does it look like for you?

![issue7864](https://github.com/Scirra/Construct-bugs/assets/768723/99299380-5ebf-4fa2-9d2e-18d9ae774e8b)

**Comment by mika222lol** [comment] 2024-02-27 13:43
![1E18CAB5-169A-4F47-8108-735E91929F4C](https://github.com/Scirra/Construct-bugs/assets/161465227/557bcfcc-d0d2-4d11-b665-8621ce2d4629)
![E973AC76-0215-42E3-AC79-BE739B23745E](https://github.com/Scirra/Construct-bugs/assets/161465227/3150b665-ec19-4009-a05d-b898ae182084)

**Comment by XHXIAIEIN** [comment] 2024-02-28 07:45
I suspect this is a visual deviation caused by your monitor or system color configuration. For example try adjusting the gamma value.

**Comment by AshleyScirra** [comment] 2024-03-25 17:24
This does not reproduce on my desktop system in Chrome or Firefox, nor does it reproduce for me on an iPad Air 5th generation running iOS 17.4.1 using either Safari or Chrome (at the moment, Chrome on iOS is just a skin around the Safari browser engine anyway), which I checked as the original report mentions Chrome on iPad. So I can't see anywhere this isn't displaying correctly. My best guess is some settings on the device have been altered which makes it look different. Unfortunately there's not much more we can do without being able to reproduce the problem, so closing.

**Closed by AshleyScirra** 2024-03-25 17:24 UTC
Labels: can't reproduce
