### ISSUE TITLE
set.x action for many objects at once dosen't get triggered by compare.x condition 

### ISSUE THREAD

**Issue by isthirequired** [Scirra/Construct-bugs#7902] opened 2024-03-16 09:57 UTC
## Problem description

many instances of sprite2 (like platforms) 
Sprite have platformer behavious 

if sprite X is less than 500  set sprite.x +500 and sprite2.x+500 
 sprite.x will be set but sprite2.x not always

if sprite behaviour is platformer then the bug happens if it's 8 direction it does not 

https://drive.google.com/file/d/115uwstcLUnGotWc6U3PdtQE7qa3t954a/view?usp=sharing

## Steps to reproduce

1.creat sprite with platformer behaviour
2.create many sprite with solid behaviour
3.add condition if sprite with platformer is past an x value ,  set x of all objects to their original x+500
4. play and move the platformer sprite past the set x

## Observed result

the platformer spirte.x gets set correctly but the solids' x don't get set
(solids dont move)

## Expected result

both the solids and platformer 's x values should be set to x+500

## More details

if the platformer sprite is set to 8 direction movement then everything is correctly moved 

firefox

dosen't work with current version as of posting this issue

## System details

Product: Construct 3 r379 (stable)
Browser: Firefox 123.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.4634146341463414
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
Language setting: en-US
Local storage

Storage quota (approx): 119 gb
Storage usage (approx): 346 mb (0.3%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0), or similar
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    WEBGL_provoking_vertex

Audio information

System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm;codecs=opus)
    WebM Vorbis (audio/webm;codecs=vorbis)
    MPEG-4 Opus (audio/mp4;codecs=opus)
    MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav;codecs=1)

Supported encode formats:

    WebM Opus (audio/webm;codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm;codecs=av01.0.00M.08)
    WebM VP9 (video/webm;codecs=vp9)
    WebM VP8 (video/webm;codecs=vp8)
    MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
    MPEG-4 VP9 (video/mp4;codecs=vp9)
    MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

Supported encode formats:

    WebM VP8 (video/webm;codecs=vp8)

**Comment by WilsonPercival** [comment] 2024-03-16 11:01
The link you provided is not working.

**Comment by WilsonPercival** [comment] 2024-03-18 09:17
It still doesn't work. To make sure the link works, follow it in the incognito tab.

**Comment by AshleyScirra** [comment] 2024-03-18 15:45
The Platform behavior is designed to follow moving platforms when the platform the object is standing on changes positions. Other behaviors do not do this, which is why something like 8 Direction would not seem to be affected. As this is by design, closing as not a bug.

**Closed by AshleyScirra** 2024-03-18 15:45 UTC
Labels: not a bug
