### ISSUE TITLE
AJAX return always same LastData if called inside a function dynamically

### ISSUE THREAD

**Issue by gaglioffo** [Scirra/Construct-bugs#6888] opened 2023-04-09 06:34 UTC
## Problem description
Called dynamically Functions with inside "Ajax" and with action "wait for previous actions to complete" the AJAX.LastData return every time the last file. Same result if flag "Asynchronous" is enable or not.

## Attach a .c3p
[CallAjaxDinamically.zip](https://github.com/Scirra/Construct-bugs/files/11184908/CallAjaxDinamically.zip)

## Steps to reproduce
1. Call dinamically a Function with a loop
2. The function execute a AJAX call
3. Add Action "wait for provious actions to complete" before read AJAX.LastData
5. Print AJAX.LastData or AJAX.Tag

## Observed result
Print/Reads not all files but repeat always the last
`File-2
File-2`

## Expected result
Print/Reads all content of all files called
`File-1
File-2`

## More details
Impossibile to use the Condition "Ajax on compled" inside a Function

**Affected browsers/platforms:** 
Platform: Windows
Browser: Chrome/Firefox/Edge (last release)

**First affected release:** broke in r336

**Comment by WilsonPercival** [comment] 2023-04-09 12:47
Workaround:

[ajax_solution.zip](https://github.com/Scirra/Construct-bugs/files/11185452/ajax_solution.zip)

**Comment by AshleyScirra** [comment] 2023-04-11 15:33
Duplicate of #5514. Since `AJAX.LastData` only returns one string, it cannot be used to distinguish multiple parallel requests. You need to use tags and the 'On completed' trigger instead of 'Wait for previous actions to complete' in this case.

**Closed by AshleyScirra** 2023-04-11 15:33 UTC
Labels: duplicate
