### ISSUE TITLE
C3 crash when Undo button is used while icon sprite is edited

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-bugs#6765] opened 2023-03-13 20:01 UTC
## Problem description
If a modify a sprite icon and click the Undo button C3 will crash.

## Attach a .c3p

Create an empty project.

## Steps to reproduce

1. create an empty project
2. edit one icon 
3. draw a circle in the icon
4. click the undo button

## Observed result

C3 crashed unexpectedly.

## More details

**Affected browsers/platforms:** 
The problem affect both Chrome and Firefox.

**First affected release:** 
I tried with R333
## System details

<details><summary>View details</summary>

PASTE HERE
Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'kk') @ TypeError: Cannot read properties of null (reading 'kk') at Zx.g.K.MSc.Jg (https://editor.construct.net/r333/projectResources.js:2514:418) at Array.XY (https://editor.construct.net/r333/projectResources.js:2511:116) at Dx.g.K.Qb.dispatchEvent (https://editor.construct.net/r333/main.js:1234:42) at https://editor.construct.net/r333/projectResources.js:2552:416
Stack: TypeError: Cannot read properties of null (reading 'kk') at Zx.g.K.MSc.Jg (https://editor.construct.net/r333/projectResources.js:2514:418) at Array.XY (https://editor.construct.net/r333/projectResources.js:2511:116) at Dx.g.K.Qb.dispatchEvent (https://editor.construct.net/r333/main.js:1234:42) at https://editor.construct.net/r333/projectResources.js:2552:416
Construct version: r333
URL: https://editor.construct.net/r333/
Date: Mon Mar 13 2023 20:58:28 GMT+0100 (Central European Standard Time)
Uptime: 1599 s

Platform information
Product: Construct 3 r333 (beta)
Browser: Chrome 110.0.5481.178
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
</details>

**Comment by DiegoScirra** [comment] 2023-03-13 21:53
Duplicate of #6748. This will be fixed in the next beta. Was a regression introduced in r333.

**Closed by DiegoScirra** 2023-03-13 21:53 UTC
Labels: duplicate
