### ISSUE TITLE
Custom Action Crashes Construct 3 after name change (easily repeatable)

### ISSUE THREAD

**Issue by dillontcordova** [Scirra/Construct-bugs#7370] opened 2023-09-06 22:50 UTC
## Problem description

When adding a custom action onto a family and renaming the action within 5 seconds, Construct 3 crashes and doesn't even offer a bug popup as usual. It's a hard uncaught crash it seems.

## Attach a .c3p

https://drive.google.com/file/d/1Yxt0wkx6P2LOFWOFCpR9tTelMhVLCqeF/view?usp=sharing

## Steps to reproduce

1. goto blank event sheet
2. click "add custom action" (don't press ok)
3. choose the family available and immediately rename the default action name, then press Ok

## Observed result

Construct 3 crashes and a google "Aw Snap!" error appears with error code: 5

## Expected result

for the custom action to be renamed to what i typed.

## More details

- Seems to be a timing issue.
- When i create the custom action and just create it with the defaulted Action1 title, works
- When I rename the action but wait 10 seconds before i press okay, works

**Affected browsers/platforms:** 

- Chrome - not working
- Safari - working

**First affected release:** 

- Unsure when it worked properly
- Doesn't work on:
stable - r350
beta: r355
beta: r357
beta: r357.2

## System details

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 116.0.5845.110
Browser engine: Chromium
Context: webapp
Operating system: macOS 12.6.8
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 455 gb
Storage usage (approx): 565 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5500M OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

When adding a custom action on a Family and renaming the default Action1 title quickly then clicking Ok; Construct 3 crashes.

</details>

**Comment by WilsonPercival** [comment] 2023-09-06 23:21
Duplicate https://github.com/Scirra/Construct-bugs/issues/7321

**Comment by AshleyScirra** [comment] 2023-09-08 09:38
Duplicate of #7321.

**Closed by AshleyScirra** 2023-09-08 09:38 UTC
