### ISSUE TITLE
R390 Error "this._iScriptInterface._release is not a function" 

### ISSUE THREAD

**Issue by laputacn** [Scirra/Construct-bugs#8007] opened 2024-05-11 11:47 UTC
## Problem description

When using JS script commands, if the target object has any loading behavior and then jumps to other scenes, an error will occur.

## Attach a .c3p
[testBugInScriptInterface.zip](https://github.com/Scirra/Construct-bugs/files/15282643/testBugInScriptInterface.zip)

## Steps to reproduce

1.Press F4 to preview the project
2.Open browser console
3.Press the B key first
4.Then press the A key

## Observed result
![image](https://github.com/Scirra/Construct-bugs/assets/4530664/8e241c31-94ed-4741-b05a-109a2e5c2172)

**Comment by laputacn** [comment] 2024-05-11 11:59
![image](https://github.com/Scirra/Construct-bugs/assets/4530664/859c5918-eb50-4c5e-a9c1-d79f0952b6c5)

**Comment by DiegoScirra** [comment] 2024-05-11 13:47
Duplicate of #7998

**Closed** 2024-05-11 13:48 UTC
Labels: duplicate
