### ISSUE TITLE
copying & pasting animations/frames 'broken' on multiple browers

### ISSUE THREAD

**Issue by ravengleam** [Scirra/Construct-bugs#8158] opened 2024-08-06 18:07 UTC
## Problem description

using ctrl+c and ctrl+v, or right-clicking to select copy and then paste, seems to work in some browsers but doesn't work in others. got the fewest successes/results in firefox and the most in microsoft edge. 

## Attach a .c3p

[newproject (2).zip](https://github.com/user-attachments/files/16530656/newproject.2.zip)

## Steps to reproduce

1. open attached project (the browsers i individually tested were: firefox, chrome, and edge).
2. select sprite "MyTest" and open animations editor
3. select "Animation 1" in the right animations bar
4. ctrl+c to copy
5. ctrl+v to try to paste
6. repeat with frame 0 in the lower animation 1 frames bar
7. repeat, but this time rather than hot-keys, right-click either "Animation 1" or "frame 0"
8. right-click to try to paste

## Observed result

in firefox, pasting does not appear to work whether you use hot-keys nor right-clicking. 
in chrome, pasting does not appear to work for hot-keys but does work for right-clicking.
in edge, pasting works for both hot-keys and right-clicking.

## Expected result

in all browsers, i was hoping that the copied animation and/or frame would then be pasted, rather than having to rely on right-clicking and selecting 'duplicate'. 

## More details

**Affected browsers/platforms:** firefox, chrome, edge

**First affected release:** r397 stable

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r397 (stable)
Browser: Firefox 128.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
Language setting: en-US
Local storage

Storage quota (approx): 10 gb
Storage usage (approx): 139 mb (1.4%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0), or similar
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    WEBGL_provoking_vertex

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm;codecs=opus)
    WebM Vorbis (audio/webm;codecs=vorbis)
    MPEG-4 Opus (audio/mp4;codecs=opus)
    MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav;codecs=1)

Supported encode formats:

    WebM Opus (audio/webm;codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm;codecs=av01.0.00M.08)
    WebM VP9 (video/webm;codecs=vp9)
    WebM VP8 (video/webm;codecs=vp8)
    MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
    MPEG-4 VP9 (video/mp4;codecs=vp9)
    MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

Supported encode formats:

    WebM VP8 (video/webm;codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2024-08-06 23:55
That file you included is not a C3 project file, it looks like an exported project. Can you add your project file?

**Comment by DiegoScirra** [comment] 2024-08-07 19:58
I could only reproduce this on Firefox.

It seems that Firefox is a bit more strict that Chrome when it comes to the Clipboard API. Since I couldn't reproduce the problem exactly as you mentioned it, you will have to check the next beta to really see if the problem was fixed.

**Comment by AshleyScirra** [comment] 2024-08-20 13:56
r403 is now out - please check again there.

**Comment by DiegoScirra** [comment] 2024-09-19 14:36
Looks like this was forgotten, closing.

**Closed by DiegoScirra** 2024-09-19 14:36 UTC
Labels: need info, firefox
